-- ============================================================
-- Oracle 19c 语法样例
-- 说明: 覆盖 19c LISTAGG DISTINCT 与 MEMOPTIMIZE FOR READ。
-- ============================================================

CREATE TABLE oracle_19_memoptimize_demo (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku VARCHAR2(50) NOT NULL,
    region_code VARCHAR2(30) NOT NULL,
    sales_amount NUMBER(18,2) NOT NULL
) MEMOPTIMIZE FOR READ;

INSERT INTO oracle_19_memoptimize_demo (sku, region_code, sales_amount) VALUES ('ORA19-DEMO-001', 'EAST', 1200.00);
INSERT INTO oracle_19_memoptimize_demo (sku, region_code, sales_amount) VALUES ('ORA19-DEMO-002', 'EAST', 980.00);

SELECT region_code,
       LISTAGG(DISTINCT sku, ', ') WITHIN GROUP (ORDER BY sku) AS sku_list,
       SUM(sales_amount) AS sales_amount
FROM oracle_19_memoptimize_demo
GROUP BY region_code;
