-- ============================================================
-- ERP系统第三批补充表: 合同管理、AR/AP账龄、税务管理、
--   质检、审批流引擎、现金流预测、项目成本、多币种汇率、
--   绩效考核、序列号追踪、寄售库存、价格变更历史
-- 关系说明:
--   contracts -> sales_orders/purchase_orders (1:1), 管理合同条款和里程碑
--   ar_aging / ap_aging: 账龄分析用，按月计算应收账款/应付账款
--   tax_invoices: 增值税发票管理，进项税/销项税
--   inspection_reports: 质检报告，关联采购入库和销售退货
--   approval_workflows: 通用审批流引擎，支持多级审批
--   cash_flow_forecasts: 现金流预测，基于应收应付和计划收支
--   projects + project_costs: 项目成本核算
--   exchange_rates: 多币种汇率管理
--   performance_reviews: 绩效考核
--   serial_numbers: 序列号追踪
--   consignment_inventory: 寄售库存
--   price_change_logs: 价格变更历史
-- ============================================================

-- ============================================================
-- Custom ENUM types
-- ============================================================

-- 合同类型
CREATE TYPE contract_type_type AS ENUM ('sales', 'purchase', 'service', 'lease', 'other');
CREATE TYPE contract_party_type AS ENUM ('customer', 'supplier', 'employee', 'other');
CREATE TYPE contract_status_type AS ENUM ('draft', 'pending_approval', 'active', 'in_progress', 'completed', 'expired', 'terminated', 'cancelled');

-- 里程碑类型
CREATE TYPE milestone_type_type AS ENUM ('delivery', 'payment', 'acceptance', 'renewal', 'other');
CREATE TYPE milestone_status_type AS ENUM ('pending', 'in_progress', 'completed', 'delayed', 'cancelled');

-- 税务发票类型
CREATE TYPE tax_invoice_type_type AS ENUM ('vat_special', 'vat_normal', 'electronic', 'customs');
CREATE TYPE tax_direction_type AS ENUM ('input', 'output');
CREATE TYPE tax_party_type AS ENUM ('supplier', 'customer');
CREATE TYPE tax_verification_status_type AS ENUM ('pending', 'verified', 'certified', 'failed');
CREATE TYPE tax_invoice_status_type AS ENUM ('draft', 'issued', 'verified', 'cancelled', 'red_issued');

-- 税务申报类型
CREATE TYPE tax_filing_type_type AS ENUM ('vat', 'income_tax', 'surtax', 'stamp', 'property', 'other');
CREATE TYPE tax_filing_status_type AS ENUM ('draft', 'prepared', 'filed', 'paid', 'overdue', 'amended');

-- 质检类型
CREATE TYPE sampling_method_type AS ENUM ('full', 'gb2828', 'fixed', 'none');
CREATE TYPE inspection_type_type AS ENUM ('IQC', 'IPQC', 'OQC', 'return_inspection', 'spot_check');
CREATE TYPE inspection_result_type AS ENUM ('qualified', 'conditionally_accepted', 'rejected', 'rework');
CREATE TYPE inspection_status_type AS ENUM ('draft', 'completed', 'reviewed', 'closed');

-- 审批流类型
CREATE TYPE approver_type_type AS ENUM ('role', 'position', 'employee', 'department_manager', 'direct_manager');
CREATE TYPE approval_mode_type AS ENUM ('single', 'countersign', 'or_sign');
CREATE TYPE approval_instance_status_type AS ENUM ('pending', 'in_progress', 'approved', 'rejected', 'recalled', 'timeout');
CREATE TYPE approval_action_type AS ENUM ('approve', 'reject', 'delegate', 'return', 'withdraw');

-- 现金流预测类型
CREATE TYPE forecast_type_type AS ENUM ('daily', 'weekly', 'monthly');

-- 项目类型
CREATE TYPE project_type_type AS ENUM ('engineering', 'rd', 'marketing', 'internal', 'other');
CREATE TYPE project_status_type AS ENUM ('planning', 'in_progress', 'paused', 'completed', 'cancelled');
CREATE TYPE project_priority_type AS ENUM ('low', 'normal', 'high', 'critical');

-- 项目成本类型
CREATE TYPE project_cost_type_type AS ENUM ('labor', 'material', 'equipment', 'travel', 'outsource', 'other');

-- 绩效考核类型
CREATE TYPE performance_review_type_type AS ENUM ('monthly', 'quarterly', 'annual', 'probation', 'promotion');
CREATE TYPE performance_review_status_type AS ENUM ('draft', 'self_reviewed', 'reviewed', 'confirmed', 'appealed');

-- KPI类型
CREATE TYPE kpi_indicator_type_type AS ENUM ('sales', 'financial', 'operational', 'hr', 'customer', 'other');
CREATE TYPE target_direction_type AS ENUM ('higher_better', 'lower_better', 'range');

-- 序列号类型
CREATE TYPE serial_number_status_type AS ENUM ('in_stock', 'in_transit', 'sold', 'returned', 'rma', 'scrapped', 'lost');
CREATE TYPE serial_number_event_type AS ENUM ('purchase_in', 'sales_out', 'return_in', 'transfer', 'scrap', 'rma_out', 'rma_in', 'location_change');

-- 寄售类型
CREATE TYPE consignment_status_type AS ENUM ('active', 'settling', 'settled', 'returned');

-- 价格变更类型
CREATE TYPE price_type_type AS ENUM ('purchase', 'wholesale', 'retail');

-- ============================================================
-- 1. 合同管理模块
-- 合同类型: 销售合同、采购合同、服务合同
-- 合同状态流转: draft -> pending_approval -> active -> in_progress -> completed -> expired -> terminated
-- ============================================================

CREATE TABLE contracts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_no VARCHAR(30) NOT NULL UNIQUE,
    contract_type contract_type_type NOT NULL,
    party_type contract_party_type NOT NULL,
    party_id BIGINT NOT NULL,
    subject VARCHAR(300) NOT NULL,
    total_amount DECIMAL(18,2) NOT NULL,
    currency VARCHAR(3) DEFAULT 'CNY',
    signed_date DATE NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    payment_terms TEXT NULL,
    delivery_terms TEXT NULL,
    status contract_status_type DEFAULT 'draft',
    prepared_by BIGINT CHECK (prepared_by >= 0) NOT NULL,
    approved_by BIGINT NULL,
    signed_by VARCHAR(100) NULL,
    attachment_path VARCHAR(500) NULL,
    remark TEXT NULL,
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ct_prepared FOREIGN KEY (prepared_by) REFERENCES employees(id),
    CONSTRAINT fk_ct_approved FOREIGN KEY (approved_by) REFERENCES employees(id)
);

CREATE INDEX idx_contracts_party ON contracts (party_type, party_id);
CREATE INDEX idx_contracts_status ON contracts (status);
CREATE INDEX idx_contracts_date_range ON contracts (start_date, end_date);
CREATE INDEX idx_contracts_type ON contracts (contract_type);

CREATE TRIGGER trg_contracts_updated_at
    BEFORE UPDATE ON contracts
    FOR EACH ROW
    EXECUTE FUNCTION update_timestamp();

-- 合同里程碑/付款计划
CREATE TABLE contract_milestones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id BIGINT CHECK (contract_id >= 0) NOT NULL,
    milestone_name VARCHAR(200) NOT NULL,
    milestone_type milestone_type_type NOT NULL,
    planned_date DATE NOT NULL,
    actual_date DATE NULL,
    amount DECIMAL(18,2) DEFAULT 0.00,
    completion_pct DECIMAL(5,2) DEFAULT 0.00,
    status milestone_status_type DEFAULT 'pending',
    responsible_person BIGINT NULL,
    remark VARCHAR(500) NULL,
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_cm_contract FOREIGN KEY (contract_id) REFERENCES contracts(id) ON DELETE CASCADE
);

CREATE INDEX idx_contract_milestones_contract ON contract_milestones (contract_id);
CREATE INDEX idx_contract_milestones_planned_date ON contract_milestones (planned_date);
CREATE INDEX idx_contract_milestones_status ON contract_milestones (status);

-- ============================================================
-- 2. 应收账款账龄 (AR Aging)
-- 计算原理: 按账期分桶: 0-30天, 31-60天, 61-90天, 91-180天, 181-365天, >365天
-- 坏账准备: >365天按50%计提, >180天按20%, >90天按5%
-- ============================================================

CREATE TABLE ar_aging_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_date DATE NOT NULL,
    customer_id BIGINT CHECK (customer_id >= 0) NOT NULL,
    order_id BIGINT CHECK (order_id >= 0) NOT NULL,
    invoice_amount DECIMAL(18,2) NOT NULL,
    paid_amount DECIMAL(18,2) DEFAULT 0.00,
    outstanding_amount DECIMAL(18,2) GENERATED ALWAYS AS (invoice_amount - paid_amount) STORED,
    due_date DATE NOT NULL,
    aging_days INTEGER GENERATED ALWAYS AS (snapshot_date - due_date) STORED,
    aging_bucket VARCHAR(20) GENERATED ALWAYS AS (
        CASE
            WHEN snapshot_date - due_date <= 0 THEN '未到期'
            WHEN snapshot_date - due_date <= 30 THEN '1-30天'
            WHEN snapshot_date - due_date <= 60 THEN '31-60天'
            WHEN snapshot_date - due_date <= 90 THEN '61-90天'
            WHEN snapshot_date - due_date <= 180 THEN '91-180天'
            WHEN snapshot_date - due_date <= 365 THEN '181-365天'
            ELSE '365天以上'
        END
    ) STORED,
    bad_debt_provision DECIMAL(18,2) GENERATED ALWAYS AS (
        ROUND((invoice_amount - paid_amount) *
        CASE
            WHEN snapshot_date - due_date <= 90 THEN 0.00
            WHEN snapshot_date - due_date <= 180 THEN 0.05
            WHEN snapshot_date - due_date <= 365 THEN 0.20
            ELSE 0.50
        END, 2)
    ) STORED,
    last_collection_date DATE NULL,
    collection_notes VARCHAR(500) NULL,
    CONSTRAINT fk_ar_customer FOREIGN KEY (customer_id) REFERENCES customers(id),
    CONSTRAINT fk_ar_order FOREIGN KEY (order_id) REFERENCES sales_orders(id)
);

CREATE INDEX idx_ar_aging_customer ON ar_aging_snapshots (customer_id);
CREATE INDEX idx_ar_aging_bucket ON ar_aging_snapshots (aging_bucket);
CREATE INDEX idx_ar_aging_snapshot_date ON ar_aging_snapshots (snapshot_date);
CREATE INDEX idx_ar_aging_due_date ON ar_aging_snapshots (due_date);

-- 应付账款账龄 (AP Aging)
CREATE TABLE ap_aging_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_date DATE NOT NULL,
    supplier_id BIGINT CHECK (supplier_id >= 0) NOT NULL,
    order_id BIGINT CHECK (order_id >= 0) NOT NULL,
    invoice_amount DECIMAL(18,2) NOT NULL,
    paid_amount DECIMAL(18,2) DEFAULT 0.00,
    outstanding_amount DECIMAL(18,2) GENERATED ALWAYS AS (invoice_amount - paid_amount) STORED,
    due_date DATE NOT NULL,
    aging_bucket VARCHAR(20) GENERATED ALWAYS AS (
        CASE
            WHEN snapshot_date - due_date <= 0 THEN '未到期'
            WHEN snapshot_date - due_date <= 30 THEN '1-30天'
            WHEN snapshot_date - due_date <= 60 THEN '31-60天'
            WHEN snapshot_date - due_date <= 90 THEN '61-90天'
            WHEN snapshot_date - due_date <= 180 THEN '91-180天'
            WHEN snapshot_date - due_date <= 365 THEN '181-365天'
            ELSE '365天以上'
        END
    ) STORED,
    planned_payment_date DATE NULL,
    CONSTRAINT fk_ap_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers(id),
    CONSTRAINT fk_ap_order FOREIGN KEY (order_id) REFERENCES purchase_orders(id)
);

CREATE INDEX idx_ap_aging_supplier ON ap_aging_snapshots (supplier_id);
CREATE INDEX idx_ap_aging_bucket ON ap_aging_snapshots (aging_bucket);
CREATE INDEX idx_ap_aging_due_date ON ap_aging_snapshots (due_date);

-- ============================================================
-- 3. 税务管理模块 (增值税)
-- 税率: 13%(一般货物), 9%(农产品/图书), 6%(服务), 0%(出口)
-- 进项税 = 采购发票税额, 销项税 = 销售发票税额
-- 应交增值税 = 销项税 - 进项税
-- ============================================================

CREATE TABLE tax_invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_no VARCHAR(50) NOT NULL UNIQUE,
    invoice_code VARCHAR(50) NULL,
    invoice_type tax_invoice_type_type NOT NULL,
    tax_direction tax_direction_type NOT NULL,
    party_type tax_party_type NOT NULL,
    party_id BIGINT NOT NULL,
    invoice_date DATE NOT NULL,
    amount_excluding_tax DECIMAL(18,2) NOT NULL,
    tax_rate DECIMAL(5,4) NOT NULL,
    tax_amount DECIMAL(18,2) GENERATED ALWAYS AS (ROUND(amount_excluding_tax * tax_rate, 2)) STORED,
    amount_including_tax DECIMAL(18,2) GENERATED ALWAYS AS (amount_excluding_tax + ROUND(amount_excluding_tax * tax_rate, 2)) STORED,
    verification_status tax_verification_status_type DEFAULT 'pending',
    verified_at TIMESTAMP(0) NULL,
    verified_by BIGINT NULL,
    tax_period VARCHAR(7) NOT NULL,
    deduction_period VARCHAR(7) NULL,
    reference_type VARCHAR(50) NULL,
    reference_id BIGINT NULL,
    status tax_invoice_status_type DEFAULT 'draft',
    remark VARCHAR(500) NULL,
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ti_verified FOREIGN KEY (verified_by) REFERENCES employees(id)
);

CREATE INDEX idx_tax_invoices_party ON tax_invoices (party_type, party_id);
CREATE INDEX idx_tax_invoices_tax_period ON tax_invoices (tax_period);
CREATE INDEX idx_tax_invoices_direction ON tax_invoices (tax_direction);
CREATE INDEX idx_tax_invoices_status ON tax_invoices (status);
CREATE INDEX idx_tax_invoices_invoice_date ON tax_invoices (invoice_date);

CREATE TRIGGER trg_tax_invoices_updated_at
    BEFORE UPDATE ON tax_invoices
    FOR EACH ROW
    EXECUTE FUNCTION update_timestamp();

-- 税务申报记录
CREATE TABLE tax_filings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tax_period VARCHAR(7) NOT NULL,
    tax_type tax_filing_type_type NOT NULL,
    output_tax DECIMAL(18,2) DEFAULT 0.00,
    input_tax DECIMAL(18,2) DEFAULT 0.00,
    input_tax_transfer DECIMAL(18,2) DEFAULT 0.00,
    tax_payable DECIMAL(18,2) DEFAULT 0.00,
    tax_paid DECIMAL(18,2) DEFAULT 0.00,
    filing_date DATE NULL,
    filing_deadline DATE NOT NULL,
    status tax_filing_status_type DEFAULT 'draft',
    prepared_by BIGINT NULL,
    voucher_id BIGINT NULL,
    remark VARCHAR(500) NULL,
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_tax_filings_period_type UNIQUE (tax_period, tax_type),
    CONSTRAINT fk_tf_prepared FOREIGN KEY (prepared_by) REFERENCES employees(id)
);

CREATE INDEX idx_tax_filings_status ON tax_filings (status);
CREATE INDEX idx_tax_filings_deadline ON tax_filings (filing_deadline);

CREATE TRIGGER trg_tax_filings_updated_at
    BEFORE UPDATE ON tax_filings
    FOR EACH ROW
    EXECUTE FUNCTION update_timestamp();

-- ============================================================
-- 4. 质量检验模块
-- 检验类型: 来料检验(IQC), 过程检验(IPQC), 出货检验(OQC), 退货检验
-- 检验结果: 合格/不合格/让步接收/退货
-- ============================================================

CREATE TABLE inspection_standards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT CHECK (product_id >= 0) NOT NULL,
    standard_name VARCHAR(200) NOT NULL,
    inspection_items JSONB NULL,
    sampling_method sampling_method_type DEFAULT 'gb2828',
    sample_size INTEGER DEFAULT 0,
    aql_level DECIMAL(5,2) DEFAULT 1.0,
    status active_status DEFAULT 'active',
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_inspection_standards_product UNIQUE (product_id, standard_name),
    CONSTRAINT fk_is_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);

CREATE TABLE inspection_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_no VARCHAR(30) NOT NULL UNIQUE,
    inspection_type inspection_type_type NOT NULL,
    reference_type VARCHAR(50) NOT NULL,
    reference_id BIGINT NOT NULL,
    product_id BIGINT CHECK (product_id >= 0) NOT NULL,
    batch_id BIGINT NULL,
    standard_id BIGINT NULL,
    sample_size INTEGER NOT NULL,
    inspected_qty INTEGER NOT NULL,
    qualified_qty INTEGER DEFAULT 0,
    defective_qty INTEGER DEFAULT 0,
    defect_rate DECIMAL(5,2) GENERATED ALWAYS AS (
        ROUND(defective_qty * 100.0 / NULLIF(inspected_qty, 0), 2)
    ) STORED,
    inspection_result inspection_result_type NOT NULL,
    inspector_id BIGINT CHECK (inspector_id >= 0) NOT NULL,
    inspection_date DATE NOT NULL,
    defect_description TEXT NULL,
    disposition VARCHAR(200) NULL,
    status inspection_status_type DEFAULT 'draft',
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ir_product FOREIGN KEY (product_id) REFERENCES products(id),
    CONSTRAINT fk_ir_batch FOREIGN KEY (batch_id) REFERENCES product_batches(id) ON DELETE SET NULL,
    CONSTRAINT fk_ir_standard FOREIGN KEY (standard_id) REFERENCES inspection_standards(id) ON DELETE SET NULL,
    CONSTRAINT fk_ir_inspector FOREIGN KEY (inspector_id) REFERENCES employees(id)
);

CREATE INDEX idx_inspection_reports_product ON inspection_reports (product_id);
CREATE INDEX idx_inspection_reports_batch ON inspection_reports (batch_id);
CREATE INDEX idx_inspection_reports_reference ON inspection_reports (reference_type, reference_id);
CREATE INDEX idx_inspection_reports_result ON inspection_reports (inspection_result);
CREATE INDEX idx_inspection_reports_date ON inspection_reports (inspection_date);

CREATE TRIGGER trg_inspection_reports_updated_at
    BEFORE UPDATE ON inspection_reports
    FOR EACH ROW
    EXECUTE FUNCTION update_timestamp();

-- ============================================================
-- 5. 通用审批流引擎
-- 支持多级审批: 部门经理 -> 总监 -> 总经理
-- 审批节点可配置，支持会签/或签
-- ============================================================

CREATE TABLE approval_workflows (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_name VARCHAR(100) NOT NULL,
    workflow_code VARCHAR(30) NOT NULL UNIQUE,
    target_type VARCHAR(50) NOT NULL,
    description VARCHAR(500) NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE approval_nodes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_id BIGINT CHECK (workflow_id >= 0) NOT NULL,
    node_name VARCHAR(100) NOT NULL,
    node_level INTEGER NOT NULL,
    approver_type approver_type_type NOT NULL,
    approver_id BIGINT NULL,
    approval_mode approval_mode_type DEFAULT 'single',
    timeout_hours INTEGER DEFAULT 48,
    can_delegate BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_approval_nodes_workflow_level UNIQUE (workflow_id, node_level),
    CONSTRAINT fk_an_workflow FOREIGN KEY (workflow_id) REFERENCES approval_workflows(id) ON DELETE CASCADE
);

CREATE TABLE approval_instances (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instance_no VARCHAR(30) NOT NULL UNIQUE,
    workflow_id BIGINT CHECK (workflow_id >= 0) NOT NULL,
    target_type VARCHAR(50) NOT NULL,
    target_id BIGINT NOT NULL,
    target_summary VARCHAR(500) NULL,
    current_node_level INTEGER DEFAULT 1,
    total_nodes INTEGER DEFAULT 1,
    submitted_by BIGINT CHECK (submitted_by >= 0) NOT NULL,
    submitted_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    status approval_instance_status_type DEFAULT 'pending',
    completed_at TIMESTAMP(0) NULL,
    remark VARCHAR(500) NULL,
    CONSTRAINT fk_ai_workflow FOREIGN KEY (workflow_id) REFERENCES approval_workflows(id),
    CONSTRAINT fk_ai_submitted FOREIGN KEY (submitted_by) REFERENCES employees(id)
);

CREATE INDEX idx_approval_instances_target ON approval_instances (target_type, target_id);
CREATE INDEX idx_approval_instances_status ON approval_instances (status);
CREATE INDEX idx_approval_instances_submitted ON approval_instances (submitted_by, submitted_at);

CREATE TABLE approval_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instance_id BIGINT CHECK (instance_id >= 0) NOT NULL,
    node_id BIGINT CHECK (node_id >= 0) NOT NULL,
    approver_id BIGINT CHECK (approver_id >= 0) NOT NULL,
    action approval_action_type NOT NULL,
    comment VARCHAR(500) NULL,
    action_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    delegated_to BIGINT NULL,
    CONSTRAINT fk_ar_instance FOREIGN KEY (instance_id) REFERENCES approval_instances(id) ON DELETE CASCADE,
    CONSTRAINT fk_ar_node FOREIGN KEY (node_id) REFERENCES approval_nodes(id),
    CONSTRAINT fk_ar_approver FOREIGN KEY (approver_id) REFERENCES employees(id)
);

CREATE INDEX idx_approval_records_instance ON approval_records (instance_id);

-- ============================================================
-- 6. 现金流预测
-- 预测来源: 应收款到期日 + 应付款到期日 + 工资发放计划 + 计划收支
-- 按日/周/月汇总预测净现金流
-- ============================================================

CREATE TABLE cash_flow_forecasts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    forecast_date DATE NOT NULL,
    forecast_type forecast_type_type NOT NULL,
    beginning_balance DECIMAL(18,2) DEFAULT 0.00,
    expected_collections DECIMAL(18,2) DEFAULT 0.00,
    expected_payments DECIMAL(18,2) DEFAULT 0.00,
    expected_salary DECIMAL(18,2) DEFAULT 0.00,
    expected_tax DECIMAL(18,2) DEFAULT 0.00,
    other_income DECIMAL(18,2) DEFAULT 0.00,
    other_expense DECIMAL(18,2) DEFAULT 0.00,
    net_cash_flow DECIMAL(18,2) GENERATED ALWAYS AS (
        expected_collections - expected_payments - expected_salary - expected_tax + other_income - other_expense
    ) STORED,
    ending_balance DECIMAL(18,2) GENERATED ALWAYS AS (
        beginning_balance + expected_collections - expected_payments - expected_salary - expected_tax + other_income - other_expense
    ) STORED,
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_cash_flow_forecast_date_type UNIQUE (forecast_date, forecast_type)
);

CREATE INDEX idx_cash_flow_forecasts_date ON cash_flow_forecasts (forecast_date);

-- ============================================================
-- 7. 项目成本核算
-- 项目类型: 工程项目、研发项目、营销活动等
-- 成本归集: 人工成本+材料成本+费用+外包
-- ============================================================

CREATE TABLE projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_no VARCHAR(30) NOT NULL UNIQUE,
    name VARCHAR(200) NOT NULL,
    project_type project_type_type NOT NULL,
    department_id BIGINT CHECK (department_id >= 0) NOT NULL,
    manager_id BIGINT CHECK (manager_id >= 0) NOT NULL,
    budget DECIMAL(18,2) NOT NULL,
    start_date DATE NOT NULL,
    planned_end_date DATE NOT NULL,
    actual_end_date DATE NULL,
    status project_status_type DEFAULT 'planning',
    priority project_priority_type DEFAULT 'normal',
    description TEXT NULL,
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_proj_dept FOREIGN KEY (department_id) REFERENCES departments(id),
    CONSTRAINT fk_proj_manager FOREIGN KEY (manager_id) REFERENCES employees(id)
);

CREATE INDEX idx_projects_dept ON projects (department_id);
CREATE INDEX idx_projects_manager ON projects (manager_id);
CREATE INDEX idx_projects_status ON projects (status);

CREATE TRIGGER trg_projects_updated_at
    BEFORE UPDATE ON projects
    FOR EACH ROW
    EXECUTE FUNCTION update_timestamp();

CREATE TABLE project_costs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT CHECK (project_id >= 0) NOT NULL,
    cost_type project_cost_type_type NOT NULL,
    cost_date DATE NOT NULL,
    amount DECIMAL(18,2) NOT NULL,
    description VARCHAR(500) NULL,
    reference_type VARCHAR(50) NULL,
    reference_id BIGINT NULL,
    recorded_by BIGINT NULL,
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_pc_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
);

CREATE INDEX idx_project_costs_project ON project_costs (project_id);
CREATE INDEX idx_project_costs_date ON project_costs (cost_date);
CREATE INDEX idx_project_costs_type ON project_costs (cost_type);

-- ============================================================
-- 8. 多币种与汇率管理
-- ============================================================

CREATE TABLE exchange_rates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_currency VARCHAR(3) NOT NULL,
    to_currency VARCHAR(3) NOT NULL DEFAULT 'CNY',
    rate_date DATE NOT NULL,
    rate DECIMAL(12,6) NOT NULL,
    rate_source VARCHAR(50) DEFAULT 'BOC',
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_exchange_rates_currency_date UNIQUE (from_currency, to_currency, rate_date)
);

CREATE INDEX idx_exchange_rates_date ON exchange_rates (rate_date);

-- 外币账户
CREATE TABLE foreign_currency_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT CHECK (account_id >= 0) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    original_balance DECIMAL(18,2) DEFAULT 0.00,
    cny_equivalent DECIMAL(18,2) DEFAULT 0.00,
    last_revaluation_date DATE NULL,
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_foreign_currency_accounts_account_currency UNIQUE (account_id, currency),
    CONSTRAINT fk_fca_account FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE
);

-- ============================================================
-- 9. 绩效考核模块
-- 考核周期: 月度/季度/年度
-- 评分维度: 业绩(40%) + 能力(30%) + 态度(20%) + 出勤(10%)
-- ============================================================

CREATE TABLE performance_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_no VARCHAR(30) NOT NULL UNIQUE,
    employee_id BIGINT CHECK (employee_id >= 0) NOT NULL,
    reviewer_id BIGINT CHECK (reviewer_id >= 0) NOT NULL,
    review_period VARCHAR(7) NOT NULL,
    review_type performance_review_type_type NOT NULL,
    -- 评分维度
    performance_score DECIMAL(5,2) DEFAULT 0.00,
    competency_score DECIMAL(5,2) DEFAULT 0.00,
    attitude_score DECIMAL(5,2) DEFAULT 0.00,
    attendance_score DECIMAL(5,2) DEFAULT 0.00,
    -- 加权总分 (业绩40% + 能力30% + 态度20% + 出勤10%)
    total_score DECIMAL(5,2) GENERATED ALWAYS AS (
        ROUND(performance_score * 0.40 + competency_score * 0.30 + attitude_score * 0.20 + attendance_score * 0.10, 2)
    ) STORED,
    grade CHAR(1) GENERATED ALWAYS AS (
        CASE
            WHEN ROUND(performance_score * 0.40 + competency_score * 0.30 + attitude_score * 0.20 + attendance_score * 0.10, 2) >= 90 THEN 'S'
            WHEN ROUND(performance_score * 0.40 + competency_score * 0.30 + attitude_score * 0.20 + attendance_score * 0.10, 2) >= 80 THEN 'A'
            WHEN ROUND(performance_score * 0.40 + competency_score * 0.30 + attitude_score * 0.20 + attendance_score * 0.10, 2) >= 70 THEN 'B'
            WHEN ROUND(performance_score * 0.40 + competency_score * 0.30 + attitude_score * 0.20 + attendance_score * 0.10, 2) >= 60 THEN 'C'
            ELSE 'D'
        END
    ) STORED,
    self_assessment TEXT NULL,
    reviewer_comment TEXT NULL,
    improvement_plan TEXT NULL,
    salary_adjustment DECIMAL(12,2) DEFAULT 0.00,
    promotion_recommendation BOOLEAN DEFAULT FALSE,
    status performance_review_status_type DEFAULT 'draft',
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_performance_reviews_emp_period_type UNIQUE (employee_id, review_period, review_type),
    CONSTRAINT fk_pr_employee FOREIGN KEY (employee_id) REFERENCES employees(id),
    CONSTRAINT fk_pr_reviewer FOREIGN KEY (reviewer_id) REFERENCES employees(id)
);

CREATE INDEX idx_performance_reviews_reviewer ON performance_reviews (reviewer_id);
CREATE INDEX idx_performance_reviews_grade ON performance_reviews (grade);
CREATE INDEX idx_performance_reviews_period ON performance_reviews (review_period);

CREATE TRIGGER trg_performance_reviews_updated_at
    BEFORE UPDATE ON performance_reviews
    FOR EACH ROW
    EXECUTE FUNCTION update_timestamp();

-- KPI指标定义
CREATE TABLE kpi_indicators (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    indicator_type kpi_indicator_type_type NOT NULL,
    unit VARCHAR(20) NOT NULL,
    target_direction target_direction_type NOT NULL,
    target_value DECIMAL(12,2) NOT NULL,
    target_min DECIMAL(12,2) NULL,
    target_max DECIMAL(12,2) NULL,
    weight DECIMAL(5,4) DEFAULT 1.0,
    applicable_role_id BIGINT NULL,
    department_id BIGINT NULL,
    status active_status DEFAULT 'active',
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_kpi_indicators_role ON kpi_indicators (applicable_role_id);
CREATE INDEX idx_kpi_indicators_dept ON kpi_indicators (department_id);

-- ============================================================
-- 10. 序列号追踪 (单品追踪)
-- 用于高价值商品(电子产品/设备)的单品全生命周期追踪
-- 生命周期: 采购入库 -> 库存 -> 销售出库 -> 客户 -> 退货 -> 翻新 -> 重新入库
-- ============================================================

CREATE TABLE serial_numbers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT CHECK (product_id >= 0) NOT NULL,
    batch_id BIGINT NULL,
    serial_no VARCHAR(100) NOT NULL,
    status serial_number_status_type DEFAULT 'in_stock',
    warehouse_id BIGINT NULL,
    purchase_receipt_id BIGINT NULL,
    sales_order_id BIGINT NULL,
    return_id BIGINT NULL,
    current_owner_id BIGINT NULL,
    warranty_start DATE NULL,
    warranty_end DATE NULL,
    last_scan_date TIMESTAMP(0) NULL,
    last_scan_location VARCHAR(200) NULL,
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_serial_numbers_product_serial UNIQUE (product_id, serial_no),
    CONSTRAINT fk_sn_product FOREIGN KEY (product_id) REFERENCES products(id),
    CONSTRAINT fk_sn_batch FOREIGN KEY (batch_id) REFERENCES product_batches(id) ON DELETE SET NULL,
    CONSTRAINT fk_sn_wh FOREIGN KEY (warehouse_id) REFERENCES warehouses(id) ON DELETE SET NULL
);

CREATE INDEX idx_serial_numbers_status ON serial_numbers (status);
CREATE INDEX idx_serial_numbers_batch ON serial_numbers (batch_id);
CREATE INDEX idx_serial_numbers_warehouse ON serial_numbers (warehouse_id);
CREATE INDEX idx_serial_numbers_warranty ON serial_numbers (warranty_end);

CREATE TRIGGER trg_serial_numbers_updated_at
    BEFORE UPDATE ON serial_numbers
    FOR EACH ROW
    EXECUTE FUNCTION update_timestamp();

-- 序列号流转日志
CREATE TABLE serial_number_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    serial_number_id BIGINT CHECK (serial_number_id >= 0) NOT NULL,
    event_type serial_number_event_type NOT NULL,
    from_status VARCHAR(20) NULL,
    to_status VARCHAR(20) NOT NULL,
    from_location VARCHAR(200) NULL,
    to_location VARCHAR(200) NULL,
    reference_type VARCHAR(50) NULL,
    reference_id BIGINT NULL,
    operator_id BIGINT NULL,
    event_time TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    remark VARCHAR(500) NULL,
    CONSTRAINT fk_snl_sn FOREIGN KEY (serial_number_id) REFERENCES serial_numbers(id) ON DELETE CASCADE
);

CREATE INDEX idx_serial_number_logs_sn ON serial_number_logs (serial_number_id);
CREATE INDEX idx_serial_number_logs_event_time ON serial_number_logs (event_time);

-- ============================================================
-- 11. 寄售库存
-- 寄售: 货品存放在客户处，客户使用时才结算
-- 所有权仍属于我方，不确认收入
-- ============================================================

CREATE TABLE consignment_inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT CHECK (product_id >= 0) NOT NULL,
    batch_id BIGINT NULL,
    customer_id BIGINT CHECK (customer_id >= 0) NOT NULL,
    consigned_qty INTEGER NOT NULL,
    consumed_qty INTEGER DEFAULT 0,
    available_qty INTEGER GENERATED ALWAYS AS (consigned_qty - consumed_qty) STORED,
    unit_price DECIMAL(12,2) NOT NULL,
    consigned_date DATE NOT NULL,
    last_consumed_date DATE NULL,
    settlement_period VARCHAR(7) NULL,
    status consignment_status_type DEFAULT 'active',
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_consignment_inventory_product_batch_customer UNIQUE (product_id, batch_id, customer_id),
    CONSTRAINT fk_ci_product FOREIGN KEY (product_id) REFERENCES products(id),
    CONSTRAINT fk_ci_batch FOREIGN KEY (batch_id) REFERENCES product_batches(id) ON DELETE SET NULL,
    CONSTRAINT fk_ci_customer FOREIGN KEY (customer_id) REFERENCES customers(id)
);

CREATE INDEX idx_consignment_inventory_customer ON consignment_inventory (customer_id);
CREATE INDEX idx_consignment_inventory_status ON consignment_inventory (status);

CREATE TRIGGER trg_consignment_inventory_updated_at
    BEFORE UPDATE ON consignment_inventory
    FOR EACH ROW
    EXECUTE FUNCTION update_timestamp();

-- 寄售消耗记录
CREATE TABLE consignment_consumptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    consignment_id BIGINT CHECK (consignment_id >= 0) NOT NULL,
    consumed_qty INTEGER NOT NULL,
    consumed_date DATE NOT NULL,
    unit_price DECIMAL(12,2) NOT NULL,
    amount DECIMAL(18,2) GENERATED ALWAYS AS (consumed_qty * unit_price) STORED,
    confirmed_by_customer BOOLEAN DEFAULT FALSE,
    sales_order_id BIGINT NULL,
    remark VARCHAR(200) NULL,
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_cc_consignment FOREIGN KEY (consignment_id) REFERENCES consignment_inventory(id) ON DELETE CASCADE
);

CREATE INDEX idx_consignment_consumptions_consignment ON consignment_consumptions (consignment_id);
CREATE INDEX idx_consignment_consumptions_date ON consignment_consumptions (consumed_date);

-- ============================================================
-- 12. 价格变更历史
-- 记录所有价格变更，用于价格分析和审计
-- ============================================================

CREATE TABLE price_change_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT CHECK (product_id >= 0) NOT NULL,
    price_type price_type_type NOT NULL,
    old_price DECIMAL(12,2) NOT NULL,
    new_price DECIMAL(12,2) NOT NULL,
    change_reason VARCHAR(200) NOT NULL,
    effective_date DATE NOT NULL,
    changed_by BIGINT CHECK (changed_by >= 0) NOT NULL,
    approved_by BIGINT NULL,
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_pcl_product FOREIGN KEY (product_id) REFERENCES products(id),
    CONSTRAINT fk_pcl_changed FOREIGN KEY (changed_by) REFERENCES employees(id)
);

CREATE INDEX idx_price_change_logs_product ON price_change_logs (product_id);
CREATE INDEX idx_price_change_logs_effective_date ON price_change_logs (effective_date);
CREATE INDEX idx_price_change_logs_price_type ON price_change_logs (price_type);
