-- ============================================================
-- ERP系统企业级扩展表 - PostgreSQL 16
-- 覆盖: 多租户/账套、地址、税率、会计期间、收付款、
--       库存盘点/调拨/预留、工艺路线/工序、班次排班
-- 数据库: PostgreSQL 16
-- ============================================================

-- ============================================================
-- Custom ENUM types
-- ============================================================

CREATE TYPE tenant_status_type AS ENUM ('active', 'suspended', 'closed');
CREATE TYPE ledger_book_status_type AS ENUM ('active', 'closed');
CREATE TYPE customer_address_type AS ENUM ('registered', 'billing', 'shipping', 'contact');
CREATE TYPE supplier_address_type AS ENUM ('registered', 'billing', 'warehouse', 'contact');
CREATE TYPE tax_rate_type AS ENUM ('vat', 'income_tax', 'surtax', 'stamp', 'other');
CREATE TYPE tax_rate_status_type AS ENUM ('active', 'expired');
CREATE TYPE accounting_period_status_type AS ENUM ('open', 'closing', 'closed', 'locked');
CREATE TYPE period_close_job_status_type AS ENUM ('pending', 'running', 'success', 'failed', 'skipped');
CREATE TYPE payment_receipt_type AS ENUM ('customer_receipt', 'supplier_payment', 'refund_payment', 'internal_transfer');
CREATE TYPE payment_party_type AS ENUM ('customer', 'supplier', 'employee', 'internal');
CREATE TYPE payment_receipt_status_type AS ENUM ('draft', 'confirmed', 'reconciled', 'cancelled');
CREATE TYPE payment_allocation_reference_type AS ENUM ('sales_order', 'purchase_order', 'sales_return', 'purchase_return', 'invoice', 'settlement');
CREATE TYPE stocktake_type_type AS ENUM ('full', 'cycle', 'spot');
CREATE TYPE stocktake_status_type AS ENUM ('draft', 'counting', 'reviewed', 'posted', 'cancelled');
CREATE TYPE stock_transfer_status_type AS ENUM ('draft', 'approved', 'in_transit', 'received', 'cancelled');
CREATE TYPE reservation_source_type AS ENUM ('sales_order', 'work_order', 'transfer', 'service_ticket');
CREATE TYPE reservation_status_type AS ENUM ('reserved', 'partially_released', 'released', 'cancelled');
CREATE TYPE production_route_status_type AS ENUM ('draft', 'active', 'retired');
CREATE TYPE shift_assignment_status_type AS ENUM ('planned', 'confirmed', 'cancelled');

-- 多租户与账套
CREATE TABLE tenants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_code VARCHAR(30) NOT NULL UNIQUE,
    tenant_name VARCHAR(100) NOT NULL,
    legal_entity_name VARCHAR(200) NOT NULL,
    tax_no VARCHAR(30) NULL,
    status tenant_status_type DEFAULT 'active',
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER trg_tenants_updated_at
    BEFORE UPDATE ON tenants
    FOR EACH ROW EXECUTE FUNCTION update_timestamp();

CREATE TABLE ledger_books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    book_code VARCHAR(30) NOT NULL,
    book_name VARCHAR(100) NOT NULL,
    base_currency VARCHAR(3) DEFAULT 'CNY',
    fiscal_year_start_month SMALLINT DEFAULT 1 CHECK (fiscal_year_start_month BETWEEN 1 AND 12),
    is_default BOOLEAN DEFAULT FALSE,
    status ledger_book_status_type DEFAULT 'active',
    CONSTRAINT uk_ledger_book UNIQUE (tenant_id, book_code),
    CONSTRAINT fk_ledger_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id)
);

-- 客户/供应商多地址
CREATE TABLE customer_addresses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    address_type customer_address_type NOT NULL,
    receiver_name VARCHAR(100) NULL,
    receiver_phone VARCHAR(30) NULL,
    province VARCHAR(50) NOT NULL,
    city VARCHAR(50) NOT NULL,
    district VARCHAR(50) NULL,
    street VARCHAR(300) NOT NULL,
    postal_code VARCHAR(20) NULL,
    is_default BOOLEAN DEFAULT FALSE,
    CONSTRAINT fk_customer_address_customer FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE
);

CREATE INDEX idx_customer_address_city ON customer_addresses (province, city);
CREATE INDEX idx_customer_address_default ON customer_addresses (customer_id, is_default);

CREATE TABLE supplier_addresses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id BIGINT NOT NULL,
    address_type supplier_address_type NOT NULL,
    contact_name VARCHAR(100) NULL,
    contact_phone VARCHAR(30) NULL,
    province VARCHAR(50) NOT NULL,
    city VARCHAR(50) NOT NULL,
    district VARCHAR(50) NULL,
    street VARCHAR(300) NOT NULL,
    postal_code VARCHAR(20) NULL,
    is_default BOOLEAN DEFAULT FALSE,
    CONSTRAINT fk_supplier_address_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE CASCADE
);

CREATE INDEX idx_supplier_address_city ON supplier_addresses (province, city);
CREATE INDEX idx_supplier_address_default ON supplier_addresses (supplier_id, is_default);

-- 税率和会计期间
CREATE TABLE tax_rates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tax_code VARCHAR(30) NOT NULL UNIQUE,
    tax_name VARCHAR(100) NOT NULL,
    tax_type tax_rate_type NOT NULL,
    rate DECIMAL(8,4) NOT NULL,
    effective_from DATE NOT NULL,
    effective_to DATE NULL,
    status tax_rate_status_type DEFAULT 'active'
);

CREATE INDEX idx_tax_rate_effective ON tax_rates (tax_type, effective_from, effective_to);

CREATE TABLE accounting_periods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ledger_book_id BIGINT NOT NULL,
    period_code VARCHAR(7) NOT NULL,
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    status accounting_period_status_type DEFAULT 'open',
    closed_by BIGINT NULL,
    closed_at TIMESTAMP(0) NULL,
    CONSTRAINT uk_accounting_period UNIQUE (ledger_book_id, period_code),
    CONSTRAINT fk_period_book FOREIGN KEY (ledger_book_id) REFERENCES ledger_books(id),
    CONSTRAINT fk_period_closed_by FOREIGN KEY (closed_by) REFERENCES employees(id)
);

CREATE TABLE period_close_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    period_id BIGINT NOT NULL,
    job_code VARCHAR(30) NOT NULL,
    job_name VARCHAR(100) NOT NULL,
    status period_close_job_status_type DEFAULT 'pending',
    started_at TIMESTAMP(0) NULL,
    finished_at TIMESTAMP(0) NULL,
    message VARCHAR(1000) NULL,
    CONSTRAINT uk_period_job UNIQUE (period_id, job_code),
    CONSTRAINT fk_period_close_job_period FOREIGN KEY (period_id) REFERENCES accounting_periods(id) ON DELETE CASCADE
);

-- 收付款流水与分配
CREATE TABLE payment_receipts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_no VARCHAR(30) NOT NULL UNIQUE,
    receipt_type payment_receipt_type NOT NULL,
    party_type payment_party_type NOT NULL,
    party_id BIGINT NULL,
    account_id BIGINT NOT NULL,
    receipt_date DATE NOT NULL,
    amount DECIMAL(18,2) NOT NULL,
    currency VARCHAR(3) DEFAULT 'CNY',
    status payment_receipt_status_type DEFAULT 'draft',
    handled_by BIGINT NOT NULL,
    confirmed_at TIMESTAMP(0) NULL,
    remark VARCHAR(500) NULL,
    CONSTRAINT fk_payment_receipt_account FOREIGN KEY (account_id) REFERENCES accounts(id),
    CONSTRAINT fk_payment_receipt_handler FOREIGN KEY (handled_by) REFERENCES employees(id)
);

CREATE INDEX idx_payment_receipt_party ON payment_receipts (party_type, party_id);
CREATE INDEX idx_payment_receipt_date ON payment_receipts (receipt_date);

CREATE TABLE payment_receipt_allocations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_id BIGINT NOT NULL,
    reference_type payment_allocation_reference_type NOT NULL,
    reference_id BIGINT NOT NULL,
    allocated_amount DECIMAL(18,2) NOT NULL,
    CONSTRAINT fk_payment_allocation_receipt FOREIGN KEY (receipt_id) REFERENCES payment_receipts(id) ON DELETE CASCADE
);

CREATE INDEX idx_payment_allocation_reference ON payment_receipt_allocations (reference_type, reference_id);

-- 库存盘点、调拨和预留
CREATE TABLE stocktakes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stocktake_no VARCHAR(30) NOT NULL UNIQUE,
    warehouse_id BIGINT NOT NULL,
    stocktake_date DATE NOT NULL,
    stocktake_type stocktake_type_type DEFAULT 'cycle',
    status stocktake_status_type DEFAULT 'draft',
    created_by BIGINT NOT NULL,
    reviewed_by BIGINT NULL,
    posted_at TIMESTAMP(0) NULL,
    CONSTRAINT fk_stocktake_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouses(id),
    CONSTRAINT fk_stocktake_created_by FOREIGN KEY (created_by) REFERENCES employees(id),
    CONSTRAINT fk_stocktake_reviewed_by FOREIGN KEY (reviewed_by) REFERENCES employees(id)
);

CREATE TABLE stocktake_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stocktake_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    batch_id BIGINT NULL,
    book_quantity INTEGER NOT NULL,
    counted_quantity INTEGER NOT NULL,
    variance_quantity INTEGER GENERATED ALWAYS AS (counted_quantity - book_quantity) STORED,
    variance_reason VARCHAR(300) NULL,
    CONSTRAINT fk_stocktake_item_stocktake FOREIGN KEY (stocktake_id) REFERENCES stocktakes(id) ON DELETE CASCADE,
    CONSTRAINT fk_stocktake_item_product FOREIGN KEY (product_id) REFERENCES products(id),
    CONSTRAINT fk_stocktake_item_batch FOREIGN KEY (batch_id) REFERENCES product_batches(id)
);

CREATE INDEX idx_stocktake_item_product ON stocktake_items (product_id, batch_id);

CREATE TABLE stock_transfers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transfer_no VARCHAR(30) NOT NULL UNIQUE,
    from_warehouse_id BIGINT NOT NULL,
    to_warehouse_id BIGINT NOT NULL,
    requested_by BIGINT NOT NULL,
    approved_by BIGINT NULL,
    transfer_date DATE NOT NULL,
    status stock_transfer_status_type DEFAULT 'draft',
    CONSTRAINT fk_transfer_from_wh FOREIGN KEY (from_warehouse_id) REFERENCES warehouses(id),
    CONSTRAINT fk_transfer_to_wh FOREIGN KEY (to_warehouse_id) REFERENCES warehouses(id),
    CONSTRAINT fk_transfer_requested_by FOREIGN KEY (requested_by) REFERENCES employees(id),
    CONSTRAINT fk_transfer_approved_by FOREIGN KEY (approved_by) REFERENCES employees(id)
);

CREATE TABLE stock_transfer_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transfer_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    batch_id BIGINT NULL,
    quantity INTEGER NOT NULL,
    received_quantity INTEGER DEFAULT 0,
    CONSTRAINT fk_transfer_item_transfer FOREIGN KEY (transfer_id) REFERENCES stock_transfers(id) ON DELETE CASCADE,
    CONSTRAINT fk_transfer_item_product FOREIGN KEY (product_id) REFERENCES products(id),
    CONSTRAINT fk_transfer_item_batch FOREIGN KEY (batch_id) REFERENCES product_batches(id)
);

CREATE TABLE inventory_reservations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_no VARCHAR(30) NOT NULL UNIQUE,
    product_id BIGINT NOT NULL,
    batch_id BIGINT NULL,
    warehouse_id BIGINT NOT NULL,
    source_type reservation_source_type NOT NULL,
    source_id BIGINT NOT NULL,
    reserved_quantity INTEGER NOT NULL,
    released_quantity INTEGER DEFAULT 0,
    status reservation_status_type DEFAULT 'reserved',
    expires_at TIMESTAMP(0) NULL,
    CONSTRAINT fk_inv_res_product FOREIGN KEY (product_id) REFERENCES products(id),
    CONSTRAINT fk_inv_res_batch FOREIGN KEY (batch_id) REFERENCES product_batches(id),
    CONSTRAINT fk_inv_res_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouses(id)
);

CREATE INDEX idx_inv_res_source ON inventory_reservations (source_type, source_id);

-- 工艺路线、工序和班次
CREATE TABLE production_routes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    route_code VARCHAR(30) NOT NULL,
    route_name VARCHAR(100) NOT NULL,
    version_no VARCHAR(20) NOT NULL,
    status production_route_status_type DEFAULT 'draft',
    CONSTRAINT uk_product_route UNIQUE (product_id, route_code, version_no),
    CONSTRAINT fk_route_product FOREIGN KEY (product_id) REFERENCES products(id)
);

CREATE TABLE production_operations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_id BIGINT NOT NULL,
    operation_no INTEGER NOT NULL CHECK (operation_no > 0),
    operation_name VARCHAR(100) NOT NULL,
    work_center VARCHAR(100) NOT NULL,
    standard_minutes DECIMAL(10,2) NOT NULL,
    predecessor_operation_id BIGINT NULL,
    CONSTRAINT uk_route_operation UNIQUE (route_id, operation_no),
    CONSTRAINT fk_operation_route FOREIGN KEY (route_id) REFERENCES production_routes(id) ON DELETE CASCADE,
    CONSTRAINT fk_operation_predecessor FOREIGN KEY (predecessor_operation_id) REFERENCES production_operations(id)
);

CREATE TABLE employee_shifts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shift_code VARCHAR(20) NOT NULL UNIQUE,
    shift_name VARCHAR(100) NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    planned_hours DECIMAL(4,2) NOT NULL,
    is_night_shift BOOLEAN DEFAULT FALSE
);

CREATE TABLE employee_shift_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL,
    shift_id BIGINT NOT NULL,
    work_date DATE NOT NULL,
    warehouse_id BIGINT NULL,
    status shift_assignment_status_type DEFAULT 'planned',
    CONSTRAINT uk_employee_shift_date UNIQUE (employee_id, work_date),
    CONSTRAINT fk_shift_assignment_employee FOREIGN KEY (employee_id) REFERENCES employees(id),
    CONSTRAINT fk_shift_assignment_shift FOREIGN KEY (shift_id) REFERENCES employee_shifts(id),
    CONSTRAINT fk_shift_assignment_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouses(id)
);
