-- ============================================================
-- ERP系统企业级扩展表 - Oracle 26ai
-- 覆盖: 多租户/账套、地址、税率、会计期间、收付款、
--       库存盘点/调拨/预留、工艺路线/工序、班次排班
-- 数据库: Oracle 26ai
-- ============================================================

-- ============================================================
-- Custom ENUM types
-- ============================================================

-- 多租户与账套
CREATE TABLE tenants (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_code VARCHAR2(30) NOT NULL UNIQUE,
    tenant_name VARCHAR2(100) NOT NULL,
    legal_entity_name VARCHAR2(200) NOT NULL,
    tax_no VARCHAR2(30) NULL,
    status VARCHAR2(40) DEFAULT 'active',
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP
);

CREATE OR REPLACE TRIGGER trg_tenants_updated_at
    BEFORE UPDATE ON tenants
    FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

CREATE TABLE ledger_books (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id NUMBER(19) NOT NULL,
    book_code VARCHAR2(30) NOT NULL,
    book_name VARCHAR2(100) NOT NULL,
    base_currency VARCHAR2(3) DEFAULT 'CNY',
    fiscal_year_start_month NUMBER(5) DEFAULT 1 CHECK (fiscal_year_start_month BETWEEN 1 AND 12),
    is_default NUMBER(1) DEFAULT 0,
    status VARCHAR2(40) DEFAULT 'active',
    CONSTRAINT uk_ledger_book UNIQUE (tenant_id, book_code),
    CONSTRAINT fk_ledger_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id)
);

-- 客户/供应商多地址
CREATE TABLE customer_addresses (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id NUMBER(19) NOT NULL,
    address_type VARCHAR2(40) NOT NULL,
    receiver_name VARCHAR2(100) NULL,
    receiver_phone VARCHAR2(30) NULL,
    province VARCHAR2(50) NOT NULL,
    city VARCHAR2(50) NOT NULL,
    district VARCHAR2(50) NULL,
    street VARCHAR2(300) NOT NULL,
    postal_code VARCHAR2(20) NULL,
    is_default NUMBER(1) DEFAULT 0,
    CONSTRAINT fk_customer_address_customer FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE
);

CREATE INDEX idx_customer_address_city ON customer_addresses (province, city);
CREATE INDEX idx_customer_address_default ON customer_addresses (customer_id, is_default);

CREATE TABLE supplier_addresses (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id NUMBER(19) NOT NULL,
    address_type VARCHAR2(40) NOT NULL,
    contact_name VARCHAR2(100) NULL,
    contact_phone VARCHAR2(30) NULL,
    province VARCHAR2(50) NOT NULL,
    city VARCHAR2(50) NOT NULL,
    district VARCHAR2(50) NULL,
    street VARCHAR2(300) NOT NULL,
    postal_code VARCHAR2(20) NULL,
    is_default NUMBER(1) DEFAULT 0,
    CONSTRAINT fk_supplier_address_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE CASCADE
);

CREATE INDEX idx_supplier_address_city ON supplier_addresses (province, city);
CREATE INDEX idx_supplier_address_default ON supplier_addresses (supplier_id, is_default);

-- 税率和会计期间
CREATE TABLE tax_rates (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tax_code VARCHAR2(30) NOT NULL UNIQUE,
    tax_name VARCHAR2(100) NOT NULL,
    tax_type VARCHAR2(40) NOT NULL,
    rate NUMBER(8,4) NOT NULL,
    effective_from DATE NOT NULL,
    effective_to DATE NULL,
    status VARCHAR2(40) DEFAULT 'active'
);

CREATE INDEX idx_tax_rate_effective ON tax_rates (tax_type, effective_from, effective_to);

CREATE TABLE accounting_periods (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ledger_book_id NUMBER(19) NOT NULL,
    period_code VARCHAR2(7) NOT NULL,
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    status VARCHAR2(40) DEFAULT 'open',
    closed_by NUMBER(19) NULL,
    closed_at TIMESTAMP(0) NULL,
    CONSTRAINT uk_accounting_period UNIQUE (ledger_book_id, period_code),
    CONSTRAINT fk_period_book FOREIGN KEY (ledger_book_id) REFERENCES ledger_books(id),
    CONSTRAINT fk_period_closed_by FOREIGN KEY (closed_by) REFERENCES employees(id)
);

CREATE TABLE period_close_jobs (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    period_id NUMBER(19) NOT NULL,
    job_code VARCHAR2(30) NOT NULL,
    job_name VARCHAR2(100) NOT NULL,
    status VARCHAR2(40) DEFAULT 'pending',
    started_at TIMESTAMP(0) NULL,
    finished_at TIMESTAMP(0) NULL,
    message VARCHAR2(1000) NULL,
    CONSTRAINT uk_period_job UNIQUE (period_id, job_code),
    CONSTRAINT fk_period_close_job_period FOREIGN KEY (period_id) REFERENCES accounting_periods(id) ON DELETE CASCADE
);

-- 收付款流水与分配
CREATE TABLE payment_receipts (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_no VARCHAR2(30) NOT NULL UNIQUE,
    receipt_type VARCHAR2(40) NOT NULL,
    party_type VARCHAR2(40) NOT NULL,
    party_id NUMBER(19) NULL,
    account_id NUMBER(19) NOT NULL,
    receipt_date DATE NOT NULL,
    amount NUMBER(18,2) NOT NULL,
    currency VARCHAR2(3) DEFAULT 'CNY',
    status VARCHAR2(40) DEFAULT 'draft',
    handled_by NUMBER(19) NOT NULL,
    confirmed_at TIMESTAMP(0) NULL,
    remark VARCHAR2(500) NULL,
    CONSTRAINT fk_payment_receipt_account FOREIGN KEY (account_id) REFERENCES accounts(id),
    CONSTRAINT fk_payment_receipt_handler FOREIGN KEY (handled_by) REFERENCES employees(id)
);

CREATE INDEX idx_payment_receipt_party ON payment_receipts (party_type, party_id);
CREATE INDEX idx_payment_receipt_date ON payment_receipts (receipt_date);

CREATE TABLE payment_receipt_allocations (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_id NUMBER(19) NOT NULL,
    reference_type VARCHAR2(40) NOT NULL,
    reference_id NUMBER(19) NOT NULL,
    allocated_amount NUMBER(18,2) NOT NULL,
    CONSTRAINT fk_payment_allocation_receipt FOREIGN KEY (receipt_id) REFERENCES payment_receipts(id) ON DELETE CASCADE
);

CREATE INDEX idx_payment_allocation_reference ON payment_receipt_allocations (reference_type, reference_id);

-- 库存盘点、调拨和预留
CREATE TABLE stocktakes (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stocktake_no VARCHAR2(30) NOT NULL UNIQUE,
    warehouse_id NUMBER(19) NOT NULL,
    stocktake_date DATE NOT NULL,
    stocktake_type VARCHAR2(40) DEFAULT 'cycle',
    status VARCHAR2(40) DEFAULT 'draft',
    created_by NUMBER(19) NOT NULL,
    reviewed_by NUMBER(19) NULL,
    posted_at TIMESTAMP(0) NULL,
    CONSTRAINT fk_stocktake_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouses(id),
    CONSTRAINT fk_stocktake_created_by FOREIGN KEY (created_by) REFERENCES employees(id),
    CONSTRAINT fk_stocktake_reviewed_by FOREIGN KEY (reviewed_by) REFERENCES employees(id)
);

CREATE TABLE stocktake_items (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stocktake_id NUMBER(19) NOT NULL,
    product_id NUMBER(19) NOT NULL,
    batch_id NUMBER(19) NULL,
    book_quantity NUMBER(10) NOT NULL,
    counted_quantity NUMBER(10) NOT NULL,
    variance_quantity NUMBER(10) GENERATED ALWAYS AS (counted_quantity - book_quantity) VIRTUAL,
    variance_reason VARCHAR2(300) NULL,
    CONSTRAINT fk_stocktake_item_stocktake FOREIGN KEY (stocktake_id) REFERENCES stocktakes(id) ON DELETE CASCADE,
    CONSTRAINT fk_stocktake_item_product FOREIGN KEY (product_id) REFERENCES products(id),
    CONSTRAINT fk_stocktake_item_batch FOREIGN KEY (batch_id) REFERENCES product_batches(id)
);

CREATE INDEX idx_stocktake_item_product ON stocktake_items (product_id, batch_id);

CREATE TABLE stock_transfers (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transfer_no VARCHAR2(30) NOT NULL UNIQUE,
    from_warehouse_id NUMBER(19) NOT NULL,
    to_warehouse_id NUMBER(19) NOT NULL,
    requested_by NUMBER(19) NOT NULL,
    approved_by NUMBER(19) NULL,
    transfer_date DATE NOT NULL,
    status VARCHAR2(40) DEFAULT 'draft',
    CONSTRAINT fk_transfer_from_wh FOREIGN KEY (from_warehouse_id) REFERENCES warehouses(id),
    CONSTRAINT fk_transfer_to_wh FOREIGN KEY (to_warehouse_id) REFERENCES warehouses(id),
    CONSTRAINT fk_transfer_requested_by FOREIGN KEY (requested_by) REFERENCES employees(id),
    CONSTRAINT fk_transfer_approved_by FOREIGN KEY (approved_by) REFERENCES employees(id)
);

CREATE TABLE stock_transfer_items (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transfer_id NUMBER(19) NOT NULL,
    product_id NUMBER(19) NOT NULL,
    batch_id NUMBER(19) NULL,
    quantity NUMBER(10) NOT NULL,
    received_quantity NUMBER(10) DEFAULT 0,
    CONSTRAINT fk_transfer_item_transfer FOREIGN KEY (transfer_id) REFERENCES stock_transfers(id) ON DELETE CASCADE,
    CONSTRAINT fk_transfer_item_product FOREIGN KEY (product_id) REFERENCES products(id),
    CONSTRAINT fk_transfer_item_batch FOREIGN KEY (batch_id) REFERENCES product_batches(id)
);

CREATE TABLE inventory_reservations (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_no VARCHAR2(30) NOT NULL UNIQUE,
    product_id NUMBER(19) NOT NULL,
    batch_id NUMBER(19) NULL,
    warehouse_id NUMBER(19) NOT NULL,
    source_type VARCHAR2(40) NOT NULL,
    source_id NUMBER(19) NOT NULL,
    reserved_quantity NUMBER(10) NOT NULL,
    released_quantity NUMBER(10) DEFAULT 0,
    status VARCHAR2(40) DEFAULT 'reserved',
    expires_at TIMESTAMP(0) NULL,
    CONSTRAINT fk_inv_res_product FOREIGN KEY (product_id) REFERENCES products(id),
    CONSTRAINT fk_inv_res_batch FOREIGN KEY (batch_id) REFERENCES product_batches(id),
    CONSTRAINT fk_inv_res_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouses(id)
);

CREATE INDEX idx_inv_res_source ON inventory_reservations (source_type, source_id);

-- 工艺路线、工序和班次
CREATE TABLE production_routes (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id NUMBER(19) NOT NULL,
    route_code VARCHAR2(30) NOT NULL,
    route_name VARCHAR2(100) NOT NULL,
    version_no VARCHAR2(20) NOT NULL,
    status VARCHAR2(40) DEFAULT 'draft',
    CONSTRAINT uk_product_route UNIQUE (product_id, route_code, version_no),
    CONSTRAINT fk_route_product FOREIGN KEY (product_id) REFERENCES products(id)
);

CREATE TABLE production_operations (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_id NUMBER(19) NOT NULL,
    operation_no NUMBER(10) NOT NULL CHECK (operation_no > 0),
    operation_name VARCHAR2(100) NOT NULL,
    work_center VARCHAR2(100) NOT NULL,
    standard_minutes NUMBER(10,2) NOT NULL,
    predecessor_operation_id NUMBER(19) NULL,
    CONSTRAINT uk_route_operation UNIQUE (route_id, operation_no),
    CONSTRAINT fk_operation_route FOREIGN KEY (route_id) REFERENCES production_routes(id) ON DELETE CASCADE,
    CONSTRAINT fk_operation_predecessor FOREIGN KEY (predecessor_operation_id) REFERENCES production_operations(id)
);

CREATE TABLE employee_shifts (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shift_code VARCHAR2(20) NOT NULL UNIQUE,
    shift_name VARCHAR2(100) NOT NULL,
    start_time VARCHAR2(8) NOT NULL,
    end_time VARCHAR2(8) NOT NULL,
    planned_hours NUMBER(4,2) NOT NULL,
    is_night_shift NUMBER(1) DEFAULT 0
);

CREATE TABLE employee_shift_assignments (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id NUMBER(19) NOT NULL,
    shift_id NUMBER(19) NOT NULL,
    work_date DATE NOT NULL,
    warehouse_id NUMBER(19) NULL,
    status VARCHAR2(40) DEFAULT 'planned',
    CONSTRAINT uk_employee_shift_date UNIQUE (employee_id, work_date),
    CONSTRAINT fk_shift_assignment_employee FOREIGN KEY (employee_id) REFERENCES employees(id),
    CONSTRAINT fk_shift_assignment_shift FOREIGN KEY (shift_id) REFERENCES employee_shifts(id),
    CONSTRAINT fk_shift_assignment_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouses(id)
);
