-- ============================================================
-- ERP系统补充表: 发货物流、销售提成、促销活动、
--   三单匹配、固定资产、BOM生产工单、客服工单
-- 关系说明:
--   shipments -> sales_orders (1:1), 通过tracking_no追踪物流
--   sales_commissions -> sales_orders + employees (N:1:1), 按销售额计算提成
--   promotions -> sales_order_items (N:M), 通过promotion_items关联
--   invoices -> purchase_orders + purchase_receipts (三单匹配)
--   fixed_assets + depreciation_log (固定资产+折旧)
--   boms -> products (自引用), 生产工单用料展开
--   work_orders -> boms + products (生产工单)
-- ============================================================

-- ============================================================
-- Custom ENUM types
-- ============================================================

CREATE TYPE shipping_method_type AS ENUM ('express', 'truck', 'air', 'sea', 'self_pickup');
CREATE TYPE shipment_status_type AS ENUM ('pending', 'picking', 'packed', 'shipped', 'in_transit', 'delivered', 'returned', 'lost');
CREATE TYPE commission_rule_status_type AS ENUM ('active', 'inactive');
CREATE TYPE commission_status_type AS ENUM ('pending', 'calculated', 'paid', 'cancelled');
CREATE TYPE promotion_type_type AS ENUM ('discount_pct', 'discount_amount', 'buy_x_get_y', 'bundle', 'coupon', 'flash_sale');
CREATE TYPE promotion_status_type AS ENUM ('draft', 'active', 'paused', 'ended', 'cancelled');
CREATE TYPE invoice_type_type AS ENUM ('purchase', 'sales', 'expense');
CREATE TYPE invoice_status_type AS ENUM ('draft', 'received', 'verified', 'matched', 'paid', 'partial_paid', 'disputed', 'cancelled');
CREATE TYPE match_status_type AS ENUM ('pending', 'matched', 'quantity_mismatch', 'price_mismatch', 'both_mismatch');
CREATE TYPE asset_category_type AS ENUM ('building', 'equipment', 'vehicle', 'furniture', 'computer', 'software', 'other');
CREATE TYPE asset_status_type AS ENUM ('in_use', 'idle', 'maintenance', 'scrapped', 'disposed');
CREATE TYPE bom_status_type AS ENUM ('active', 'inactive', 'obsolete');
CREATE TYPE work_order_status_type AS ENUM ('draft', 'released', 'in_progress', 'completed', 'cancelled', 'on_hold');
CREATE TYPE priority_type AS ENUM ('low', 'normal', 'high', 'urgent');
CREATE TYPE wom_status_type AS ENUM ('pending', 'partial', 'issued', 'completed');
CREATE TYPE ticket_type_type AS ENUM ('complaint', 'return', 'exchange', 'inquiry', 'maintenance', 'other');
CREATE TYPE ticket_status_type AS ENUM ('open', 'processing', 'waiting_customer', 'resolved', 'closed', 'escalated');

-- ============================================================
-- 1. 发货物流模块
-- shipments: 发货单 -> 关联sales_orders
-- shipping_tracks: 物流轨迹 -> 关联shipments
-- ============================================================

CREATE TABLE shipments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_no VARCHAR(30) NOT NULL UNIQUE,
    order_id BIGINT CHECK (order_id >= 0) NOT NULL,
    warehouse_id BIGINT CHECK (warehouse_id >= 0) NOT NULL,
    carrier VARCHAR(100) NOT NULL,
    tracking_no VARCHAR(50) NULL,
    shipping_method shipping_method_type DEFAULT 'express',
    shipping_fee DECIMAL(12,2) DEFAULT 0.00,
    package_count INTEGER DEFAULT 1,
    weight_kg DECIMAL(8,3) DEFAULT 0.000,
    status shipment_status_type DEFAULT 'pending',
    picker_id BIGINT NULL,
    packer_id BIGINT NULL,
    shipped_at TIMESTAMP(0) NULL,
    delivered_at TIMESTAMP(0) NULL,
    estimated_delivery_date DATE NULL,
    actual_delivery_date DATE NULL,
    from_address VARCHAR(300) NULL,
    to_address VARCHAR(300) NOT NULL,
    receiver_name VARCHAR(50) NULL,
    receiver_phone VARCHAR(20) NULL,
    remark VARCHAR(500) NULL,
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ship_order FOREIGN KEY (order_id) REFERENCES sales_orders(id),
    CONSTRAINT fk_ship_wh FOREIGN KEY (warehouse_id) REFERENCES warehouses(id)
);

CREATE INDEX idx_shipments_order ON shipments (order_id);
CREATE INDEX idx_shipments_tracking ON shipments (tracking_no);
CREATE INDEX idx_shipments_status ON shipments (status);
CREATE INDEX idx_shipments_carrier ON shipments (carrier);
CREATE INDEX idx_shipments_shipped_at ON shipments (shipped_at);

CREATE TRIGGER trg_shipments_updated_at
    BEFORE UPDATE ON shipments
    FOR EACH ROW
    EXECUTE FUNCTION update_timestamp();

CREATE TABLE shipping_tracks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_id BIGINT CHECK (shipment_id >= 0) NOT NULL,
    track_time TIMESTAMP(0) NOT NULL,
    location VARCHAR(200) NOT NULL,
    status_desc VARCHAR(200) NOT NULL,
    operator VARCHAR(50) NULL,
    remark VARCHAR(200) NULL,
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_st_shipment FOREIGN KEY (shipment_id) REFERENCES shipments(id) ON DELETE CASCADE
);

CREATE INDEX idx_shipping_tracks_shipment ON shipping_tracks (shipment_id);
CREATE INDEX idx_shipping_tracks_track_time ON shipping_tracks (track_time);

-- ============================================================
-- 2. 销售提成模块
-- 提成规则: 不同产品/分类不同提成比例
-- 销售额阶梯提成，超过目标有额外奖励
-- ============================================================

CREATE TABLE commission_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    product_category_id BIGINT NULL,
    min_amount DECIMAL(18,2) DEFAULT 0.00,
    max_amount DECIMAL(18,2) DEFAULT 99999999.99,
    commission_rate DECIMAL(5,4) NOT NULL,
    bonus DECIMAL(12,2) DEFAULT 0.00,
    effective_date DATE NOT NULL,
    expiry_date DATE NULL,
    status commission_rule_status_type DEFAULT 'active',
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_cr_category FOREIGN KEY (product_category_id) REFERENCES product_categories(id) ON DELETE SET NULL
);

CREATE INDEX idx_commission_rules_category ON commission_rules (product_category_id);
CREATE INDEX idx_commission_rules_effective ON commission_rules (effective_date, expiry_date);

CREATE TABLE sales_commissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT CHECK (employee_id >= 0) NOT NULL,
    order_id BIGINT CHECK (order_id >= 0) NOT NULL,
    order_item_id BIGINT NULL,
    period VARCHAR(7) NOT NULL,
    base_amount DECIMAL(18,2) NOT NULL,
    commission_rate DECIMAL(5,4) NOT NULL,
    commission_amount DECIMAL(12,2) NOT NULL,
    bonus DECIMAL(12,2) DEFAULT 0.00,
    total_commission DECIMAL(12,2) GENERATED ALWAYS AS (commission_amount + bonus) STORED,
    status commission_status_type DEFAULT 'pending',
    calculated_at TIMESTAMP(0) NULL,
    paid_at TIMESTAMP(0) NULL,
    settlement_id BIGINT NULL,
    CONSTRAINT uk_sales_commissions_order_item UNIQUE (order_id, order_item_id),
    CONSTRAINT fk_sc_emp FOREIGN KEY (employee_id) REFERENCES employees(id),
    CONSTRAINT fk_sc_order FOREIGN KEY (order_id) REFERENCES sales_orders(id)
);

CREATE INDEX idx_sales_commissions_employee ON sales_commissions (employee_id);
CREATE INDEX idx_sales_commissions_period ON sales_commissions (period);
CREATE INDEX idx_sales_commissions_status ON sales_commissions (status);

-- ============================================================
-- 3. 促销活动模块
-- ============================================================

CREATE TABLE promotions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    code VARCHAR(30) NOT NULL UNIQUE,
    promotion_type promotion_type_type NOT NULL,
    discount_value DECIMAL(12,2) NOT NULL,
    min_purchase_amount DECIMAL(18,2) DEFAULT 0.00,
    max_discount_amount DECIMAL(12,2) DEFAULT 0.00,
    usage_limit INTEGER DEFAULT 0,
    used_count INTEGER DEFAULT 0,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    status promotion_status_type DEFAULT 'draft',
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_promotions_date_range ON promotions (start_date, end_date);
CREATE INDEX idx_promotions_status ON promotions (status);
CREATE INDEX idx_promotions_code ON promotions (code);

CREATE TRIGGER trg_promotions_updated_at
    BEFORE UPDATE ON promotions
    FOR EACH ROW
    EXECUTE FUNCTION update_timestamp();

CREATE TABLE promotion_products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    promotion_id BIGINT CHECK (promotion_id >= 0) NOT NULL,
    product_id BIGINT NULL,
    category_id BIGINT NULL,
    CONSTRAINT uk_promo_product UNIQUE (promotion_id, product_id, category_id),
    CONSTRAINT fk_pp_promo FOREIGN KEY (promotion_id) REFERENCES promotions(id) ON DELETE CASCADE,
    CONSTRAINT fk_pp_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
    CONSTRAINT fk_pp_category FOREIGN KEY (category_id) REFERENCES product_categories(id) ON DELETE CASCADE
);

-- 促销使用记录
CREATE TABLE promotion_usages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    promotion_id BIGINT CHECK (promotion_id >= 0) NOT NULL,
    order_id BIGINT CHECK (order_id >= 0) NOT NULL,
    customer_id BIGINT CHECK (customer_id >= 0) NOT NULL,
    discount_applied DECIMAL(12,2) NOT NULL,
    used_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_promo_order UNIQUE (promotion_id, order_id),
    CONSTRAINT fk_pu_promo FOREIGN KEY (promotion_id) REFERENCES promotions(id),
    CONSTRAINT fk_pu_order FOREIGN KEY (order_id) REFERENCES sales_orders(id) ON DELETE CASCADE,
    CONSTRAINT fk_pu_customer FOREIGN KEY (customer_id) REFERENCES customers(id)
);

CREATE INDEX idx_promotion_usages_customer ON promotion_usages (customer_id);

-- ============================================================
-- 4. 发票与三单匹配模块
-- 三单匹配: 采购单(PO) vs 入库单(Receipt) vs 发票(Invoice)
-- 匹配条件: 数量、单价、金额一致才可付款
-- ============================================================

CREATE TABLE invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_no VARCHAR(50) NOT NULL UNIQUE,
    invoice_type invoice_type_type NOT NULL,
    supplier_id BIGINT NULL,
    customer_id BIGINT NULL,
    invoice_date DATE NOT NULL,
    due_date DATE NULL,
    total_amount DECIMAL(18,2) NOT NULL,
    tax_amount DECIMAL(18,2) DEFAULT 0.00,
    tax_rate DECIMAL(5,4) DEFAULT 0.13,
    status invoice_status_type DEFAULT 'draft',
    verified_by BIGINT NULL,
    verified_at TIMESTAMP(0) NULL,
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_inv_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE SET NULL,
    CONSTRAINT fk_inv_customer FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE SET NULL
);

CREATE INDEX idx_invoices_supplier ON invoices (supplier_id);
CREATE INDEX idx_invoices_customer ON invoices (customer_id);
CREATE INDEX idx_invoices_date ON invoices (invoice_date);
CREATE INDEX idx_invoices_status ON invoices (status);

CREATE TRIGGER trg_invoices_updated_at
    BEFORE UPDATE ON invoices
    FOR EACH ROW
    EXECUTE FUNCTION update_timestamp();

-- 三单匹配明细
CREATE TABLE three_way_matching (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id BIGINT CHECK (invoice_id >= 0) NOT NULL,
    purchase_order_id BIGINT CHECK (purchase_order_id >= 0) NOT NULL,
    purchase_receipt_id BIGINT CHECK (purchase_receipt_id >= 0) NOT NULL,
    product_id BIGINT CHECK (product_id >= 0) NOT NULL,
    po_quantity INTEGER NOT NULL,
    receipt_quantity INTEGER NOT NULL,
    invoice_quantity INTEGER NOT NULL,
    po_price DECIMAL(12,2) NOT NULL,
    receipt_price DECIMAL(12,2) NOT NULL,
    invoice_price DECIMAL(12,2) NOT NULL,
    quantity_match BOOLEAN GENERATED ALWAYS AS (po_quantity = receipt_quantity AND receipt_quantity = invoice_quantity) STORED,
    price_match BOOLEAN GENERATED ALWAYS AS (po_price = receipt_price AND receipt_price = invoice_price) STORED,
    match_status match_status_type DEFAULT 'pending',
    match_result VARCHAR(500) NULL,
    matched_by BIGINT NULL,
    matched_at TIMESTAMP(0) NULL,
    CONSTRAINT fk_twm_invoice FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE CASCADE,
    CONSTRAINT fk_twm_po FOREIGN KEY (purchase_order_id) REFERENCES purchase_orders(id),
    CONSTRAINT fk_twm_receipt FOREIGN KEY (purchase_receipt_id) REFERENCES purchase_receipts(id),
    CONSTRAINT fk_twm_product FOREIGN KEY (product_id) REFERENCES products(id)
);

CREATE INDEX idx_three_way_matching_invoice ON three_way_matching (invoice_id);
CREATE INDEX idx_three_way_matching_po ON three_way_matching (purchase_order_id);
CREATE INDEX idx_three_way_matching_receipt ON three_way_matching (purchase_receipt_id);

-- ============================================================
-- 5. 固定资产模块
-- 折旧方法: 直线法(straight_line)
-- 折旧公式: 月折旧额 = (原值 - 残值) / 使用月数
-- 净值 = 原值 - 累计折旧
-- ============================================================

CREATE TABLE fixed_assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_no VARCHAR(30) NOT NULL UNIQUE,
    name VARCHAR(200) NOT NULL,
    category asset_category_type NOT NULL,
    purchase_date DATE NOT NULL,
    purchase_amount DECIMAL(18,2) NOT NULL,
    salvage_value DECIMAL(18,2) DEFAULT 0.00,
    useful_life_months INTEGER NOT NULL,
    monthly_depreciation DECIMAL(12,2) GENERATED ALWAYS AS (
        ROUND((purchase_amount - salvage_value) / useful_life_months, 2)
    ) STORED,
    accumulated_depreciation DECIMAL(18,2) DEFAULT 0.00,
    net_book_value DECIMAL(18,2) GENERATED ALWAYS AS (
        purchase_amount - accumulated_depreciation
    ) STORED,
    department_id BIGINT CHECK (department_id >= 0) NOT NULL,
    custodian_id BIGINT NULL,
    location VARCHAR(200) NULL,
    status asset_status_type DEFAULT 'in_use',
    last_depreciation_date DATE NULL,
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_fa_dept FOREIGN KEY (department_id) REFERENCES departments(id),
    CONSTRAINT fk_fa_custodian FOREIGN KEY (custodian_id) REFERENCES employees(id) ON DELETE SET NULL
);

CREATE INDEX idx_fixed_assets_dept ON fixed_assets (department_id);
CREATE INDEX idx_fixed_assets_category ON fixed_assets (category);
CREATE INDEX idx_fixed_assets_status ON fixed_assets (status);

CREATE TRIGGER trg_fixed_assets_updated_at
    BEFORE UPDATE ON fixed_assets
    FOR EACH ROW
    EXECUTE FUNCTION update_timestamp();

CREATE TABLE depreciation_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id BIGINT CHECK (asset_id >= 0) NOT NULL,
    depreciation_date DATE NOT NULL,
    depreciation_amount DECIMAL(12,2) NOT NULL,
    before_accumulated DECIMAL(18,2) NOT NULL,
    after_accumulated DECIMAL(18,2) NOT NULL,
    before_net_value DECIMAL(18,2) NOT NULL,
    after_net_value DECIMAL(18,2) NOT NULL,
    voucher_id BIGINT NULL,
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_asset_date UNIQUE (asset_id, depreciation_date),
    CONSTRAINT fk_dl_asset FOREIGN KEY (asset_id) REFERENCES fixed_assets(id) ON DELETE CASCADE
);

CREATE INDEX idx_depreciation_log_date ON depreciation_log (depreciation_date);

-- ============================================================
-- 6. BOM与生产工单模块
-- BOM: 物料清单，定义产品组成关系
-- 自引用: parent_product_id -> products.id (成品), child_product_id -> products.id (原料/半成品)
-- ============================================================

CREATE TABLE boms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_product_id BIGINT CHECK (parent_product_id >= 0) NOT NULL,
    child_product_id BIGINT CHECK (child_product_id >= 0) NOT NULL,
    quantity DECIMAL(10,3) NOT NULL,
    unit VARCHAR(20) NOT NULL,
    scrap_rate DECIMAL(5,4) DEFAULT 0.00,
    sort_order INTEGER DEFAULT 0,
    effective_date DATE NOT NULL,
    expiry_date DATE NULL,
    status bom_status_type DEFAULT 'active',
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_parent_child UNIQUE (parent_product_id, child_product_id, effective_date),
    CONSTRAINT fk_bom_parent FOREIGN KEY (parent_product_id) REFERENCES products(id) ON DELETE CASCADE,
    CONSTRAINT fk_bom_child FOREIGN KEY (child_product_id) REFERENCES products(id) ON DELETE CASCADE
);

CREATE INDEX idx_boms_child ON boms (child_product_id);
CREATE INDEX idx_boms_status ON boms (status);

CREATE TABLE work_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no VARCHAR(30) NOT NULL UNIQUE,
    product_id BIGINT CHECK (product_id >= 0) NOT NULL,
    bom_id BIGINT NULL,
    planned_quantity INTEGER NOT NULL,
    completed_quantity INTEGER DEFAULT 0,
    rejected_quantity INTEGER DEFAULT 0,
    warehouse_id BIGINT CHECK (warehouse_id >= 0) NOT NULL,
    start_date DATE NULL,
    due_date DATE NULL,
    completed_date DATE NULL,
    status work_order_status_type DEFAULT 'draft',
    priority priority_type DEFAULT 'normal',
    released_by BIGINT NULL,
    remark VARCHAR(500) NULL,
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_wo_product FOREIGN KEY (product_id) REFERENCES products(id),
    CONSTRAINT fk_wo_bom FOREIGN KEY (bom_id) REFERENCES boms(id) ON DELETE SET NULL,
    CONSTRAINT fk_wo_wh FOREIGN KEY (warehouse_id) REFERENCES warehouses(id)
);

CREATE INDEX idx_work_orders_product ON work_orders (product_id);
CREATE INDEX idx_work_orders_status ON work_orders (status);
CREATE INDEX idx_work_orders_due_date ON work_orders (due_date);
CREATE INDEX idx_work_orders_priority ON work_orders (priority);

CREATE TRIGGER trg_work_orders_updated_at
    BEFORE UPDATE ON work_orders
    FOR EACH ROW
    EXECUTE FUNCTION update_timestamp();

-- 工单用料明细
CREATE TABLE work_order_materials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_order_id BIGINT CHECK (work_order_id >= 0) NOT NULL,
    product_id BIGINT CHECK (product_id >= 0) NOT NULL,
    batch_id BIGINT NULL,
    required_qty DECIMAL(10,3) NOT NULL,
    issued_qty DECIMAL(10,3) DEFAULT 0,
    returned_qty DECIMAL(10,3) DEFAULT 0,
    actual_consumed DECIMAL(10,3) DEFAULT 0,
    unit VARCHAR(20) NOT NULL,
    status wom_status_type DEFAULT 'pending',
    CONSTRAINT fk_wom_wo FOREIGN KEY (work_order_id) REFERENCES work_orders(id) ON DELETE CASCADE,
    CONSTRAINT fk_wom_product FOREIGN KEY (product_id) REFERENCES products(id)
);

CREATE INDEX idx_work_order_materials_wo ON work_order_materials (work_order_id);
CREATE INDEX idx_work_order_materials_product ON work_order_materials (product_id);

-- ============================================================
-- 7. 客服工单模块
-- ============================================================

CREATE TABLE service_tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_no VARCHAR(30) NOT NULL UNIQUE,
    customer_id BIGINT CHECK (customer_id >= 0) NOT NULL,
    order_id BIGINT NULL,
    product_id BIGINT NULL,
    ticket_type ticket_type_type NOT NULL,
    priority priority_type DEFAULT 'normal',
    subject VARCHAR(200) NOT NULL,
    description TEXT NULL,
    status ticket_status_type DEFAULT 'open',
    assigned_to BIGINT NULL,
    resolution VARCHAR(500) NULL,
    resolved_at TIMESTAMP(0) NULL,
    satisfaction_score SMALLINT NULL,
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_st_customer FOREIGN KEY (customer_id) REFERENCES customers(id),
    CONSTRAINT fk_st_order FOREIGN KEY (order_id) REFERENCES sales_orders(id) ON DELETE SET NULL,
    CONSTRAINT fk_st_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL,
    CONSTRAINT fk_st_assigned FOREIGN KEY (assigned_to) REFERENCES employees(id) ON DELETE SET NULL
);

CREATE INDEX idx_service_tickets_customer ON service_tickets (customer_id);
CREATE INDEX idx_service_tickets_order ON service_tickets (order_id);
CREATE INDEX idx_service_tickets_status ON service_tickets (status);
CREATE INDEX idx_service_tickets_priority ON service_tickets (priority);
CREATE INDEX idx_service_tickets_assigned ON service_tickets (assigned_to);

CREATE TRIGGER trg_service_tickets_updated_at
    BEFORE UPDATE ON service_tickets
    FOR EACH ROW
    EXECUTE FUNCTION update_timestamp();