-- ============================================================
-- Oracle 12c 语法样例
-- 说明: 覆盖 12c 合法的 identity、row limiting、Oracle PL/SQL 和基础 DML。
-- ============================================================

CREATE TABLE oracle_12c_identity_demo (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku VARCHAR2(50) NOT NULL,
    sales_amount NUMBER(18,2) NOT NULL,
    cost_amount NUMBER(18,2) NOT NULL,
    gross_margin NUMBER(18,2) GENERATED ALWAYS AS (sales_amount - cost_amount) VIRTUAL
);

INSERT INTO oracle_12c_identity_demo (sku, sales_amount, cost_amount) VALUES ('ORA12-DEMO-001', 1200.00, 830.00);
INSERT INTO oracle_12c_identity_demo (sku, sales_amount, cost_amount) VALUES ('ORA12-DEMO-002', 980.00, 760.00);

SELECT sku, sales_amount, cost_amount, gross_margin
FROM oracle_12c_identity_demo
ORDER BY sales_amount DESC
FETCH FIRST 1 ROWS ONLY;

CREATE OR REPLACE PROCEDURE oracle_12c_raise_margin (p_sku IN VARCHAR2) AS
BEGIN
    UPDATE oracle_12c_identity_demo
    SET sales_amount = sales_amount * 1.05
    WHERE sku = p_sku;
END;
/
