-- ============================================================
-- ERP系统第三批补充表: 合同管理、AR/AP账龄、税务管理、
--   质检、审批流引擎、现金流预测、项目成本、多币种汇率、
--   绩效考核、序列号追踪、寄售库存、价格变更历史
-- 关系说明:
--   contracts -> sales_orders/purchase_orders (1:1), 管理合同条款和里程碑
--   ar_aging / ap_aging: 账龄分析用，按月计算应收账款/应付账款
--   tax_invoices: 增值税发票管理，进项税/销项税
--   inspection_reports: 质检报告，关联采购入库和销售退货
--   approval_workflows: 通用审批流引擎，支持多级审批
--   cash_flow_forecasts: 现金流预测，基于应收应付和计划收支
--   projects + project_costs: 项目成本核算
--   exchange_rates: 多币种汇率管理
--   performance_reviews: 绩效考核
--   serial_numbers: 序列号追踪
--   consignment_inventory: 寄售库存
--   price_change_logs: 价格变更历史
-- ============================================================

-- ============================================================
-- Custom ENUM types
-- ============================================================

-- 合同类型
-- 里程碑类型
-- 税务发票类型
-- 税务申报类型
-- 质检类型
-- 审批流类型
-- 现金流预测类型
-- 项目类型
-- 项目成本类型
-- 绩效考核类型
-- KPI类型
-- 序列号类型
-- 寄售类型
-- 价格变更类型
-- ============================================================
-- 1. 合同管理模块
-- 合同类型: 销售合同、采购合同、服务合同
-- 合同状态流转: draft -> pending_approval -> active -> in_progress -> completed -> expired -> terminated
-- ============================================================

CREATE TABLE contracts (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_no VARCHAR2(30) NOT NULL UNIQUE,
    contract_type VARCHAR2(40) NOT NULL,
    party_type VARCHAR2(40) NOT NULL,
    party_id NUMBER(19) NOT NULL,
    subject VARCHAR2(300) NOT NULL,
    total_amount NUMBER(18,2) NOT NULL,
    currency VARCHAR2(3) DEFAULT 'CNY',
    signed_date DATE NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    payment_terms CLOB NULL,
    delivery_terms CLOB NULL,
    status VARCHAR2(40) DEFAULT 'draft',
    prepared_by NUMBER(19) CHECK (prepared_by >= 0) NOT NULL,
    approved_by NUMBER(19) NULL,
    signed_by VARCHAR2(100) NULL,
    attachment_path VARCHAR2(500) NULL,
    remark CLOB NULL,
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ct_prepared FOREIGN KEY (prepared_by) REFERENCES employees(id),
    CONSTRAINT fk_ct_approved FOREIGN KEY (approved_by) REFERENCES employees(id)
);

CREATE INDEX idx_contracts_party ON contracts (party_type, party_id);
CREATE INDEX idx_contracts_status ON contracts (status);
CREATE INDEX idx_contracts_date_range ON contracts (start_date, end_date);
CREATE INDEX idx_contracts_type ON contracts (contract_type);

CREATE OR REPLACE TRIGGER trg_contracts_updated_at
    BEFORE UPDATE ON contracts
    FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- 合同里程碑/付款计划
CREATE TABLE contract_milestones (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id NUMBER(19) CHECK (contract_id >= 0) NOT NULL,
    milestone_name VARCHAR2(200) NOT NULL,
    milestone_type VARCHAR2(40) NOT NULL,
    planned_date DATE NOT NULL,
    actual_date DATE NULL,
    amount NUMBER(18,2) DEFAULT 0.00,
    completion_pct NUMBER(5,2) DEFAULT 0.00,
    status VARCHAR2(40) DEFAULT 'pending',
    responsible_person NUMBER(19) NULL,
    remark VARCHAR2(500) NULL,
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_cm_contract FOREIGN KEY (contract_id) REFERENCES contracts(id) ON DELETE CASCADE
);

CREATE INDEX idx_contract_milestones_contract ON contract_milestones (contract_id);
CREATE INDEX idx_contract_milestones_planned_date ON contract_milestones (planned_date);
CREATE INDEX idx_contract_milestones_status ON contract_milestones (status);

-- ============================================================
-- 2. 应收账款账龄 (AR Aging)
-- 计算原理: 按账期分桶: 0-30天, 31-60天, 61-90天, 91-180天, 181-365天, >365天
-- 坏账准备: >365天按50%计提, >180天按20%, >90天按5%
-- ============================================================

CREATE TABLE ar_aging_snapshots (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_date DATE NOT NULL,
    customer_id NUMBER(19) CHECK (customer_id >= 0) NOT NULL,
    order_id NUMBER(19) CHECK (order_id >= 0) NOT NULL,
    invoice_amount NUMBER(18,2) NOT NULL,
    paid_amount NUMBER(18,2) DEFAULT 0.00,
    outstanding_amount NUMBER(18,2) GENERATED ALWAYS AS (invoice_amount - paid_amount) STORED,
    due_date DATE NOT NULL,
    aging_days NUMBER(10) GENERATED ALWAYS AS (snapshot_date - due_date) STORED,
    aging_bucket VARCHAR2(20) GENERATED ALWAYS AS (
        CASE
            WHEN snapshot_date - due_date <= 0 THEN '未到期'
            WHEN snapshot_date - due_date <= 30 THEN '1-30天'
            WHEN snapshot_date - due_date <= 60 THEN '31-60天'
            WHEN snapshot_date - due_date <= 90 THEN '61-90天'
            WHEN snapshot_date - due_date <= 180 THEN '91-180天'
            WHEN snapshot_date - due_date <= 365 THEN '181-365天'
            ELSE '365天以上'
        END
    ) STORED,
    bad_debt_provision NUMBER(18,2) GENERATED ALWAYS AS (
        ROUND((invoice_amount - paid_amount) *
        CASE
            WHEN snapshot_date - due_date <= 90 THEN 0.00
            WHEN snapshot_date - due_date <= 180 THEN 0.05
            WHEN snapshot_date - due_date <= 365 THEN 0.20
            ELSE 0.50
        END, 2)
    ) STORED,
    last_collection_date DATE NULL,
    collection_notes VARCHAR2(500) NULL,
    CONSTRAINT fk_ar_customer FOREIGN KEY (customer_id) REFERENCES customers(id),
    CONSTRAINT fk_ar_order FOREIGN KEY (order_id) REFERENCES sales_orders(id)
);

CREATE INDEX idx_ar_aging_customer ON ar_aging_snapshots (customer_id);
CREATE INDEX idx_ar_aging_bucket ON ar_aging_snapshots (aging_bucket);
CREATE INDEX idx_ar_aging_snapshot_date ON ar_aging_snapshots (snapshot_date);
CREATE INDEX idx_ar_aging_due_date ON ar_aging_snapshots (due_date);

-- 应付账款账龄 (AP Aging)
CREATE TABLE ap_aging_snapshots (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_date DATE NOT NULL,
    supplier_id NUMBER(19) CHECK (supplier_id >= 0) NOT NULL,
    order_id NUMBER(19) CHECK (order_id >= 0) NOT NULL,
    invoice_amount NUMBER(18,2) NOT NULL,
    paid_amount NUMBER(18,2) DEFAULT 0.00,
    outstanding_amount NUMBER(18,2) GENERATED ALWAYS AS (invoice_amount - paid_amount) STORED,
    due_date DATE NOT NULL,
    aging_bucket VARCHAR2(20) GENERATED ALWAYS AS (
        CASE
            WHEN snapshot_date - due_date <= 0 THEN '未到期'
            WHEN snapshot_date - due_date <= 30 THEN '1-30天'
            WHEN snapshot_date - due_date <= 60 THEN '31-60天'
            WHEN snapshot_date - due_date <= 90 THEN '61-90天'
            WHEN snapshot_date - due_date <= 180 THEN '91-180天'
            WHEN snapshot_date - due_date <= 365 THEN '181-365天'
            ELSE '365天以上'
        END
    ) STORED,
    planned_payment_date DATE NULL,
    CONSTRAINT fk_ap_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers(id),
    CONSTRAINT fk_ap_order FOREIGN KEY (order_id) REFERENCES purchase_orders(id)
);

CREATE INDEX idx_ap_aging_supplier ON ap_aging_snapshots (supplier_id);
CREATE INDEX idx_ap_aging_bucket ON ap_aging_snapshots (aging_bucket);
CREATE INDEX idx_ap_aging_due_date ON ap_aging_snapshots (due_date);

-- ============================================================
-- 3. 税务管理模块 (增值税)
-- 税率: 13%(一般货物), 9%(农产品/图书), 6%(服务), 0%(出口)
-- 进项税 = 采购发票税额, 销项税 = 销售发票税额
-- 应交增值税 = 销项税 - 进项税
-- ============================================================

CREATE TABLE tax_invoices (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_no VARCHAR2(50) NOT NULL UNIQUE,
    invoice_code VARCHAR2(50) NULL,
    invoice_type VARCHAR2(40) NOT NULL,
    tax_direction VARCHAR2(40) NOT NULL,
    party_type VARCHAR2(40) NOT NULL,
    party_id NUMBER(19) NOT NULL,
    invoice_date DATE NOT NULL,
    amount_excluding_tax NUMBER(18,2) NOT NULL,
    tax_rate NUMBER(5,4) NOT NULL,
    tax_amount NUMBER(18,2) GENERATED ALWAYS AS (ROUND(amount_excluding_tax * tax_rate, 2)) STORED,
    amount_including_tax NUMBER(18,2) GENERATED ALWAYS AS (amount_excluding_tax + ROUND(amount_excluding_tax * tax_rate, 2)) STORED,
    verification_status VARCHAR2(40) DEFAULT 'pending',
    verified_at TIMESTAMP(0) NULL,
    verified_by NUMBER(19) NULL,
    tax_period VARCHAR2(7) NOT NULL,
    deduction_period VARCHAR2(7) NULL,
    reference_type VARCHAR2(50) NULL,
    reference_id NUMBER(19) NULL,
    status VARCHAR2(40) DEFAULT 'draft',
    remark VARCHAR2(500) NULL,
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ti_verified FOREIGN KEY (verified_by) REFERENCES employees(id)
);

CREATE INDEX idx_tax_invoices_party ON tax_invoices (party_type, party_id);
CREATE INDEX idx_tax_invoices_tax_period ON tax_invoices (tax_period);
CREATE INDEX idx_tax_invoices_direction ON tax_invoices (tax_direction);
CREATE INDEX idx_tax_invoices_status ON tax_invoices (status);
CREATE INDEX idx_tax_invoices_invoice_date ON tax_invoices (invoice_date);

CREATE OR REPLACE TRIGGER trg_tax_invoices_updated_at
    BEFORE UPDATE ON tax_invoices
    FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- 税务申报记录
CREATE TABLE tax_filings (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tax_period VARCHAR2(7) NOT NULL,
    tax_type VARCHAR2(40) NOT NULL,
    output_tax NUMBER(18,2) DEFAULT 0.00,
    input_tax NUMBER(18,2) DEFAULT 0.00,
    input_tax_transfer NUMBER(18,2) DEFAULT 0.00,
    tax_payable NUMBER(18,2) DEFAULT 0.00,
    tax_paid NUMBER(18,2) DEFAULT 0.00,
    filing_date DATE NULL,
    filing_deadline DATE NOT NULL,
    status VARCHAR2(40) DEFAULT 'draft',
    prepared_by NUMBER(19) NULL,
    voucher_id NUMBER(19) NULL,
    remark VARCHAR2(500) NULL,
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (tax_period, tax_type),
    CONSTRAINT fk_tf_prepared FOREIGN KEY (prepared_by) REFERENCES employees(id)
);

CREATE INDEX idx_tax_filings_status ON tax_filings (status);
CREATE INDEX idx_tax_filings_deadline ON tax_filings (filing_deadline);

CREATE OR REPLACE TRIGGER trg_tax_filings_updated_at
    BEFORE UPDATE ON tax_filings
    FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- ============================================================
-- 4. 质量检验模块
-- 检验类型: 来料检验(IQC), 过程检验(IPQC), 出货检验(OQC), 退货检验
-- 检验结果: 合格/不合格/让步接收/退货
-- ============================================================

CREATE TABLE inspection_standards (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id NUMBER(19) CHECK (product_id >= 0) NOT NULL,
    standard_name VARCHAR2(200) NOT NULL,
    inspection_items CLOB NULL,
    sampling_method VARCHAR2(40) DEFAULT 'gb2828',
    sample_size NUMBER(10) DEFAULT 0,
    aql_level NUMBER(5,2) DEFAULT 1.0,
    status VARCHAR2(40) DEFAULT 'active',
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_inspection_standards_product UNIQUE (product_id, standard_name),
    CONSTRAINT fk_is_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);

CREATE TABLE inspection_reports (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_no VARCHAR2(30) NOT NULL UNIQUE,
    inspection_type VARCHAR2(40) NOT NULL,
    reference_type VARCHAR2(50) NOT NULL,
    reference_id NUMBER(19) NOT NULL,
    product_id NUMBER(19) CHECK (product_id >= 0) NOT NULL,
    batch_id NUMBER(19) NULL,
    standard_id NUMBER(19) NULL,
    sample_size NUMBER(10) NOT NULL,
    inspected_qty NUMBER(10) NOT NULL,
    qualified_qty NUMBER(10) DEFAULT 0,
    defective_qty NUMBER(10) DEFAULT 0,
    defect_rate NUMBER(5,2) GENERATED ALWAYS AS (
        ROUND(defective_qty * 100.0 / NULLIF(inspected_qty, 0), 2)
    ) STORED,
    inspection_result VARCHAR2(40) NOT NULL,
    inspector_id NUMBER(19) CHECK (inspector_id >= 0) NOT NULL,
    inspection_date DATE NOT NULL,
    defect_description CLOB NULL,
    disposition VARCHAR2(200) NULL,
    status VARCHAR2(40) DEFAULT 'draft',
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ir_product FOREIGN KEY (product_id) REFERENCES products(id),
    CONSTRAINT fk_ir_batch FOREIGN KEY (batch_id) REFERENCES product_batches(id) ON DELETE SET NULL,
    CONSTRAINT fk_ir_standard FOREIGN KEY (standard_id) REFERENCES inspection_standards(id) ON DELETE SET NULL,
    CONSTRAINT fk_ir_inspector FOREIGN KEY (inspector_id) REFERENCES employees(id)
);

CREATE INDEX idx_inspection_reports_product ON inspection_reports (product_id);
CREATE INDEX idx_inspection_reports_batch ON inspection_reports (batch_id);
CREATE INDEX idx_inspection_reports_reference ON inspection_reports (reference_type, reference_id);
CREATE INDEX idx_inspection_reports_result ON inspection_reports (inspection_result);
CREATE INDEX idx_inspection_reports_date ON inspection_reports (inspection_date);

CREATE OR REPLACE TRIGGER trg_inspection_reports_updated_at
    BEFORE UPDATE ON inspection_reports
    FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- ============================================================
-- 5. 通用审批流引擎
-- 支持多级审批: 部门经理 -> 总监 -> 总经理
-- 审批节点可配置，支持会签/或签
-- ============================================================

CREATE TABLE approval_workflows (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_name VARCHAR2(100) NOT NULL,
    workflow_code VARCHAR2(30) NOT NULL UNIQUE,
    target_type VARCHAR2(50) NOT NULL,
    description VARCHAR2(500) NULL,
    is_active NUMBER(1) DEFAULT 1,
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE approval_nodes (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_id NUMBER(19) CHECK (workflow_id >= 0) NOT NULL,
    node_name VARCHAR2(100) NOT NULL,
    node_level NUMBER(10) NOT NULL,
    approver_type VARCHAR2(40) NOT NULL,
    approver_id NUMBER(19) NULL,
    approval_mode VARCHAR2(40) DEFAULT 'single',
    timeout_hours NUMBER(10) DEFAULT 48,
    can_delegate NUMBER(1) DEFAULT 1,
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_approval_nodes_workflow_level UNIQUE (workflow_id, node_level),
    CONSTRAINT fk_an_workflow FOREIGN KEY (workflow_id) REFERENCES approval_workflows(id) ON DELETE CASCADE
);

CREATE TABLE approval_instances (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instance_no VARCHAR2(30) NOT NULL UNIQUE,
    workflow_id NUMBER(19) CHECK (workflow_id >= 0) NOT NULL,
    target_type VARCHAR2(50) NOT NULL,
    target_id NUMBER(19) NOT NULL,
    target_summary VARCHAR2(500) NULL,
    current_node_level NUMBER(10) DEFAULT 1,
    total_nodes NUMBER(10) DEFAULT 1,
    submitted_by NUMBER(19) CHECK (submitted_by >= 0) NOT NULL,
    submitted_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR2(40) DEFAULT 'pending',
    completed_at TIMESTAMP(0) NULL,
    remark VARCHAR2(500) NULL,
    CONSTRAINT fk_ai_workflow FOREIGN KEY (workflow_id) REFERENCES approval_workflows(id),
    CONSTRAINT fk_ai_submitted FOREIGN KEY (submitted_by) REFERENCES employees(id)
);

CREATE INDEX idx_approval_instances_target ON approval_instances (target_type, target_id);
CREATE INDEX idx_approval_instances_status ON approval_instances (status);
CREATE INDEX idx_approval_instances_submitted ON approval_instances (submitted_by, submitted_at);

CREATE TABLE approval_records (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instance_id NUMBER(19) CHECK (instance_id >= 0) NOT NULL,
    node_id NUMBER(19) CHECK (node_id >= 0) NOT NULL,
    approver_id NUMBER(19) CHECK (approver_id >= 0) NOT NULL,
    action VARCHAR2(40) NOT NULL,
    comment VARCHAR2(500) NULL,
    action_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    delegated_to NUMBER(19) NULL,
    CONSTRAINT fk_ar_instance FOREIGN KEY (instance_id) REFERENCES approval_instances(id) ON DELETE CASCADE,
    CONSTRAINT fk_ar_node FOREIGN KEY (node_id) REFERENCES approval_nodes(id),
    CONSTRAINT fk_ar_approver FOREIGN KEY (approver_id) REFERENCES employees(id)
);

CREATE INDEX idx_approval_records_instance ON approval_records (instance_id);

-- ============================================================
-- 6. 现金流预测
-- 预测来源: 应收款到期日 + 应付款到期日 + 工资发放计划 + 计划收支
-- 按日/周/月汇总预测净现金流
-- ============================================================

CREATE TABLE cash_flow_forecasts (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    forecast_date DATE NOT NULL,
    forecast_type VARCHAR2(40) NOT NULL,
    beginning_balance NUMBER(18,2) DEFAULT 0.00,
    expected_collections NUMBER(18,2) DEFAULT 0.00,
    expected_payments NUMBER(18,2) DEFAULT 0.00,
    expected_salary NUMBER(18,2) DEFAULT 0.00,
    expected_tax NUMBER(18,2) DEFAULT 0.00,
    other_income NUMBER(18,2) DEFAULT 0.00,
    other_expense NUMBER(18,2) DEFAULT 0.00,
    net_cash_flow NUMBER(18,2) GENERATED ALWAYS AS (
        expected_collections - expected_payments - expected_salary - expected_tax + other_income - other_expense
    ) STORED,
    ending_balance NUMBER(18,2) GENERATED ALWAYS AS (
        beginning_balance + expected_collections - expected_payments - expected_salary - expected_tax + other_income - other_expense
    ) STORED,
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (forecast_date, forecast_type)
);

CREATE INDEX idx_cash_flow_forecasts_date ON cash_flow_forecasts (forecast_date);

-- ============================================================
-- 7. 项目成本核算
-- 项目类型: 工程项目、研发项目、营销活动等
-- 成本归集: 人工成本+材料成本+费用+外包
-- ============================================================

CREATE TABLE projects (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_no VARCHAR2(30) NOT NULL UNIQUE,
    name VARCHAR2(200) NOT NULL,
    project_type VARCHAR2(40) NOT NULL,
    department_id NUMBER(19) CHECK (department_id >= 0) NOT NULL,
    manager_id NUMBER(19) CHECK (manager_id >= 0) NOT NULL,
    budget NUMBER(18,2) NOT NULL,
    start_date DATE NOT NULL,
    planned_end_date DATE NOT NULL,
    actual_end_date DATE NULL,
    status VARCHAR2(40) DEFAULT 'planning',
    priority VARCHAR2(40) DEFAULT 'normal',
    description CLOB NULL,
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_proj_dept FOREIGN KEY (department_id) REFERENCES departments(id),
    CONSTRAINT fk_proj_manager FOREIGN KEY (manager_id) REFERENCES employees(id)
);

CREATE INDEX idx_projects_dept ON projects (department_id);
CREATE INDEX idx_projects_manager ON projects (manager_id);
CREATE INDEX idx_projects_status ON projects (status);

CREATE OR REPLACE TRIGGER trg_projects_updated_at
    BEFORE UPDATE ON projects
    FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

CREATE TABLE project_costs (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id NUMBER(19) CHECK (project_id >= 0) NOT NULL,
    cost_type VARCHAR2(40) NOT NULL,
    cost_date DATE NOT NULL,
    amount NUMBER(18,2) NOT NULL,
    description VARCHAR2(500) NULL,
    reference_type VARCHAR2(50) NULL,
    reference_id NUMBER(19) NULL,
    recorded_by NUMBER(19) NULL,
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_pc_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
);

CREATE INDEX idx_project_costs_project ON project_costs (project_id);
CREATE INDEX idx_project_costs_date ON project_costs (cost_date);
CREATE INDEX idx_project_costs_type ON project_costs (cost_type);

-- ============================================================
-- 8. 多币种与汇率管理
-- ============================================================

CREATE TABLE exchange_rates (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_currency VARCHAR2(3) NOT NULL,
    to_currency VARCHAR2(3) NOT NULL DEFAULT 'CNY',
    rate_date DATE NOT NULL,
    rate NUMBER(12,6) NOT NULL,
    rate_source VARCHAR2(50) DEFAULT 'BOC',
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_exchange_rates_currency_date UNIQUE (from_currency, to_currency, rate_date)
);

CREATE INDEX idx_exchange_rates_date ON exchange_rates (rate_date);

-- 外币账户
CREATE TABLE foreign_currency_accounts (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id NUMBER(19) CHECK (account_id >= 0) NOT NULL,
    currency VARCHAR2(3) NOT NULL,
    original_balance NUMBER(18,2) DEFAULT 0.00,
    cny_equivalent NUMBER(18,2) DEFAULT 0.00,
    last_revaluation_date DATE NULL,
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_foreign_currency_accounts_account_currency UNIQUE (account_id, currency),
    CONSTRAINT fk_fca_account FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE
);

-- ============================================================
-- 9. 绩效考核模块
-- 考核周期: 月度/季度/年度
-- 评分维度: 业绩(40%) + 能力(30%) + 态度(20%) + 出勤(10%)
-- ============================================================

CREATE TABLE performance_reviews (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_no VARCHAR2(30) NOT NULL UNIQUE,
    employee_id NUMBER(19) CHECK (employee_id >= 0) NOT NULL,
    reviewer_id NUMBER(19) CHECK (reviewer_id >= 0) NOT NULL,
    review_period VARCHAR2(7) NOT NULL,
    review_type VARCHAR2(40) NOT NULL,
    -- 评分维度
    performance_score NUMBER(5,2) DEFAULT 0.00,
    competency_score NUMBER(5,2) DEFAULT 0.00,
    attitude_score NUMBER(5,2) DEFAULT 0.00,
    attendance_score NUMBER(5,2) DEFAULT 0.00,
    -- 加权总分 (业绩40% + 能力30% + 态度20% + 出勤10%)
    total_score NUMBER(5,2) GENERATED ALWAYS AS (
        ROUND(performance_score * 0.40 + competency_score * 0.30 + attitude_score * 0.20 + attendance_score * 0.10, 2)
    ) STORED,
    grade CHAR(1) GENERATED ALWAYS AS (
        CASE
            WHEN ROUND(performance_score * 0.40 + competency_score * 0.30 + attitude_score * 0.20 + attendance_score * 0.10, 2) >= 90 THEN 'S'
            WHEN ROUND(performance_score * 0.40 + competency_score * 0.30 + attitude_score * 0.20 + attendance_score * 0.10, 2) >= 80 THEN 'A'
            WHEN ROUND(performance_score * 0.40 + competency_score * 0.30 + attitude_score * 0.20 + attendance_score * 0.10, 2) >= 70 THEN 'B'
            WHEN ROUND(performance_score * 0.40 + competency_score * 0.30 + attitude_score * 0.20 + attendance_score * 0.10, 2) >= 60 THEN 'C'
            ELSE 'D'
        END
    ) STORED,
    self_assessment CLOB NULL,
    reviewer_comment CLOB NULL,
    improvement_plan CLOB NULL,
    salary_adjustment NUMBER(12,2) DEFAULT 0.00,
    promotion_recommendation NUMBER(1) DEFAULT 0,
    status VARCHAR2(40) DEFAULT 'draft',
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (employee_id, review_period, review_type),
    CONSTRAINT fk_pr_employee FOREIGN KEY (employee_id) REFERENCES employees(id),
    CONSTRAINT fk_pr_reviewer FOREIGN KEY (reviewer_id) REFERENCES employees(id)
);

CREATE INDEX idx_performance_reviews_reviewer ON performance_reviews (reviewer_id);
CREATE INDEX idx_performance_reviews_grade ON performance_reviews (grade);
CREATE INDEX idx_performance_reviews_period ON performance_reviews (review_period);

CREATE OR REPLACE TRIGGER trg_performance_reviews_updated_at
    BEFORE UPDATE ON performance_reviews
    FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- KPI指标定义
CREATE TABLE kpi_indicators (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(200) NOT NULL,
    indicator_type VARCHAR2(40) NOT NULL,
    unit VARCHAR2(20) NOT NULL,
    target_direction VARCHAR2(40) NOT NULL,
    target_value NUMBER(12,2) NOT NULL,
    target_min NUMBER(12,2) NULL,
    target_max NUMBER(12,2) NULL,
    weight NUMBER(5,4) DEFAULT 1.0,
    applicable_role_id NUMBER(19) NULL,
    department_id NUMBER(19) NULL,
    status VARCHAR2(40) DEFAULT 'active',
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_kpi_indicators_role ON kpi_indicators (applicable_role_id);
CREATE INDEX idx_kpi_indicators_dept ON kpi_indicators (department_id);

-- ============================================================
-- 10. 序列号追踪 (单品追踪)
-- 用于高价值商品(电子产品/设备)的单品全生命周期追踪
-- 生命周期: 采购入库 -> 库存 -> 销售出库 -> 客户 -> 退货 -> 翻新 -> 重新入库
-- ============================================================

CREATE TABLE serial_numbers (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id NUMBER(19) CHECK (product_id >= 0) NOT NULL,
    batch_id NUMBER(19) NULL,
    serial_no VARCHAR2(100) NOT NULL,
    status VARCHAR2(40) DEFAULT 'in_stock',
    warehouse_id NUMBER(19) NULL,
    purchase_receipt_id NUMBER(19) NULL,
    sales_order_id NUMBER(19) NULL,
    return_id NUMBER(19) NULL,
    current_owner_id NUMBER(19) NULL,
    warranty_start DATE NULL,
    warranty_end DATE NULL,
    last_scan_date TIMESTAMP(0) NULL,
    last_scan_location VARCHAR2(200) NULL,
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_serial_numbers_product_serial UNIQUE (product_id, serial_no),
    CONSTRAINT fk_sn_product FOREIGN KEY (product_id) REFERENCES products(id),
    CONSTRAINT fk_sn_batch FOREIGN KEY (batch_id) REFERENCES product_batches(id) ON DELETE SET NULL,
    CONSTRAINT fk_sn_wh FOREIGN KEY (warehouse_id) REFERENCES warehouses(id) ON DELETE SET NULL
);

CREATE INDEX idx_serial_numbers_status ON serial_numbers (status);
CREATE INDEX idx_serial_numbers_batch ON serial_numbers (batch_id);
CREATE INDEX idx_serial_numbers_warehouse ON serial_numbers (warehouse_id);
CREATE INDEX idx_serial_numbers_warranty ON serial_numbers (warranty_end);

CREATE OR REPLACE TRIGGER trg_serial_numbers_updated_at
    BEFORE UPDATE ON serial_numbers
    FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- 序列号流转日志
CREATE TABLE serial_number_logs (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    serial_number_id NUMBER(19) CHECK (serial_number_id >= 0) NOT NULL,
    event_type VARCHAR2(40) NOT NULL,
    from_status VARCHAR2(20) NULL,
    to_status VARCHAR2(20) NOT NULL,
    from_location VARCHAR2(200) NULL,
    to_location VARCHAR2(200) NULL,
    reference_type VARCHAR2(50) NULL,
    reference_id NUMBER(19) NULL,
    operator_id NUMBER(19) NULL,
    event_time TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    remark VARCHAR2(500) NULL,
    CONSTRAINT fk_snl_sn FOREIGN KEY (serial_number_id) REFERENCES serial_numbers(id) ON DELETE CASCADE
);

CREATE INDEX idx_serial_number_logs_sn ON serial_number_logs (serial_number_id);
CREATE INDEX idx_serial_number_logs_event_time ON serial_number_logs (event_time);

-- ============================================================
-- 11. 寄售库存
-- 寄售: 货品存放在客户处，客户使用时才结算
-- 所有权仍属于我方，不确认收入
-- ============================================================

CREATE TABLE consignment_inventory (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id NUMBER(19) CHECK (product_id >= 0) NOT NULL,
    batch_id NUMBER(19) NULL,
    customer_id NUMBER(19) CHECK (customer_id >= 0) NOT NULL,
    consigned_qty NUMBER(10) NOT NULL,
    consumed_qty NUMBER(10) DEFAULT 0,
    available_qty NUMBER(10) GENERATED ALWAYS AS (consigned_qty - consumed_qty) STORED,
    unit_price NUMBER(12,2) NOT NULL,
    consigned_date DATE NOT NULL,
    last_consumed_date DATE NULL,
    settlement_period VARCHAR2(7) NULL,
    status VARCHAR2(40) DEFAULT 'active',
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_consignment_inventory_product_batch_customer UNIQUE (product_id, batch_id, customer_id),
    CONSTRAINT fk_ci_product FOREIGN KEY (product_id) REFERENCES products(id),
    CONSTRAINT fk_ci_batch FOREIGN KEY (batch_id) REFERENCES product_batches(id) ON DELETE SET NULL,
    CONSTRAINT fk_ci_customer FOREIGN KEY (customer_id) REFERENCES customers(id)
);

CREATE INDEX idx_consignment_inventory_customer ON consignment_inventory (customer_id);
CREATE INDEX idx_consignment_inventory_status ON consignment_inventory (status);

CREATE OR REPLACE TRIGGER trg_consignment_inventory_updated_at
    BEFORE UPDATE ON consignment_inventory
    FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- 寄售消耗记录
CREATE TABLE consignment_consumptions (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    consignment_id NUMBER(19) CHECK (consignment_id >= 0) NOT NULL,
    consumed_qty NUMBER(10) NOT NULL,
    consumed_date DATE NOT NULL,
    unit_price NUMBER(12,2) NOT NULL,
    amount NUMBER(18,2) GENERATED ALWAYS AS (consumed_qty * unit_price) STORED,
    confirmed_by_customer NUMBER(1) DEFAULT 0,
    sales_order_id NUMBER(19) NULL,
    remark VARCHAR2(200) NULL,
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_cc_consignment FOREIGN KEY (consignment_id) REFERENCES consignment_inventory(id) ON DELETE CASCADE
);

CREATE INDEX idx_consignment_consumptions_consignment ON consignment_consumptions (consignment_id);
CREATE INDEX idx_consignment_consumptions_date ON consignment_consumptions (consumed_date);

-- ============================================================
-- 12. 价格变更历史
-- 记录所有价格变更，用于价格分析和审计
-- ============================================================

CREATE TABLE price_change_logs (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id NUMBER(19) CHECK (product_id >= 0) NOT NULL,
    price_type VARCHAR2(40) NOT NULL,
    old_price NUMBER(12,2) NOT NULL,
    new_price NUMBER(12,2) NOT NULL,
    change_reason VARCHAR2(200) NOT NULL,
    effective_date DATE NOT NULL,
    changed_by NUMBER(19) CHECK (changed_by >= 0) NOT NULL,
    approved_by NUMBER(19) NULL,
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_pcl_product FOREIGN KEY (product_id) REFERENCES products(id),
    CONSTRAINT fk_pcl_changed FOREIGN KEY (changed_by) REFERENCES employees(id)
);

CREATE INDEX idx_price_change_logs_product ON price_change_logs (product_id);
CREATE INDEX idx_price_change_logs_effective_date ON price_change_logs (effective_date);
CREATE INDEX idx_price_change_logs_price_type ON price_change_logs (price_type);
