-- ============================================================
-- PostgreSQL 17 兼容语法样例
-- 说明:
--   这份文件由 PostgreSQL 18 专属语法样例降级而来。
--   目标是在 PostgreSQL 17 中保留等价业务含义，同时不使用高版本专属语法：
--   - virtual generated column -> stored generated column
--   - RETURNING old/new -> CTE 捕获更新前后值
--   - higher-version temporal constraints -> exclusion constraint + 普通 FK 兼容表达
--   可在 PostgreSQL 17 环境中单独执行。
-- ============================================================

CREATE EXTENSION IF NOT EXISTS btree_gist;

-- 1. Stored generated column, compatible with PostgreSQL 17
CREATE TABLE pg17_generated_margin_demo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku VARCHAR(50) NOT NULL,
    sales_amount NUMERIC(18,2) NOT NULL,
    cost_amount NUMERIC(18,2) NOT NULL,
    gross_margin NUMERIC(18,2) GENERATED ALWAYS AS (sales_amount - cost_amount) STORED
);

INSERT INTO pg17_generated_margin_demo (sku, sales_amount, cost_amount) VALUES
('PG17-DEMO-001', 1200.00, 830.00),
('PG17-DEMO-002', 980.00, 760.00);

-- 2. Update previous/current value comparison without high-version RETURNING aliases
WITH before_update AS (
    SELECT
        sku,
        sales_amount AS old_sales_amount,
        gross_margin AS old_gross_margin
    FROM pg17_generated_margin_demo
    WHERE sku = 'PG17-DEMO-001'
),
updated AS (
    UPDATE pg17_generated_margin_demo target
    SET sales_amount = target.sales_amount * 1.05
    FROM before_update before_row
    WHERE target.sku = before_row.sku
    RETURNING
        target.sku,
        target.sales_amount AS new_sales_amount,
        target.gross_margin AS new_gross_margin
)
SELECT
    updated.sku,
    before_update.old_sales_amount,
    updated.new_sales_amount,
    before_update.old_gross_margin,
    updated.new_gross_margin
FROM updated
JOIN before_update ON before_update.sku = updated.sku;

-- 3. Temporal non-overlap compatibility with exclusion constraint
CREATE TABLE pg17_price_validity_demo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    valid_period DATERANGE NOT NULL,
    price NUMERIC(12,2) NOT NULL,
    UNIQUE (product_id, valid_period),
    EXCLUDE USING gist (product_id WITH =, valid_period WITH &&)
);

INSERT INTO pg17_price_validity_demo (product_id, valid_period, price) VALUES
(1, daterange('2026-01-01', '2026-04-01', '[)'), 899.00),
(1, daterange('2026-04-01', '2026-07-01', '[)'), 929.00);

-- 4. Compatibility foreign key. PostgreSQL 17 cannot express temporal coverage FK,
--    so the sample keeps a normal exact-period FK plus the non-overlap constraint above.
CREATE TABLE pg17_price_promotion_demo (
    product_id BIGINT NOT NULL,
    promo_period DATERANGE NOT NULL,
    promo_price NUMERIC(12,2) NOT NULL,
    FOREIGN KEY (product_id, promo_period)
        REFERENCES pg17_price_validity_demo (product_id, valid_period)
);

INSERT INTO pg17_price_promotion_demo (product_id, promo_period, promo_price) VALUES
(1, daterange('2026-01-01', '2026-04-01', '[)'), 859.00);
