-- ============================================================
-- PostgreSQL 18 专属语法样例
-- 说明:
--   这些 SQL 用来覆盖 PostgreSQL 18 版本能力，不参与 MySQL 8.0 业务对齐。
--   可在 PostgreSQL 18 环境中单独执行。
-- ============================================================

CREATE EXTENSION IF NOT EXISTS btree_gist;

-- 1. Virtual generated column
CREATE TABLE pg18_generated_margin_demo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku VARCHAR(50) NOT NULL,
    sales_amount NUMERIC(18,2) NOT NULL,
    cost_amount NUMERIC(18,2) NOT NULL,
    gross_margin NUMERIC(18,2) GENERATED ALWAYS AS (sales_amount - cost_amount) VIRTUAL
);

INSERT INTO pg18_generated_margin_demo (sku, sales_amount, cost_amount) VALUES
('PG18-DEMO-001', 1200.00, 830.00),
('PG18-DEMO-002', 980.00, 760.00);

-- 2. RETURNING old/new values
UPDATE pg18_generated_margin_demo
SET sales_amount = sales_amount * 1.05
WHERE sku = 'PG18-DEMO-001'
RETURNING
    sku,
    old.sales_amount AS old_sales_amount,
    new.sales_amount AS new_sales_amount,
    old.gross_margin AS old_gross_margin,
    new.gross_margin AS new_gross_margin;

-- 3. Temporal primary key / unique constraint with WITHOUT OVERLAPS
CREATE TABLE pg18_price_validity_demo (
    product_id BIGINT NOT NULL,
    valid_period DATERANGE NOT NULL,
    price NUMERIC(12,2) NOT NULL,
    PRIMARY KEY (product_id, valid_period WITHOUT OVERLAPS)
);

INSERT INTO pg18_price_validity_demo (product_id, valid_period, price) VALUES
(1, daterange('2026-01-01', '2026-04-01', '[)'), 899.00),
(1, daterange('2026-04-01', '2026-07-01', '[)'), 929.00);

-- 4. Temporal foreign key with PERIOD
CREATE TABLE pg18_price_promotion_demo (
    product_id BIGINT NOT NULL,
    promo_period DATERANGE NOT NULL,
    promo_price NUMERIC(12,2) NOT NULL,
    FOREIGN KEY (product_id, PERIOD promo_period)
        REFERENCES pg18_price_validity_demo (product_id, PERIOD valid_period)
);

INSERT INTO pg18_price_promotion_demo (product_id, promo_period, promo_price) VALUES
(1, daterange('2026-02-01', '2026-02-15', '[)'), 859.00);
