-- ============================================================
-- ERP系统完整数据库设计 - Oracle 26ai
-- 模块: HR, 权限, 货品, 批号, 库存, 采购, 销售, 财务
-- 数据库: Oracle 26ai
-- ============================================================

-- ============================================================
-- 0. 自定义ENUM类型
-- ============================================================

-- 通用状态
-- 部门状态
-- 职位状态
-- 性别
-- 员工状态
-- 考勤状态
-- 请假类型
-- 请假审批状态
-- 货品状态
-- 供应商信用等级
-- 供应商合作状态
-- 批号状态
-- 仓库类型
-- 仓库状态
-- 库存交易类型
-- 请购紧急程度
-- 请购单状态
-- 采购单状态
-- 收货单状态
-- 客户类型
-- 会员等级
-- 客户状态
-- 支付方式
-- 销售单状态
-- 销售退货类型
-- 销售退货状态
-- 退货明细状态
-- 采购退货类型
-- 采购退货状态
-- 报损类型
-- 报损状态
-- 会计科目类型
-- 余额方向
-- 科目状态
-- 凭证类型
-- 凭证状态
-- 分录方向
-- 出纳日记账类型
-- 出纳日记账状态
-- 工资发放方式
-- 工资发放状态
-- 对账状态
-- 结算类型
-- 结算支付方式
-- 结算状态
-- ============================================================
-- 触发器辅助函数: 自动更新updated_at
-- ============================================================

-- update_timestamp helper is implemented inline by Oracle row triggers.

-- ============================================================
-- 1. HR模块 - 组织架构
-- ============================================================

-- 部门表
CREATE TABLE departments (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id NUMBER(19) CHECK (parent_id IS NULL OR parent_id >= 0),
    name VARCHAR2(100) NOT NULL,
    code VARCHAR2(20) NOT NULL UNIQUE,
    manager_id NUMBER(19) CHECK (manager_id IS NULL OR manager_id >= 0),
    budget NUMBER(18,2) DEFAULT 0.00,
    headcount_plan NUMBER(10) CHECK (headcount_plan IS NULL OR headcount_plan >= 0) DEFAULT 0,
    status VARCHAR2(40) DEFAULT 'active',
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_dept_parent FOREIGN KEY (parent_id) REFERENCES departments(id) ON DELETE SET NULL
);

CREATE INDEX idx_dept_parent ON departments(parent_id);
CREATE INDEX idx_dept_status ON departments(status);

COMMENT ON TABLE departments IS '部门表';
COMMENT ON COLUMN departments.manager_id IS '部门负责人';
COMMENT ON COLUMN departments.budget IS '部门预算';
COMMENT ON COLUMN departments.headcount_plan IS '计划编制人数';

CREATE OR REPLACE TRIGGER trg_departments_updated_at
    BEFORE UPDATE ON departments
    FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- 职位表
CREATE TABLE positions (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id NUMBER(19) NOT NULL CHECK (department_id >= 0),
    name VARCHAR2(100) NOT NULL,
    code VARCHAR2(20) NOT NULL,
    level NUMBER(5) CHECK (level IS NULL OR (level >= 0 AND level <= 15)) DEFAULT 1,
    min_salary NUMBER(12,2) DEFAULT 0.00,
    max_salary NUMBER(12,2) DEFAULT 0.00,
    headcount NUMBER(10) DEFAULT 1 CHECK (headcount >= 0),
    status VARCHAR2(40) DEFAULT 'active',
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (department_id, code),
    CONSTRAINT fk_pos_dept FOREIGN KEY (department_id) REFERENCES departments(id) ON DELETE CASCADE
);

CREATE INDEX idx_pos_level ON positions(level);

COMMENT ON TABLE positions IS '职位表';
COMMENT ON COLUMN positions.level IS '职级 1-15';
COMMENT ON COLUMN positions.headcount IS '编制人数';

-- 员工表
CREATE TABLE employees (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_no VARCHAR2(20) NOT NULL UNIQUE,
    name VARCHAR2(50) NOT NULL,
    gender VARCHAR2(40) NOT NULL,
    id_card VARCHAR2(18) NOT NULL UNIQUE,
    phone VARCHAR2(20) NOT NULL,
    email VARCHAR2(100),
    birth_date DATE NOT NULL,
    hire_date DATE NOT NULL,
    department_id NUMBER(19) NOT NULL CHECK (department_id >= 0),
    position_id NUMBER(19) NOT NULL CHECK (position_id >= 0),
    manager_id NUMBER(19) CHECK (manager_id IS NULL OR manager_id >= 0),
    salary NUMBER(12,2) NOT NULL DEFAULT 0.00,
    social_security_base NUMBER(12,2) DEFAULT 0.00,
    housing_fund_base NUMBER(12,2) DEFAULT 0.00,
    bank_name VARCHAR2(100),
    bank_account VARCHAR2(50),
    status VARCHAR2(40) DEFAULT 'probation',
    resignation_date DATE,
    resignation_reason VARCHAR2(500),
    address VARCHAR2(200),
    emergency_contact VARCHAR2(50),
    emergency_phone VARCHAR2(20),
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_emp_dept FOREIGN KEY (department_id) REFERENCES departments(id),
    CONSTRAINT fk_emp_pos FOREIGN KEY (position_id) REFERENCES positions(id),
    CONSTRAINT fk_emp_manager FOREIGN KEY (manager_id) REFERENCES employees(id) ON DELETE SET NULL
);

CREATE INDEX idx_emp_dept ON employees(department_id);
CREATE INDEX idx_emp_position ON employees(position_id);
CREATE INDEX idx_emp_manager ON employees(manager_id);
CREATE INDEX idx_emp_status ON employees(status);
CREATE INDEX idx_emp_hire_date ON employees(hire_date);
CREATE INDEX idx_emp_resignation ON employees(resignation_date);

COMMENT ON TABLE employees IS '员工表';
COMMENT ON COLUMN employees.employee_no IS '工号';
COMMENT ON COLUMN employees.id_card IS '身份证号';
COMMENT ON COLUMN employees.social_security_base IS '社保基数';
COMMENT ON COLUMN employees.housing_fund_base IS '公积金基数';
COMMENT ON COLUMN employees.bank_name IS '开户银行';
COMMENT ON COLUMN employees.bank_account IS '银行账号';

CREATE OR REPLACE TRIGGER trg_employees_updated_at
    BEFORE UPDATE ON employees
    FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- 更新部门负责人外键
ALTER TABLE departments ADD CONSTRAINT fk_dept_manager FOREIGN KEY (manager_id) REFERENCES employees(id) ON DELETE SET NULL;

-- 薪资变动记录
CREATE TABLE employee_salary_log (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id NUMBER(19) NOT NULL CHECK (employee_id >= 0),
    old_salary NUMBER(12,2) NOT NULL,
    new_salary NUMBER(12,2) NOT NULL,
    change_reason VARCHAR2(200) NOT NULL,
    effective_date DATE NOT NULL,
    approved_by NUMBER(19) CHECK (approved_by IS NULL OR approved_by >= 0),
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sal_emp FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE
);

CREATE INDEX idx_sal_employee ON employee_salary_log(employee_id);
CREATE INDEX idx_sal_effective_date ON employee_salary_log(effective_date);

-- 考勤记录
CREATE TABLE attendance (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id NUMBER(19) NOT NULL CHECK (employee_id >= 0),
    attendance_date DATE NOT NULL,
    clock_in TIMESTAMP(0),
    clock_out TIMESTAMP(0),
    status VARCHAR2(40) DEFAULT 'normal',
    late_minutes NUMBER(10) DEFAULT 0,
    early_minutes NUMBER(10) DEFAULT 0,
    overtime_hours NUMBER(4,1) DEFAULT 0.0,
    remark VARCHAR2(200),
    UNIQUE (employee_id, attendance_date),
    CONSTRAINT fk_att_emp FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE
);

CREATE INDEX idx_att_date ON attendance(attendance_date);

-- 请假记录
CREATE TABLE leave_records (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id NUMBER(19) NOT NULL CHECK (employee_id >= 0),
    leave_type VARCHAR2(40) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    days NUMBER(4,1) NOT NULL,
    reason VARCHAR2(500),
    status VARCHAR2(40) DEFAULT 'pending',
    approved_by NUMBER(19) CHECK (approved_by IS NULL OR approved_by >= 0),
    approved_at TIMESTAMP(0),
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_leave_emp FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE
);

CREATE INDEX idx_leave_emp ON leave_records(employee_id);
CREATE INDEX idx_leave_date_range ON leave_records(start_date, end_date);
CREATE INDEX idx_leave_status ON leave_records(status);

-- ============================================================
-- 2. 权限模块
-- ============================================================

CREATE TABLE roles (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(50) NOT NULL UNIQUE,
    code VARCHAR2(30) NOT NULL UNIQUE,
    description VARCHAR2(200),
    is_system NUMBER(1) DEFAULT 0,
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON COLUMN roles.is_system IS '系统内置角色';

CREATE TABLE permissions (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id NUMBER(19) CHECK (parent_id IS NULL OR parent_id >= 0),
    name VARCHAR2(100) NOT NULL,
    code VARCHAR2(50) NOT NULL UNIQUE,
    resource_type VARCHAR2(50) NOT NULL,
    resource_path VARCHAR2(200),
    action VARCHAR2(50) NOT NULL,
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_perm_parent FOREIGN KEY (parent_id) REFERENCES permissions(id) ON DELETE SET NULL
);

CREATE INDEX idx_perm_parent ON permissions(parent_id);
CREATE INDEX idx_perm_resource ON permissions(resource_type);

COMMENT ON COLUMN permissions.code IS '权限标识符';
COMMENT ON COLUMN permissions.resource_type IS '资源类型: menu, api, button, data';
COMMENT ON COLUMN permissions.resource_path IS '资源路径';
COMMENT ON COLUMN permissions.action IS '操作: create,read,update,delete,approve,export,import';

CREATE TABLE role_permissions (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id NUMBER(19) NOT NULL CHECK (role_id >= 0),
    permission_id NUMBER(19) NOT NULL CHECK (permission_id >= 0),
    UNIQUE (role_id, permission_id),
    CONSTRAINT fk_rp_role FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE,
    CONSTRAINT fk_rp_perm FOREIGN KEY (permission_id) REFERENCES permissions(id) ON DELETE CASCADE
);

CREATE TABLE employee_roles (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id NUMBER(19) NOT NULL CHECK (employee_id >= 0),
    role_id NUMBER(19) NOT NULL CHECK (role_id >= 0),
    granted_by NUMBER(19) CHECK (granted_by IS NULL OR granted_by >= 0),
    granted_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP(0),
    UNIQUE (employee_id, role_id),
    CONSTRAINT fk_er_emp FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE,
    CONSTRAINT fk_er_role FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
);

-- 操作审计日志
CREATE TABLE audit_log (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id NUMBER(19) CHECK (employee_id IS NULL OR employee_id >= 0),
    action VARCHAR2(100) NOT NULL,
    target_type VARCHAR2(50) NOT NULL,
    target_id NUMBER(19),
    old_value CLOB,
    new_value CLOB,
    ip_address VARCHAR2(45),
    user_agent VARCHAR2(500),
    remark VARCHAR2(500),
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_audit_employee ON audit_log(employee_id);
CREATE INDEX idx_audit_target ON audit_log(target_type, target_id);
CREATE INDEX idx_audit_created_at ON audit_log(created_at);
CREATE INDEX idx_audit_action ON audit_log(action);

COMMENT ON COLUMN audit_log.target_type IS '操作对象类型';
COMMENT ON COLUMN audit_log.target_id IS '操作对象ID';

-- ============================================================
-- 3. 货品与批号模块
-- ============================================================

CREATE TABLE product_categories (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id NUMBER(19) CHECK (parent_id IS NULL OR parent_id >= 0),
    name VARCHAR2(100) NOT NULL,
    code VARCHAR2(20) NOT NULL UNIQUE,
    description VARCHAR2(500),
    sort_order NUMBER(10) DEFAULT 0,
    status VARCHAR2(40) DEFAULT 'active',
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_cat_parent FOREIGN KEY (parent_id) REFERENCES product_categories(id) ON DELETE SET NULL
);

CREATE INDEX idx_cat_parent ON product_categories(parent_id);

-- 供应商表
CREATE TABLE suppliers (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(200) NOT NULL,
    code VARCHAR2(20) NOT NULL UNIQUE,
    contact_person VARCHAR2(50),
    phone VARCHAR2(20),
    email VARCHAR2(100),
    address VARCHAR2(300),
    province VARCHAR2(50),
    city VARCHAR2(50),
    district VARCHAR2(50),
    latitude NUMBER(10,7),
    longitude NUMBER(10,7),
    bank_name VARCHAR2(100),
    bank_account VARCHAR2(50),
    tax_id VARCHAR2(50),
    credit_level VARCHAR2(40) DEFAULT 'B',
    cooperation_status VARCHAR2(40) DEFAULT 'active',
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_supplier_status ON suppliers(cooperation_status);
CREATE INDEX idx_supplier_city ON suppliers(city);
CREATE INDEX idx_supplier_province ON suppliers(province);

COMMENT ON TABLE suppliers IS '供应商表';
COMMENT ON COLUMN suppliers.province IS '省份';
COMMENT ON COLUMN suppliers.city IS '城市';
COMMENT ON COLUMN suppliers.district IS '区县';
COMMENT ON COLUMN suppliers.latitude IS '纬度';
COMMENT ON COLUMN suppliers.longitude IS '经度';
COMMENT ON COLUMN suppliers.tax_id IS '税号';

CREATE OR REPLACE TRIGGER trg_suppliers_updated_at
    BEFORE UPDATE ON suppliers
    FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

CREATE TABLE products (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku VARCHAR2(50) NOT NULL UNIQUE,
    name VARCHAR2(200) NOT NULL,
    category_id NUMBER(19) NOT NULL CHECK (category_id >= 0),
    unit VARCHAR2(20) NOT NULL DEFAULT '件',
    spec VARCHAR2(100),
    brand VARCHAR2(100),
    barcode VARCHAR2(50),
    purchase_price NUMBER(12,2) DEFAULT 0.00,
    wholesale_price NUMBER(12,2) DEFAULT 0.00,
    retail_price NUMBER(12,2) DEFAULT 0.00,
    min_stock NUMBER(10) DEFAULT 0,
    max_stock NUMBER(10) DEFAULT 99999,
    batch_managed NUMBER(1) DEFAULT 1,
    shelf_life_days NUMBER(10) DEFAULT 0,
    weight_kg NUMBER(8,3) DEFAULT 0.000,
    volume_m3 NUMBER(8,6) DEFAULT 0.000000,
    status VARCHAR2(40) DEFAULT 'active',
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_prod_cat FOREIGN KEY (category_id) REFERENCES product_categories(id)
);

CREATE INDEX idx_prod_category ON products(category_id);
CREATE INDEX idx_prod_status ON products(status);
CREATE INDEX idx_prod_barcode ON products(barcode);

COMMENT ON COLUMN products.sku IS 'SKU编码';
COMMENT ON COLUMN products.unit IS '计量单位';
COMMENT ON COLUMN products.spec IS '规格型号';
COMMENT ON COLUMN products.purchase_price IS '进货价';
COMMENT ON COLUMN products.wholesale_price IS '批发价';
COMMENT ON COLUMN products.retail_price IS '零售价';
COMMENT ON COLUMN products.min_stock IS '最低库存警戒';
COMMENT ON COLUMN products.max_stock IS '最高库存';
COMMENT ON COLUMN products.batch_managed IS '是否批号管理';
COMMENT ON COLUMN products.shelf_life_days IS '保质期天数';

CREATE OR REPLACE TRIGGER trg_products_updated_at
    BEFORE UPDATE ON products
    FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- 供应商-货品关联
CREATE TABLE supplier_products (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id NUMBER(19) NOT NULL CHECK (supplier_id >= 0),
    product_id NUMBER(19) NOT NULL CHECK (product_id >= 0),
    supplier_price NUMBER(12,2) DEFAULT 0.00,
    lead_time_days NUMBER(10) DEFAULT 0,
    min_order_qty NUMBER(10) DEFAULT 1,
    shipping_cost_per_km NUMBER(8,4) DEFAULT 0.50,
    return_rate NUMBER(5,4) DEFAULT 0.00,
    quality_score NUMBER(5,2) DEFAULT 100.00,
    is_preferred NUMBER(1) DEFAULT 0,
    last_order_date DATE,
    total_order_count NUMBER(10) DEFAULT 0,
    total_order_qty NUMBER(10) DEFAULT 0,
    UNIQUE (supplier_id, product_id),
    CONSTRAINT fk_sp_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE CASCADE,
    CONSTRAINT fk_sp_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);

CREATE INDEX idx_sp_product_price ON supplier_products(product_id, supplier_price);
CREATE INDEX idx_sp_quality ON supplier_products(quality_score);

COMMENT ON COLUMN supplier_products.supplier_price IS '供应商报价';
COMMENT ON COLUMN supplier_products.lead_time_days IS '供货周期(天)';
COMMENT ON COLUMN supplier_products.min_order_qty IS '最小起订量';
COMMENT ON COLUMN supplier_products.shipping_cost_per_km IS '每公里物流费率(元/km)';
COMMENT ON COLUMN supplier_products.return_rate IS '该货品历史退货率(0-1)';
COMMENT ON COLUMN supplier_products.quality_score IS '质检评分(0-100)';
COMMENT ON COLUMN supplier_products.is_preferred IS '是否优选供应商';
COMMENT ON COLUMN supplier_products.last_order_date IS '最近采购日期';
COMMENT ON COLUMN supplier_products.total_order_count IS '累计采购次数';
COMMENT ON COLUMN supplier_products.total_order_qty IS '累计采购数量';

-- 批号管理
CREATE TABLE product_batches (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id NUMBER(19) NOT NULL CHECK (product_id >= 0),
    batch_no VARCHAR2(50) NOT NULL,
    production_date DATE,
    expiry_date DATE,
    supplier_id NUMBER(19) CHECK (supplier_id IS NULL OR supplier_id >= 0),
    purchase_price NUMBER(12,2) DEFAULT 0.00,
    initial_qty NUMBER(10) NOT NULL DEFAULT 0,
    current_qty NUMBER(10) NOT NULL DEFAULT 0,
    status VARCHAR2(40) DEFAULT 'active',
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (product_id, batch_no),
    CONSTRAINT fk_batch_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
    CONSTRAINT fk_batch_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE SET NULL
);

CREATE INDEX idx_batch_expiry ON product_batches(expiry_date);
CREATE INDEX idx_batch_status ON product_batches(status);
CREATE INDEX idx_batch_supplier ON product_batches(supplier_id);

COMMENT ON COLUMN product_batches.production_date IS '生产日期';
COMMENT ON COLUMN product_batches.expiry_date IS '过期日期';
COMMENT ON COLUMN product_batches.initial_qty IS '初始数量';
COMMENT ON COLUMN product_batches.current_qty IS '当前数量';

-- ============================================================
-- 4. 库存模块
-- ============================================================

CREATE TABLE warehouses (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    code VARCHAR2(20) NOT NULL UNIQUE,
    address VARCHAR2(200),
    province VARCHAR2(50),
    city VARCHAR2(50),
    district VARCHAR2(50),
    latitude NUMBER(10,7),
    longitude NUMBER(10,7),
    manager_id NUMBER(19) CHECK (manager_id IS NULL OR manager_id >= 0),
    type VARCHAR2(40) DEFAULT 'main',
    capacity_m3 NUMBER(10,3) DEFAULT 0.000,
    status VARCHAR2(40) DEFAULT 'active',
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_wh_manager FOREIGN KEY (manager_id) REFERENCES employees(id) ON DELETE SET NULL
);

CREATE INDEX idx_wh_type ON warehouses(type);
CREATE INDEX idx_wh_city ON warehouses(city);
CREATE INDEX idx_wh_province ON warehouses(province);

COMMENT ON TABLE warehouses IS '仓库/门店表';
COMMENT ON COLUMN warehouses.province IS '省份';
COMMENT ON COLUMN warehouses.city IS '城市';
COMMENT ON COLUMN warehouses.district IS '区县';

CREATE TABLE inventory (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id NUMBER(19) NOT NULL CHECK (product_id >= 0),
    batch_id NUMBER(19) CHECK (batch_id IS NULL OR batch_id >= 0),
    warehouse_id NUMBER(19) NOT NULL CHECK (warehouse_id >= 0),
    shelf_location VARCHAR2(50),
    quantity NUMBER(10) NOT NULL DEFAULT 0,
    locked_quantity NUMBER(10) DEFAULT 0,
    available_quantity NUMBER(10) GENERATED ALWAYS AS (quantity - locked_quantity) STORED,
    last_stocktake_date DATE,
    updated_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (product_id, batch_id, warehouse_id),
    CONSTRAINT fk_inv_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
    CONSTRAINT fk_inv_batch FOREIGN KEY (batch_id) REFERENCES product_batches(id) ON DELETE SET NULL,
    CONSTRAINT fk_inv_wh FOREIGN KEY (warehouse_id) REFERENCES warehouses(id) ON DELETE CASCADE
);

CREATE INDEX idx_inv_warehouse ON inventory(warehouse_id);
CREATE INDEX idx_inv_quantity ON inventory(quantity);
CREATE INDEX idx_inv_available ON inventory(available_quantity);

COMMENT ON COLUMN inventory.shelf_location IS '货架位置';
COMMENT ON COLUMN inventory.locked_quantity IS '锁定库存';

CREATE OR REPLACE TRIGGER trg_inventory_updated_at
    BEFORE UPDATE ON inventory
    FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- 库存变动日志
CREATE TABLE inventory_transactions (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id NUMBER(19) NOT NULL CHECK (product_id >= 0),
    batch_id NUMBER(19) CHECK (batch_id IS NULL OR batch_id >= 0),
    warehouse_id NUMBER(19) NOT NULL CHECK (warehouse_id >= 0),
    transaction_type VARCHAR2(40) NOT NULL,
    quantity_change NUMBER(10) NOT NULL,
    before_qty NUMBER(10) NOT NULL,
    after_qty NUMBER(10) NOT NULL,
    reference_type VARCHAR2(50),
    reference_id NUMBER(19),
    operator_id NUMBER(19) CHECK (operator_id IS NULL OR operator_id >= 0),
    remark VARCHAR2(500),
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_it_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
    CONSTRAINT fk_it_batch FOREIGN KEY (batch_id) REFERENCES product_batches(id) ON DELETE SET NULL,
    CONSTRAINT fk_it_wh FOREIGN KEY (warehouse_id) REFERENCES warehouses(id) ON DELETE CASCADE
);

CREATE INDEX idx_it_product ON inventory_transactions(product_id);
CREATE INDEX idx_it_warehouse ON inventory_transactions(warehouse_id);
CREATE INDEX idx_it_type ON inventory_transactions(transaction_type);
CREATE INDEX idx_it_reference ON inventory_transactions(reference_type, reference_id);
CREATE INDEX idx_it_created_at ON inventory_transactions(created_at);

COMMENT ON COLUMN inventory_transactions.quantity_change IS '正数=入库，负数=出库';

-- ============================================================
-- 5. 采购模块
-- ============================================================

-- 请购单
CREATE TABLE purchase_requisitions (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requisition_no VARCHAR2(30) NOT NULL UNIQUE,
    department_id NUMBER(19) NOT NULL CHECK (department_id >= 0),
    requester_id NUMBER(19) NOT NULL CHECK (requester_id >= 0),
    requisition_date DATE NOT NULL,
    required_date DATE,
    urgency VARCHAR2(40) DEFAULT 'normal',
    total_amount NUMBER(18,2) DEFAULT 0.00,
    status VARCHAR2(40) DEFAULT 'draft',
    remark VARCHAR2(500),
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_pr_dept FOREIGN KEY (department_id) REFERENCES departments(id),
    CONSTRAINT fk_pr_requester FOREIGN KEY (requester_id) REFERENCES employees(id)
);

CREATE INDEX idx_pr_dept ON purchase_requisitions(department_id);
CREATE INDEX idx_pr_requester ON purchase_requisitions(requester_id);
CREATE INDEX idx_pr_status ON purchase_requisitions(status);
CREATE INDEX idx_pr_date ON purchase_requisitions(requisition_date);

CREATE OR REPLACE TRIGGER trg_pr_updated_at
    BEFORE UPDATE ON purchase_requisitions
    FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

CREATE TABLE purchase_requisition_items (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requisition_id NUMBER(19) NOT NULL CHECK (requisition_id >= 0),
    product_id NUMBER(19) NOT NULL CHECK (product_id >= 0),
    quantity NUMBER(10) NOT NULL,
    estimated_price NUMBER(12,2) DEFAULT 0.00,
    amount NUMBER(18,2) GENERATED ALWAYS AS (quantity * estimated_price) STORED,
    remark VARCHAR2(200),
    CONSTRAINT fk_pri_req FOREIGN KEY (requisition_id) REFERENCES purchase_requisitions(id) ON DELETE CASCADE,
    CONSTRAINT fk_pri_product FOREIGN KEY (product_id) REFERENCES products(id)
);

CREATE INDEX idx_pri_product ON purchase_requisition_items(product_id);

-- 采购单
CREATE TABLE purchase_orders (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no VARCHAR2(30) NOT NULL UNIQUE,
    supplier_id NUMBER(19) NOT NULL CHECK (supplier_id >= 0),
    requisition_id NUMBER(19) CHECK (requisition_id IS NULL OR requisition_id >= 0),
    department_id NUMBER(19) NOT NULL CHECK (department_id >= 0),
    purchaser_id NUMBER(19) NOT NULL CHECK (purchaser_id >= 0),
    order_date DATE NOT NULL,
    expected_delivery_date DATE,
    actual_delivery_date DATE,
    total_amount NUMBER(18,2) DEFAULT 0.00,
    paid_amount NUMBER(18,2) DEFAULT 0.00,
    payment_terms VARCHAR2(100),
    status VARCHAR2(40) DEFAULT 'draft',
    remark VARCHAR2(500),
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_po_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers(id),
    CONSTRAINT fk_po_req FOREIGN KEY (requisition_id) REFERENCES purchase_requisitions(id) ON DELETE SET NULL,
    CONSTRAINT fk_po_purchaser FOREIGN KEY (purchaser_id) REFERENCES employees(id)
);

CREATE INDEX idx_po_supplier ON purchase_orders(supplier_id);
CREATE INDEX idx_po_requisition ON purchase_orders(requisition_id);
CREATE INDEX idx_po_purchaser ON purchase_orders(purchaser_id);
CREATE INDEX idx_po_status ON purchase_orders(status);
CREATE INDEX idx_po_date ON purchase_orders(order_date);

COMMENT ON COLUMN purchase_orders.payment_terms IS '付款条件';

CREATE OR REPLACE TRIGGER trg_po_updated_at
    BEFORE UPDATE ON purchase_orders
    FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

CREATE TABLE purchase_order_items (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id NUMBER(19) NOT NULL CHECK (order_id >= 0),
    product_id NUMBER(19) NOT NULL CHECK (product_id >= 0),
    quantity NUMBER(10) NOT NULL,
    unit_price NUMBER(12,2) NOT NULL,
    amount NUMBER(18,2) GENERATED ALWAYS AS (quantity * unit_price) STORED,
    received_qty NUMBER(10) DEFAULT 0,
    returned_qty NUMBER(10) DEFAULT 0,
    remark VARCHAR2(200),
    CONSTRAINT fk_poi_order FOREIGN KEY (order_id) REFERENCES purchase_orders(id) ON DELETE CASCADE,
    CONSTRAINT fk_poi_product FOREIGN KEY (product_id) REFERENCES products(id)
);

CREATE INDEX idx_poi_product ON purchase_order_items(product_id);

-- 进货单（入库单）
CREATE TABLE purchase_receipts (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_no VARCHAR2(30) NOT NULL UNIQUE,
    order_id NUMBER(19) NOT NULL CHECK (order_id >= 0),
    warehouse_id NUMBER(19) NOT NULL CHECK (warehouse_id >= 0),
    receiver_id NUMBER(19) NOT NULL CHECK (receiver_id >= 0),
    receipt_date DATE NOT NULL,
    batch_no VARCHAR2(50),
    total_qty NUMBER(10) DEFAULT 0,
    total_amount NUMBER(18,2) DEFAULT 0.00,
    status VARCHAR2(40) DEFAULT 'pending',
    inspection_result VARCHAR2(500),
    remark VARCHAR2(500),
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_prec_order FOREIGN KEY (order_id) REFERENCES purchase_orders(id),
    CONSTRAINT fk_prec_wh FOREIGN KEY (warehouse_id) REFERENCES warehouses(id),
    CONSTRAINT fk_prec_receiver FOREIGN KEY (receiver_id) REFERENCES employees(id)
);

CREATE INDEX idx_prec_order ON purchase_receipts(order_id);
CREATE INDEX idx_prec_warehouse ON purchase_receipts(warehouse_id);
CREATE INDEX idx_prec_date ON purchase_receipts(receipt_date);

COMMENT ON COLUMN purchase_receipts.batch_no IS '统一批号';
COMMENT ON COLUMN purchase_receipts.inspection_result IS '质检结果';

CREATE TABLE purchase_receipt_items (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_id NUMBER(19) NOT NULL CHECK (receipt_id >= 0),
    order_item_id NUMBER(19) NOT NULL CHECK (order_item_id >= 0),
    product_id NUMBER(19) NOT NULL CHECK (product_id >= 0),
    batch_id NUMBER(19) CHECK (batch_id IS NULL OR batch_id >= 0),
    received_qty NUMBER(10) NOT NULL,
    accepted_qty NUMBER(10) DEFAULT 0,
    rejected_qty NUMBER(10) DEFAULT 0,
    unit_price NUMBER(12,2) NOT NULL,
    production_date DATE,
    expiry_date DATE,
    remark VARCHAR2(200),
    CONSTRAINT fk_preci_receipt FOREIGN KEY (receipt_id) REFERENCES purchase_receipts(id) ON DELETE CASCADE,
    CONSTRAINT fk_preci_product FOREIGN KEY (product_id) REFERENCES products(id),
    CONSTRAINT fk_preci_batch FOREIGN KEY (batch_id) REFERENCES product_batches(id) ON DELETE SET NULL
);

CREATE INDEX idx_preci_order_item ON purchase_receipt_items(order_item_id);
CREATE INDEX idx_preci_product ON purchase_receipt_items(product_id);
CREATE INDEX idx_preci_batch ON purchase_receipt_items(batch_id);

COMMENT ON COLUMN purchase_receipt_items.accepted_qty IS '合格数量';
COMMENT ON COLUMN purchase_receipt_items.rejected_qty IS '不合格数量';

-- ============================================================
-- 6. 销售模块
-- ============================================================

CREATE TABLE customers (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR2(20) NOT NULL UNIQUE,
    name VARCHAR2(200) NOT NULL,
    type VARCHAR2(40) DEFAULT 'individual',
    contact_person VARCHAR2(50),
    phone VARCHAR2(20),
    email VARCHAR2(100),
    address VARCHAR2(300),
    credit_limit NUMBER(18,2) DEFAULT 0.00,
    credit_days NUMBER(10) DEFAULT 30,
    balance NUMBER(18,2) DEFAULT 0.00,
    payment_method VARCHAR2(40) DEFAULT 'normal',
    status VARCHAR2(40) DEFAULT 'active',
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_customer_type ON customers(type);
CREATE INDEX idx_customer_status ON customers(status);
CREATE INDEX idx_customer_membership ON customers(VARCHAR2(40));

COMMENT ON COLUMN customers.credit_limit IS '信用额度';
COMMENT ON COLUMN customers.credit_days IS '账期天数';
COMMENT ON COLUMN customers.balance IS '账户余额/欠款';

CREATE OR REPLACE TRIGGER trg_customers_updated_at
    BEFORE UPDATE ON customers
    FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- 销售单
CREATE TABLE sales_orders (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no VARCHAR2(30) NOT NULL UNIQUE,
    customer_id NUMBER(19) NOT NULL CHECK (customer_id >= 0),
    salesperson_id NUMBER(19) NOT NULL CHECK (salesperson_id >= 0),
    warehouse_id NUMBER(19) NOT NULL CHECK (warehouse_id >= 0),
    order_date DATE NOT NULL,
    delivery_date DATE,
    total_amount NUMBER(18,2) DEFAULT 0.00,
    discount_amount NUMBER(18,2) DEFAULT 0.00,
    paid_amount NUMBER(18,2) DEFAULT 0.00,
    tax_amount NUMBER(18,2) DEFAULT 0.00,
    payment_method VARCHAR2(40) DEFAULT 'transfer',
    status VARCHAR2(40) DEFAULT 'draft',
    invoice_no VARCHAR2(50),
    remark VARCHAR2(500),
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_so_customer FOREIGN KEY (customer_id) REFERENCES customers(id),
    CONSTRAINT fk_so_salesperson FOREIGN KEY (salesperson_id) REFERENCES employees(id),
    CONSTRAINT fk_so_wh FOREIGN KEY (warehouse_id) REFERENCES warehouses(id)
);

CREATE INDEX idx_so_customer ON sales_orders(customer_id);
CREATE INDEX idx_so_salesperson ON sales_orders(salesperson_id);
CREATE INDEX idx_so_date ON sales_orders(order_date);
CREATE INDEX idx_so_status ON sales_orders(status);
CREATE INDEX idx_so_payment ON sales_orders(payment_method);

CREATE OR REPLACE TRIGGER trg_so_updated_at
    BEFORE UPDATE ON sales_orders
    FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

CREATE TABLE sales_order_items (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id NUMBER(19) NOT NULL CHECK (order_id >= 0),
    product_id NUMBER(19) NOT NULL CHECK (product_id >= 0),
    batch_id NUMBER(19) CHECK (batch_id IS NULL OR batch_id >= 0),
    quantity NUMBER(10) NOT NULL,
    unit_price NUMBER(12,2) NOT NULL,
    discount NUMBER(12,2) DEFAULT 0.00,
    amount NUMBER(18,2) NOT NULL,
    returned_qty NUMBER(10) DEFAULT 0,
    CONSTRAINT fk_soi_order FOREIGN KEY (order_id) REFERENCES sales_orders(id) ON DELETE CASCADE,
    CONSTRAINT fk_soi_product FOREIGN KEY (product_id) REFERENCES products(id),
    CONSTRAINT fk_soi_batch FOREIGN KEY (batch_id) REFERENCES product_batches(id) ON DELETE SET NULL
);

CREATE INDEX idx_soi_order ON sales_order_items(order_id);
CREATE INDEX idx_soi_product ON sales_order_items(product_id);
CREATE INDEX idx_soi_batch ON sales_order_items(batch_id);

COMMENT ON COLUMN sales_order_items.amount IS '折后金额';

-- 退库单
CREATE TABLE sales_returns (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    return_no VARCHAR2(30) NOT NULL UNIQUE,
    order_id NUMBER(19) NOT NULL CHECK (order_id >= 0),
    customer_id NUMBER(19) NOT NULL CHECK (customer_id >= 0),
    warehouse_id NUMBER(19) NOT NULL CHECK (warehouse_id >= 0),
    handler_id NUMBER(19) NOT NULL CHECK (handler_id >= 0),
    return_date DATE NOT NULL,
    return_reason VARCHAR2(500) NOT NULL,
    return_type VARCHAR2(40) DEFAULT 'other',
    total_amount NUMBER(18,2) DEFAULT 0.00,
    refund_amount NUMBER(18,2) DEFAULT 0.00,
    restock_fee NUMBER(12,2) DEFAULT 0.00,
    status VARCHAR2(40) DEFAULT 'pending',
    approved_by NUMBER(19) CHECK (approved_by IS NULL OR approved_by >= 0),
    approved_at TIMESTAMP(0),
    refund_voucher_id NUMBER(19) CHECK (refund_voucher_id IS NULL OR refund_voucher_id >= 0),
    return_shipping_fee NUMBER(12,2) DEFAULT 0.00,
    remark VARCHAR2(500),
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sr_order FOREIGN KEY (order_id) REFERENCES sales_orders(id),
    CONSTRAINT fk_sr_customer FOREIGN KEY (customer_id) REFERENCES customers(id),
    CONSTRAINT fk_sr_wh FOREIGN KEY (warehouse_id) REFERENCES warehouses(id),
    CONSTRAINT fk_sr_handler FOREIGN KEY (handler_id) REFERENCES employees(id),
    CONSTRAINT fk_sr_approved FOREIGN KEY (approved_by) REFERENCES employees(id)
);

CREATE INDEX idx_sr_order ON sales_returns(order_id);
CREATE INDEX idx_sr_customer ON sales_returns(customer_id);
CREATE INDEX idx_sr_date ON sales_returns(return_date);
CREATE INDEX idx_sr_status ON sales_returns(status);
CREATE INDEX idx_sr_approved ON sales_returns(approved_by);
CREATE INDEX idx_sr_type ON sales_returns(return_type);

COMMENT ON COLUMN sales_returns.handler_id IS '处理人';
COMMENT ON COLUMN sales_returns.refund_amount IS '实际退款金额';
COMMENT ON COLUMN sales_returns.restock_fee IS '退货折旧费/手续费';
COMMENT ON COLUMN sales_returns.approved_by IS '审批人';
COMMENT ON COLUMN sales_returns.approved_at IS '审批时间';
COMMENT ON COLUMN sales_returns.return_shipping_fee IS '退货运费';

CREATE OR REPLACE TRIGGER trg_sr_updated_at
    BEFORE UPDATE ON sales_returns
    FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

CREATE TABLE sales_return_items (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    return_id NUMBER(19) NOT NULL CHECK (return_id >= 0),
    order_item_id NUMBER(19) NOT NULL CHECK (order_item_id >= 0),
    product_id NUMBER(19) NOT NULL CHECK (product_id >= 0),
    batch_id NUMBER(19) CHECK (batch_id IS NULL OR batch_id >= 0),
    return_qty NUMBER(10) NOT NULL,
    unit_price NUMBER(12,2) NOT NULL,
    amount NUMBER(18,2) NOT NULL,
    status VARCHAR2(40) DEFAULT 'pending',
    CONSTRAINT fk_sri_return FOREIGN KEY (return_id) REFERENCES sales_returns(id) ON DELETE CASCADE,
    CONSTRAINT fk_sri_product FOREIGN KEY (product_id) REFERENCES products(id),
    CONSTRAINT fk_sri_batch FOREIGN KEY (batch_id) REFERENCES product_batches(id) ON DELETE SET NULL
);

CREATE INDEX idx_sri_order_item ON sales_return_items(order_item_id);

-- ============================================================
-- 6B. 退货给供应商模块 (采购退货)
-- ============================================================

CREATE TABLE purchase_returns (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    return_no VARCHAR2(30) NOT NULL UNIQUE,
    purchase_order_id NUMBER(19) NOT NULL CHECK (purchase_order_id >= 0),
    purchase_receipt_id NUMBER(19) CHECK (purchase_receipt_id IS NULL OR purchase_receipt_id >= 0),
    supplier_id NUMBER(19) NOT NULL CHECK (supplier_id >= 0),
    warehouse_id NUMBER(19) NOT NULL CHECK (warehouse_id >= 0),
    handler_id NUMBER(19) NOT NULL CHECK (handler_id >= 0),
    return_date DATE NOT NULL,
    return_reason VARCHAR2(500) NOT NULL,
    return_type VARCHAR2(40) DEFAULT 'quality',
    total_amount NUMBER(18,2) DEFAULT 0.00,
    refund_received NUMBER(18,2) DEFAULT 0.00,
    shipping_fee NUMBER(12,2) DEFAULT 0.00,
    status VARCHAR2(40) DEFAULT 'draft',
    approved_by NUMBER(19) CHECK (approved_by IS NULL OR approved_by >= 0),
    approved_at TIMESTAMP(0),
    refund_voucher_id NUMBER(19) CHECK (refund_voucher_id IS NULL OR refund_voucher_id >= 0),
    remark VARCHAR2(500),
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_prt_po FOREIGN KEY (purchase_order_id) REFERENCES purchase_orders(id),
    CONSTRAINT fk_prt_receipt FOREIGN KEY (purchase_receipt_id) REFERENCES purchase_receipts(id) ON DELETE SET NULL,
    CONSTRAINT fk_prt_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers(id),
    CONSTRAINT fk_prt_wh FOREIGN KEY (warehouse_id) REFERENCES warehouses(id),
    CONSTRAINT fk_prt_handler FOREIGN KEY (handler_id) REFERENCES employees(id),
    CONSTRAINT fk_prt_approved FOREIGN KEY (approved_by) REFERENCES employees(id)
);

CREATE INDEX idx_prt_po ON purchase_returns(purchase_order_id);
CREATE INDEX idx_prt_supplier ON purchase_returns(supplier_id);
CREATE INDEX idx_prt_status ON purchase_returns(status);
CREATE INDEX idx_prt_date ON purchase_returns(return_date);
CREATE INDEX idx_prt_type ON purchase_returns(return_type);

COMMENT ON COLUMN purchase_returns.total_amount IS '退货总金额';
COMMENT ON COLUMN purchase_returns.refund_received IS '已收到退款';
COMMENT ON COLUMN purchase_returns.shipping_fee IS '退货运费';
COMMENT ON COLUMN purchase_returns.refund_voucher_id IS '退款凭证';

CREATE OR REPLACE TRIGGER trg_prt_updated_at
    BEFORE UPDATE ON purchase_returns
    FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

CREATE TABLE purchase_return_items (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    return_id NUMBER(19) NOT NULL CHECK (return_id >= 0),
    product_id NUMBER(19) NOT NULL CHECK (product_id >= 0),
    batch_id NUMBER(19) CHECK (batch_id IS NULL OR batch_id >= 0),
    return_qty NUMBER(10) NOT NULL,
    unit_price NUMBER(12,2) NOT NULL,
    amount NUMBER(18,2) GENERATED ALWAYS AS (return_qty * unit_price) STORED,
    reason VARCHAR2(200),
    CONSTRAINT fk_pri_return FOREIGN KEY (return_id) REFERENCES purchase_returns(id) ON DELETE CASCADE,
    CONSTRAINT fk_pri_product FOREIGN KEY (product_id) REFERENCES products(id),
    CONSTRAINT fk_pri_batch FOREIGN KEY (batch_id) REFERENCES product_batches(id) ON DELETE SET NULL
);

CREATE INDEX idx_pri_product ON purchase_return_items(product_id);
CREATE INDEX idx_pri_batch ON purchase_return_items(batch_id);

COMMENT ON COLUMN purchase_return_items.unit_price IS '退货单价(采购价)';

-- ============================================================
-- 6C. 报损/报废模块
-- ============================================================

CREATE TABLE damage_reports (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_no VARCHAR2(30) NOT NULL UNIQUE,
    warehouse_id NUMBER(19) NOT NULL CHECK (warehouse_id >= 0),
    report_type VARCHAR2(40) NOT NULL,
    report_date DATE NOT NULL,
    reported_by NUMBER(19) NOT NULL CHECK (reported_by >= 0),
    total_quantity NUMBER(10) DEFAULT 0,
    total_loss_amount NUMBER(18,2) DEFAULT 0.00,
    status VARCHAR2(40) DEFAULT 'draft',
    approved_by NUMBER(19) CHECK (approved_by IS NULL OR approved_by >= 0),
    approved_at TIMESTAMP(0),
    executed_by NUMBER(19) CHECK (executed_by IS NULL OR executed_by >= 0),
    executed_at TIMESTAMP(0),
    voucher_id NUMBER(19) CHECK (voucher_id IS NULL OR voucher_id >= 0),
    description CLOB,
    remark VARCHAR2(500),
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_dr_wh FOREIGN KEY (warehouse_id) REFERENCES warehouses(id),
    CONSTRAINT fk_dr_reported FOREIGN KEY (reported_by) REFERENCES employees(id),
    CONSTRAINT fk_dr_approved FOREIGN KEY (approved_by) REFERENCES employees(id),
    CONSTRAINT fk_dr_executed FOREIGN KEY (executed_by) REFERENCES employees(id)
);

CREATE INDEX idx_dr_warehouse ON damage_reports(warehouse_id);
CREATE INDEX idx_dr_type ON damage_reports(report_type);
CREATE INDEX idx_dr_date ON damage_reports(report_date);
CREATE INDEX idx_dr_status ON damage_reports(status);

COMMENT ON COLUMN damage_reports.total_loss_amount IS '报损总金额(成本价)';
COMMENT ON COLUMN damage_reports.voucher_id IS '财务凭证';

CREATE OR REPLACE TRIGGER trg_dr_updated_at
    BEFORE UPDATE ON damage_reports
    FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

CREATE TABLE damage_report_items (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id NUMBER(19) NOT NULL CHECK (report_id >= 0),
    product_id NUMBER(19) NOT NULL CHECK (product_id >= 0),
    batch_id NUMBER(19) CHECK (batch_id IS NULL OR batch_id >= 0),
    quantity NUMBER(10) NOT NULL,
    unit_cost NUMBER(12,2) NOT NULL,
    loss_amount NUMBER(18,2) GENERATED ALWAYS AS (quantity * unit_cost) STORED,
    reason VARCHAR2(200),
    CONSTRAINT fk_dri_report FOREIGN KEY (report_id) REFERENCES damage_reports(id) ON DELETE CASCADE,
    CONSTRAINT fk_dri_product FOREIGN KEY (product_id) REFERENCES products(id),
    CONSTRAINT fk_dri_batch FOREIGN KEY (batch_id) REFERENCES product_batches(id) ON DELETE SET NULL
);

CREATE INDEX idx_dri_product ON damage_report_items(product_id);
CREATE INDEX idx_dri_batch ON damage_report_items(batch_id);

COMMENT ON COLUMN damage_report_items.unit_cost IS '单位成本';

-- ============================================================
-- 7. 财务模块
-- ============================================================

-- 财务账户
CREATE TABLE accounts (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR2(20) NOT NULL UNIQUE,
    parent_id NUMBER(19) CHECK (parent_id IS NULL OR parent_id >= 0),
    name VARCHAR2(100) NOT NULL,
    account_type VARCHAR2(40) NOT NULL,
    balance_direction VARCHAR2(10) NOT NULL,
    is_cash NUMBER(1) DEFAULT 0,
    is_bank NUMBER(1) DEFAULT 0,
    bank_name VARCHAR2(100),
    bank_account VARCHAR2(50),
    current_balance NUMBER(18,2) DEFAULT 0.00,
    status VARCHAR2(40) DEFAULT 'active',
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_acct_parent FOREIGN KEY (parent_id) REFERENCES accounts(id) ON DELETE SET NULL
);

CREATE INDEX idx_acct_parent ON accounts(parent_id);
CREATE INDEX idx_acct_type ON accounts(account_type);

COMMENT ON COLUMN accounts.code IS '科目编码';
COMMENT ON COLUMN accounts.balance_direction IS '余额方向';
COMMENT ON COLUMN accounts.is_cash IS '是否现金科目';
COMMENT ON COLUMN accounts.is_bank IS '是否银行科目';

-- 财务凭证
CREATE TABLE vouchers (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voucher_no VARCHAR2(30) NOT NULL UNIQUE,
    voucher_date DATE NOT NULL,
    voucher_type VARCHAR2(40) NOT NULL,
    reference_type VARCHAR2(50),
    reference_id NUMBER(19),
    total_debit NUMBER(18,2) DEFAULT 0.00,
    total_credit NUMBER(18,2) DEFAULT 0.00,
    prepared_by NUMBER(19) NOT NULL CHECK (prepared_by >= 0),
    reviewed_by NUMBER(19) CHECK (reviewed_by IS NULL OR reviewed_by >= 0),
    posted_by NUMBER(19) CHECK (posted_by IS NULL OR posted_by >= 0),
    status VARCHAR2(40) DEFAULT 'draft',
    summary VARCHAR2(500),
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_v_prepared FOREIGN KEY (prepared_by) REFERENCES employees(id),
    CONSTRAINT fk_v_reviewed FOREIGN KEY (reviewed_by) REFERENCES employees(id),
    CONSTRAINT fk_v_posted FOREIGN KEY (posted_by) REFERENCES employees(id)
);

CREATE INDEX idx_v_date ON vouchers(voucher_date);
CREATE INDEX idx_v_type ON vouchers(voucher_type);
CREATE INDEX idx_v_reference ON vouchers(reference_type, reference_id);
CREATE INDEX idx_v_status ON vouchers(status);

CREATE OR REPLACE TRIGGER trg_v_updated_at
    BEFORE UPDATE ON vouchers
    FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

CREATE TABLE voucher_items (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voucher_id NUMBER(19) NOT NULL CHECK (voucher_id >= 0),
    account_id NUMBER(19) NOT NULL CHECK (account_id >= 0),
    line_no NUMBER(10) NOT NULL,
    direction VARCHAR2(10) NOT NULL,
    amount NUMBER(18,2) NOT NULL,
    summary VARCHAR2(500),
    CONSTRAINT fk_vi_voucher FOREIGN KEY (voucher_id) REFERENCES vouchers(id) ON DELETE CASCADE,
    CONSTRAINT fk_vi_account FOREIGN KEY (account_id) REFERENCES accounts(id)
);

CREATE INDEX idx_vi_voucher ON voucher_items(voucher_id);
CREATE INDEX idx_vi_account ON voucher_items(account_id);

-- 出纳日记账
CREATE TABLE cashier_journals (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    journal_no VARCHAR2(30) NOT NULL UNIQUE,
    journal_date DATE NOT NULL,
    account_id NUMBER(19) NOT NULL CHECK (account_id >= 0),
    cashier_id NUMBER(19) NOT NULL CHECK (cashier_id >= 0),
    journal_type VARCHAR2(40) NOT NULL,
    amount NUMBER(18,2) NOT NULL,
    counterparty VARCHAR2(200),
    reference_type VARCHAR2(50),
    reference_id NUMBER(19),
    voucher_id NUMBER(19) CHECK (voucher_id IS NULL OR voucher_id >= 0),
    bank_account VARCHAR2(50),
    check_no VARCHAR2(50),
    status VARCHAR2(40) DEFAULT 'pending',
    remark VARCHAR2(500),
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_cj_account FOREIGN KEY (account_id) REFERENCES accounts(id),
    CONSTRAINT fk_cj_cashier FOREIGN KEY (cashier_id) REFERENCES employees(id),
    CONSTRAINT fk_cj_voucher FOREIGN KEY (voucher_id) REFERENCES vouchers(id) ON DELETE SET NULL
);

CREATE INDEX idx_cj_date ON cashier_journals(journal_date);
CREATE INDEX idx_cj_account ON cashier_journals(account_id);
CREATE INDEX idx_cj_cashier ON cashier_journals(cashier_id);
CREATE INDEX idx_cj_status ON cashier_journals(status);
CREATE INDEX idx_cj_voucher ON cashier_journals(voucher_id);

COMMENT ON COLUMN cashier_journals.counterparty IS '对方单位/个人';

-- 工资发放表
CREATE TABLE salary_payments (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_no VARCHAR2(30) NOT NULL UNIQUE,
    employee_id NUMBER(19) NOT NULL CHECK (employee_id >= 0),
    payment_date DATE NOT NULL,
    salary_month VARCHAR2(7) NOT NULL,
    base_salary NUMBER(12,2) NOT NULL,
    overtime_pay NUMBER(12,2) DEFAULT 0.00,
    bonus NUMBER(12,2) DEFAULT 0.00,
    deduction NUMBER(12,2) DEFAULT 0.00,
    social_security_personal NUMBER(12,2) DEFAULT 0.00,
    housing_fund_personal NUMBER(12,2) DEFAULT 0.00,
    income_tax NUMBER(12,2) DEFAULT 0.00,
    net_pay NUMBER(12,2) NOT NULL,
    social_security_company NUMBER(12,2) DEFAULT 0.00,
    housing_fund_company NUMBER(12,2) DEFAULT 0.00,
    payment_method VARCHAR2(40) DEFAULT 'bank_transfer',
    status VARCHAR2(40) DEFAULT 'pending',
    paid_at TIMESTAMP(0),
    voucher_id NUMBER(19) CHECK (voucher_id IS NULL OR voucher_id >= 0),
    remark VARCHAR2(200),
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (employee_id, salary_month),
    CONSTRAINT fk_sp_emp FOREIGN KEY (employee_id) REFERENCES employees(id),
    CONSTRAINT fk_sp_voucher FOREIGN KEY (voucher_id) REFERENCES vouchers(id) ON DELETE SET NULL
);

CREATE INDEX idx_sp_date ON salary_payments(payment_date);
CREATE INDEX idx_sp_month ON salary_payments(salary_month);
CREATE INDEX idx_sp_status ON salary_payments(status);

COMMENT ON COLUMN salary_payments.salary_month IS 'YYYY-MM';
COMMENT ON COLUMN salary_payments.deduction IS '扣款';
COMMENT ON COLUMN salary_payments.social_security_personal IS '个人社保';
COMMENT ON COLUMN salary_payments.housing_fund_personal IS '个人公积金';
COMMENT ON COLUMN salary_payments.income_tax IS '个税';
COMMENT ON COLUMN salary_payments.net_pay IS '实发工资';
COMMENT ON COLUMN salary_payments.social_security_company IS '公司社保';
COMMENT ON COLUMN salary_payments.housing_fund_company IS '公司公积金';

-- 对账表
CREATE TABLE reconciliations (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recon_no VARCHAR2(30) NOT NULL UNIQUE,
    account_id NUMBER(19) NOT NULL CHECK (account_id >= 0),
    recon_date DATE NOT NULL,
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    book_balance NUMBER(18,2) NOT NULL,
    bank_balance NUMBER(18,2) DEFAULT 0.00,
    difference NUMBER(18,2) DEFAULT 0.00,
    unreconciled_income NUMBER(18,2) DEFAULT 0.00,
    unreconciled_expense NUMBER(18,2) DEFAULT 0.00,
    adjusted_balance NUMBER(18,2) DEFAULT 0.00,
    prepared_by NUMBER(19) NOT NULL CHECK (prepared_by >= 0),
    reviewed_by NUMBER(19) CHECK (reviewed_by IS NULL OR reviewed_by >= 0),
    status VARCHAR2(40) DEFAULT 'draft',
    remark VARCHAR2(500),
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_recon_account FOREIGN KEY (account_id) REFERENCES accounts(id),
    CONSTRAINT fk_recon_prepared FOREIGN KEY (prepared_by) REFERENCES employees(id),
    CONSTRAINT fk_recon_reviewed FOREIGN KEY (reviewed_by) REFERENCES employees(id)
);

CREATE INDEX idx_recon_account ON reconciliations(account_id);
CREATE INDEX idx_recon_period ON reconciliations(period_start, period_end);
CREATE INDEX idx_recon_status ON reconciliations(status);

COMMENT ON COLUMN reconciliations.book_balance IS '账面余额';
COMMENT ON COLUMN reconciliations.bank_balance IS '银行余额';
COMMENT ON COLUMN reconciliations.difference IS '差异';
COMMENT ON COLUMN reconciliations.unreconciled_income IS '未达账-收入';
COMMENT ON COLUMN reconciliations.unreconciled_expense IS '未达账-支出';
COMMENT ON COLUMN reconciliations.adjusted_balance IS '调整后余额';

CREATE OR REPLACE TRIGGER trg_recon_updated_at
    BEFORE UPDATE ON reconciliations
    FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- 对账明细
CREATE TABLE reconciliation_items (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reconciliation_id NUMBER(19) NOT NULL CHECK (reconciliation_id >= 0),
    journal_id NUMBER(19) CHECK (journal_id IS NULL OR journal_id >= 0),
    transaction_date DATE NOT NULL,
    description VARCHAR2(500) NOT NULL,
    debit_amount NUMBER(18,2) DEFAULT 0.00,
    credit_amount NUMBER(18,2) DEFAULT 0.00,
    is_matched NUMBER(1) DEFAULT 0,
    matched_item_id NUMBER(19) CHECK (matched_item_id IS NULL OR matched_item_id >= 0),
    difference_reason VARCHAR2(500),
    CONSTRAINT fk_ri_recon FOREIGN KEY (reconciliation_id) REFERENCES reconciliations(id) ON DELETE CASCADE
);

CREATE INDEX idx_ri_recon ON reconciliation_items(reconciliation_id);
CREATE INDEX idx_ri_journal ON reconciliation_items(journal_id);

-- 结算单
CREATE TABLE settlements (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    settlement_no VARCHAR2(30) NOT NULL UNIQUE,
    settlement_type VARCHAR2(40) NOT NULL,
    party_id NUMBER(19) NOT NULL CHECK (party_id >= 0),
    settlement_date DATE NOT NULL,
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    total_amount NUMBER(18,2) NOT NULL,
    settled_amount NUMBER(18,2) DEFAULT 0.00,
    unpaid_amount NUMBER(18,2) GENERATED ALWAYS AS (total_amount - settled_amount) STORED,
    payment_due_date DATE,
    settlement_payment_method VARCHAR2(40) DEFAULT 'bank_transfer',
    status VARCHAR2(40) DEFAULT 'pending',
    voucher_id NUMBER(19) CHECK (voucher_id IS NULL OR voucher_id >= 0),
    prepared_by NUMBER(19) NOT NULL CHECK (prepared_by >= 0),
    approved_by NUMBER(19) CHECK (approved_by IS NULL OR approved_by >= 0),
    remark VARCHAR2(500),
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_settle_prepared FOREIGN KEY (prepared_by) REFERENCES employees(id),
    CONSTRAINT fk_settle_approved FOREIGN KEY (approved_by) REFERENCES employees(id)
);

CREATE INDEX idx_settle_party ON settlements(settlement_type, party_id);
CREATE INDEX idx_settle_date ON settlements(settlement_date);
CREATE INDEX idx_settle_status ON settlements(status);
CREATE INDEX idx_settle_due_date ON settlements(payment_due_date);

COMMENT ON COLUMN settlements.party_id IS '对方ID（供应商/客户/员工等）';

CREATE OR REPLACE TRIGGER trg_settle_updated_at
    BEFORE UPDATE ON settlements
    FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- 结算明细
CREATE TABLE settlement_items (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    settlement_id NUMBER(19) NOT NULL CHECK (settlement_id >= 0),
    reference_type VARCHAR2(50) NOT NULL,
    reference_id NUMBER(19) NOT NULL,
    amount NUMBER(18,2) NOT NULL,
    settled_amount NUMBER(18,2) DEFAULT 0.00,
    remark VARCHAR2(200),
    CONSTRAINT fk_si_settlement FOREIGN KEY (settlement_id) REFERENCES settlements(id) ON DELETE CASCADE
);

CREATE INDEX idx_si_settlement ON settlement_items(settlement_id);
CREATE INDEX idx_si_reference ON settlement_items(reference_type, reference_id);

COMMENT ON COLUMN settlement_items.reference_type IS '关联单据类型';

-- 延迟添加 sales_returns 和 purchase_returns 对 vouchers 的外键
ALTER TABLE sales_returns ADD CONSTRAINT fk_sr_refund_voucher
    FOREIGN KEY (refund_voucher_id) REFERENCES vouchers(id) ON DELETE SET NULL;

ALTER TABLE purchase_returns ADD CONSTRAINT fk_prt_voucher
    FOREIGN KEY (refund_voucher_id) REFERENCES vouchers(id) ON DELETE SET NULL;

ALTER TABLE damage_reports ADD CONSTRAINT fk_dr_voucher
    FOREIGN KEY (voucher_id) REFERENCES vouchers(id) ON DELETE SET NULL;

ALTER TABLE settlements ADD CONSTRAINT fk_settle_voucher
    FOREIGN KEY (voucher_id) REFERENCES vouchers(id) ON DELETE SET NULL;