-- ============================================================
-- Oracle 21c 语法样例
-- 说明: 覆盖 SQL_MACRO 表达式宏和普通 DML。
-- ============================================================

CREATE TABLE oracle_21_sales_demo (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku VARCHAR2(50) NOT NULL,
    sales_amount NUMBER(18,2) NOT NULL,
    cost_amount NUMBER(18,2) NOT NULL
);

CREATE OR REPLACE FUNCTION oracle_21_margin_expr(p_sales NUMBER, p_cost NUMBER)
RETURN VARCHAR2 SQL_MACRO(SCALAR) IS
BEGIN
    RETURN 'p_sales - p_cost';
END;
/

INSERT INTO oracle_21_sales_demo (sku, sales_amount, cost_amount) VALUES ('ORA21-DEMO-001', 1200.00, 830.00);

SELECT sku, oracle_21_margin_expr(sales_amount, cost_amount) AS gross_margin
FROM oracle_21_sales_demo;
