-- ============================================================
-- Oracle 26ai 语法样例
-- 说明: 覆盖 VECTOR 数据类型和向量列建表。
-- ============================================================

CREATE TABLE oracle_26ai_product_vector_demo (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku VARCHAR2(50) NOT NULL,
    description VARCHAR2(200),
    embedding VECTOR(3, FLOAT32)
);

INSERT INTO oracle_26ai_product_vector_demo (sku, description) VALUES ('ORA26-DEMO-001', 'women jacket east region sample');

SELECT sku, description
FROM oracle_26ai_product_vector_demo
ORDER BY id
FETCH FIRST 5 ROWS ONLY;
