-- PostgreSQL support-table DDL translated from MySQL basic-correctness case_01 SHOW CREATE TABLE.
-- MySQL storage, charset, collation, AUTO_INCREMENT and COMMENT clauses are converted or omitted.
-- This file is a parser correctness fixture input, not a production migration script.

-- relation-detector-fixture-table: public.GRAPH_CHECKPOINT
CREATE TABLE graph_checkpoint (
  checkpoint_id VARCHAR(36) NOT NULL,
  thread_id VARCHAR(36) NOT NULL,
  node_id VARCHAR(255) DEFAULT NULL,
  next_node_id VARCHAR(255) DEFAULT NULL,
  state_data JSONB NOT NULL,
  saved_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (checkpoint_id),
  CONSTRAINT graph_fk_thread FOREIGN KEY (thread_id) REFERENCES graph_thread (thread_id) ON DELETE CASCADE ON UPDATE RESTRICT
);
CREATE INDEX graph_fk_thread ON graph_checkpoint (thread_id);

-- relation-detector-fixture-table: public.GRAPH_THREAD
CREATE TABLE graph_thread (
  thread_id VARCHAR(36) NOT NULL,
  thread_name VARCHAR(255) DEFAULT NULL,
  is_released BOOLEAN NOT NULL DEFAULT false,
  PRIMARY KEY (thread_id),
  CONSTRAINT idx_graph_thread_name_released UNIQUE (thread_name, is_released)
);

-- relation-detector-fixture-table: public.biz_bill_item_fact
CREATE TABLE biz_bill_item_fact (
  factid BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  tenantid BIGINT NOT NULL,
  sourceorderid BIGINT NOT NULL,
  sourceorderno VARCHAR(50) DEFAULT NULL,
  sourceorderitemid BIGINT NOT NULL,
  purchaseorderlinkno VARCHAR(50) DEFAULT NULL,
  purchaseapplylinkno VARCHAR(50) DEFAULT NULL,
  sourcetype VARCHAR(32) DEFAULT NULL,
  sourcesubtype VARCHAR(32) DEFAULT NULL,
  businessdate TIMESTAMP DEFAULT NULL,
  creator BIGINT DEFAULT NULL,
  supplierid BIGINT DEFAULT NULL,
  customerid BIGINT DEFAULT NULL,
  memberid BIGINT DEFAULT NULL,
  storeid BIGINT DEFAULT NULL,
  productid BIGINT DEFAULT NULL,
  warehouseid BIGINT DEFAULT NULL,
  outwarehouseid BIGINT DEFAULT NULL,
  inwarehouseid BIGINT DEFAULT NULL,
  quantity NUMERIC(24,6) DEFAULT NULL,
  amount NUMERIC(24,6) DEFAULT NULL,
  inventorydirection SMALLINT DEFAULT NULL,
  salesdirection SMALLINT DEFAULT NULL,
  createdat TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedat TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (factid),
  CONSTRAINT uk_bill_item_fact_source_item UNIQUE (tenantid, sourceorderitemid),
  CONSTRAINT uk_tenant_item UNIQUE (tenantid, sourceorderitemid)
);
CREATE INDEX idx_bill_item_fact_time ON biz_bill_item_fact (tenantid, businessdate);
CREATE INDEX idx_bill_item_fact_type_time ON biz_bill_item_fact (tenantid, sourcetype, sourcesubtype, businessdate);
CREATE INDEX idx_bill_item_fact_store_time ON biz_bill_item_fact (tenantid, storeid, businessdate);
CREATE INDEX idx_bill_item_fact_product_time ON biz_bill_item_fact (tenantid, productid, businessdate);
CREATE INDEX idx_bill_item_fact_warehouse_time ON biz_bill_item_fact (tenantid, warehouseid, businessdate);
CREATE INDEX idx_bif_purchaseorderlinkno ON biz_bill_item_fact (tenantid, sourcesubtype, purchaseorderlinkno);
CREATE INDEX idx_bif_purchaseapplylinkno ON biz_bill_item_fact (tenantid, sourcesubtype, purchaseapplylinkno);

-- relation-detector-fixture-table: public.biz_sync_progress
CREATE TABLE biz_sync_progress (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  jobid BIGINT NOT NULL,
  tenantid BIGINT DEFAULT NULL,
  batchfromid BIGINT DEFAULT NULL,
  batchtoid BIGINT DEFAULT NULL,
  affectedrows INTEGER DEFAULT NULL,
  donerows BIGINT DEFAULT NULL,
  totalrows BIGINT DEFAULT NULL,
  pct NUMERIC(8,2) DEFAULT NULL,
  status VARCHAR(20) NOT NULL,
  msg VARCHAR(255) DEFAULT NULL,
  createdat TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);
CREATE INDEX idx_job_time ON biz_sync_progress (jobid, createdat);

-- relation-detector-fixture-table: public.chat_message
CREATE TABLE chat_message (
  id BIGINT NOT NULL,
  session_id VARCHAR(64) NOT NULL,
  role VARCHAR(16) NOT NULL,
  content TEXT,
  result_data TEXT,
  status VARCHAR(16) DEFAULT 'done',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted BOOLEAN NOT NULL DEFAULT false,
  PRIMARY KEY (id)
);
CREATE INDEX idx_session_id ON chat_message (session_id);
CREATE INDEX idx_created_at ON chat_message (created_at);

-- relation-detector-fixture-table: public.chat_session
CREATE TABLE chat_session (
  id VARCHAR(64) NOT NULL,
  title VARCHAR(256) NOT NULL DEFAULT '新对话',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted BOOLEAN NOT NULL DEFAULT false,
  PRIMARY KEY (id)
);
CREATE INDEX idx_updated_at ON chat_session (updated_at);

-- relation-detector-fixture-table: public.fe_agent_message
CREATE TABLE fe_agent_message (
  id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  sessionid INTEGER NOT NULL,
  role VARCHAR(64) NOT NULL,
  content TEXT NOT NULL,
  metadata JSONB DEFAULT NULL,
  createdat TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  CONSTRAINT fk_fe_agent_message_session FOREIGN KEY (sessionid) REFERENCES fe_agent_session (id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX idx_fe_agent_message_sessionid ON fe_agent_message (sessionid);

-- relation-detector-fixture-table: public.fe_agent_session
CREATE TABLE fe_agent_session (
  id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  sessionid VARCHAR(100) NOT NULL,
  userid INTEGER DEFAULT NULL,
  title VARCHAR(200) DEFAULT NULL,
  status VARCHAR(64) NOT NULL DEFAULT 'active',
  metadata JSONB DEFAULT NULL,
  createdat TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updatedat TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  CONSTRAINT uq_fe_agent_session_sessionid UNIQUE (sessionid)
);
CREATE INDEX idx_fe_agent_session_userid ON fe_agent_session (userid);

-- relation-detector-fixture-table: public.fe_typeorm_migrations
CREATE TABLE fe_typeorm_migrations (
  id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  timestamp BIGINT NOT NULL,
  name VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
);

-- relation-detector-fixture-table: public.jsh_account
CREATE TABLE jsh_account (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(50) DEFAULT NULL,
  serial_no VARCHAR(50) DEFAULT NULL,
  initial_amount NUMERIC(24,6) DEFAULT NULL,
  current_amount NUMERIC(24,6) DEFAULT NULL,
  remark VARCHAR(100) DEFAULT NULL,
  enabled BOOLEAN DEFAULT NULL,
  sort VARCHAR(10) DEFAULT NULL,
  is_default BOOLEAN DEFAULT NULL,
  tenant_id BIGINT DEFAULT NULL,
  delete_flag VARCHAR(1) DEFAULT '0',
  PRIMARY KEY (id)
);
CREATE INDEX tenant_id ON jsh_account (tenant_id);

-- relation-detector-fixture-table: public.jsh_account_head
CREATE TABLE jsh_account_head (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  type VARCHAR(50) DEFAULT NULL,
  organ_id BIGINT DEFAULT NULL,
  hands_person_id BIGINT DEFAULT NULL,
  creator BIGINT DEFAULT NULL,
  change_amount NUMERIC(24,6) DEFAULT NULL,
  discount_money NUMERIC(24,6) DEFAULT NULL,
  total_price NUMERIC(24,6) DEFAULT NULL,
  account_id BIGINT DEFAULT NULL,
  bill_no VARCHAR(50) DEFAULT NULL,
  bill_time TIMESTAMP DEFAULT NULL,
  remark VARCHAR(1000) DEFAULT NULL,
  file_name VARCHAR(500) DEFAULT NULL,
  status VARCHAR(1) DEFAULT NULL,
  source VARCHAR(1) DEFAULT '0',
  tenant_id BIGINT DEFAULT NULL,
  delete_flag VARCHAR(1) DEFAULT '0',
  PRIMARY KEY (id)
);
CREATE INDEX fk9f4c0d8db610fc06 ON jsh_account_head (organ_id);
CREATE INDEX fk9f4c0d8daae50527 ON jsh_account_head (account_id);
CREATE INDEX fk9f4c0d8dc4170b37 ON jsh_account_head (hands_person_id);
CREATE INDEX bill_no ON jsh_account_head (bill_no);
CREATE INDEX tenant_id ON jsh_account_head (tenant_id);

-- relation-detector-fixture-table: public.jsh_account_item
CREATE TABLE jsh_account_item (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  header_id BIGINT NOT NULL,
  account_id BIGINT DEFAULT NULL,
  in_out_item_id BIGINT DEFAULT NULL,
  bill_id BIGINT DEFAULT NULL,
  need_debt NUMERIC(24,6) DEFAULT NULL,
  finish_debt NUMERIC(24,6) DEFAULT NULL,
  each_amount NUMERIC(24,6) DEFAULT NULL,
  remark VARCHAR(500) DEFAULT NULL,
  tenant_id BIGINT DEFAULT NULL,
  delete_flag VARCHAR(1) DEFAULT '0',
  PRIMARY KEY (id)
);
CREATE INDEX fk9f4cbac0aae50527 ON jsh_account_item (account_id);
CREATE INDEX fk9f4cbac0c5fe6007 ON jsh_account_item (header_id);
CREATE INDEX fk9f4cbac0d203edc5 ON jsh_account_item (in_out_item_id);
CREATE INDEX bill_id ON jsh_account_item (bill_id);
CREATE INDEX tenant_id ON jsh_account_item (tenant_id);

-- relation-detector-fixture-table: public.jsh_depot
CREATE TABLE jsh_depot (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(20) DEFAULT NULL,
  address VARCHAR(50) DEFAULT NULL,
  warehousing NUMERIC(24,6) DEFAULT NULL,
  truckage NUMERIC(24,6) DEFAULT NULL,
  type INTEGER DEFAULT NULL,
  sort VARCHAR(10) DEFAULT NULL,
  remark VARCHAR(100) DEFAULT NULL,
  principal BIGINT DEFAULT NULL,
  enabled BOOLEAN DEFAULT NULL,
  tenant_id BIGINT DEFAULT NULL,
  delete_flag VARCHAR(1) DEFAULT '0',
  is_default BOOLEAN DEFAULT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX tenant_id ON jsh_depot (tenant_id);

-- relation-detector-fixture-table: public.jsh_depot_head
CREATE TABLE jsh_depot_head (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  type VARCHAR(50) DEFAULT NULL,
  sub_type VARCHAR(50) DEFAULT NULL,
  default_number VARCHAR(50) DEFAULT NULL,
  number VARCHAR(50) DEFAULT NULL,
  create_time TIMESTAMP DEFAULT NULL,
  oper_time TIMESTAMP DEFAULT NULL,
  organ_id BIGINT DEFAULT NULL,
  creator BIGINT DEFAULT NULL,
  account_id BIGINT DEFAULT NULL,
  change_amount NUMERIC(24,6) DEFAULT NULL,
  back_amount NUMERIC(24,6) DEFAULT NULL,
  total_price NUMERIC(24,6) DEFAULT NULL,
  pay_type VARCHAR(50) DEFAULT NULL,
  bill_type VARCHAR(50) DEFAULT NULL,
  remark VARCHAR(1000) DEFAULT NULL,
  file_name VARCHAR(1000) DEFAULT NULL,
  sales_man VARCHAR(50) DEFAULT NULL,
  account_id_list VARCHAR(50) DEFAULT NULL,
  account_money_list VARCHAR(200) DEFAULT NULL,
  discount NUMERIC(24,6) DEFAULT NULL,
  discount_money NUMERIC(24,6) DEFAULT NULL,
  discount_last_money NUMERIC(24,6) DEFAULT NULL,
  other_money NUMERIC(24,6) DEFAULT NULL,
  deposit NUMERIC(24,6) DEFAULT NULL,
  status VARCHAR(1) DEFAULT NULL,
  purchase_status VARCHAR(1) DEFAULT NULL,
  source VARCHAR(1) DEFAULT '0',
  link_number VARCHAR(50) DEFAULT NULL,
  link_apply VARCHAR(50) DEFAULT NULL,
  tenant_id BIGINT DEFAULT NULL,
  delete_flag VARCHAR(1) DEFAULT '0',
  PRIMARY KEY (id)
);
CREATE INDEX fk2a80f214b610fc06 ON jsh_depot_head (organ_id);
CREATE INDEX fk2a80f214aae50527 ON jsh_depot_head (account_id);
CREATE INDEX number ON jsh_depot_head (number);
CREATE INDEX link_number ON jsh_depot_head (link_number);
CREATE INDEX creator ON jsh_depot_head (creator);
CREATE INDEX tenant_id ON jsh_depot_head (tenant_id);
CREATE INDEX idx_tenant_subtype_status_id ON jsh_depot_head (tenant_id, sub_type, status, delete_flag, id);
CREATE INDEX idx_tenant_type_subtype_id ON jsh_depot_head (tenant_id, type, sub_type, id, number);

-- relation-detector-fixture-table: public.jsh_depot_item
CREATE TABLE jsh_depot_item (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  header_id BIGINT NOT NULL,
  material_id BIGINT NOT NULL,
  material_extend_id BIGINT DEFAULT NULL,
  material_unit VARCHAR(20) DEFAULT NULL,
  sku VARCHAR(50) DEFAULT NULL,
  oper_number NUMERIC(24,6) DEFAULT NULL,
  basic_number NUMERIC(24,6) DEFAULT NULL,
  unit_price NUMERIC(24,6) DEFAULT NULL,
  purchase_unit_price NUMERIC(24,6) DEFAULT NULL,
  tax_unit_price NUMERIC(24,6) DEFAULT NULL,
  all_price NUMERIC(24,6) DEFAULT NULL,
  remark VARCHAR(500) DEFAULT NULL,
  depot_id BIGINT DEFAULT NULL,
  another_depot_id BIGINT DEFAULT NULL,
  tax_rate NUMERIC(24,6) DEFAULT NULL,
  tax_money NUMERIC(24,6) DEFAULT NULL,
  tax_last_money NUMERIC(24,6) DEFAULT NULL,
  material_type VARCHAR(20) DEFAULT NULL,
  sn_list VARCHAR(2000) DEFAULT NULL,
  batch_number VARCHAR(100) DEFAULT NULL,
  expiration_date TIMESTAMP DEFAULT NULL,
  link_id BIGINT DEFAULT NULL,
  tenant_id BIGINT DEFAULT NULL,
  delete_flag VARCHAR(1) DEFAULT '0',
  PRIMARY KEY (id)
);
CREATE INDEX fk2a819f475d61ccf7 ON jsh_depot_item (material_id);
CREATE INDEX fk2a819f474bb6190e ON jsh_depot_item (header_id);
CREATE INDEX fk2a819f479485b3f5 ON jsh_depot_item (depot_id);
CREATE INDEX fk2a819f47729f5392 ON jsh_depot_item (another_depot_id);
CREATE INDEX material_extend_id ON jsh_depot_item (material_extend_id);
CREATE INDEX tenant_id ON jsh_depot_item (tenant_id);

-- relation-detector-fixture-table: public.jsh_function
CREATE TABLE jsh_function (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  number VARCHAR(50) DEFAULT NULL,
  name VARCHAR(50) DEFAULT NULL,
  parent_number VARCHAR(50) DEFAULT NULL,
  url VARCHAR(100) DEFAULT NULL,
  component VARCHAR(100) DEFAULT NULL,
  state BOOLEAN DEFAULT NULL,
  sort VARCHAR(50) DEFAULT NULL,
  enabled BOOLEAN DEFAULT NULL,
  type VARCHAR(50) DEFAULT NULL,
  push_btn VARCHAR(50) DEFAULT NULL,
  icon VARCHAR(50) DEFAULT NULL,
  delete_flag VARCHAR(1) DEFAULT '0',
  PRIMARY KEY (id),
  CONSTRAINT url UNIQUE (url)
);

-- relation-detector-fixture-table: public.jsh_in_out_item
CREATE TABLE jsh_in_out_item (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(50) DEFAULT NULL,
  type VARCHAR(20) DEFAULT NULL,
  remark VARCHAR(100) DEFAULT NULL,
  enabled BOOLEAN DEFAULT NULL,
  sort VARCHAR(10) DEFAULT NULL,
  tenant_id BIGINT DEFAULT NULL,
  delete_flag VARCHAR(1) DEFAULT '0',
  PRIMARY KEY (id)
);
CREATE INDEX tenant_id ON jsh_in_out_item (tenant_id);

-- relation-detector-fixture-table: public.jsh_location_gps
CREATE TABLE jsh_location_gps (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  link_id BIGINT NOT NULL,
  link_type VARCHAR(30) NOT NULL,
  val_supplier_id BIGINT GENERATED ALWAYS AS (
    CASE WHEN link_type = 'SUPPLIER' THEN link_id ELSE NULL END
  ) STORED,
  val_org_id BIGINT GENERATED ALWAYS AS (
    CASE
      WHEN link_type IN ('STORE', 'HEADQUARTER', 'REGION', 'CITY', 'DISTRICT') THEN link_id
      ELSE NULL
    END
  ) STORED,
  val_depot_id BIGINT GENERATED ALWAYS AS (
    CASE WHEN link_type = 'DEPOT' THEN link_id ELSE NULL END
  ) STORED,
  link_code VARCHAR(50) DEFAULT NULL,
  link_name VARCHAR(255) DEFAULT NULL,
  longitude NUMERIC(10,7) DEFAULT NULL,
  latitude NUMERIC(10,7) DEFAULT NULL,
  province VARCHAR(50) DEFAULT NULL,
  city VARCHAR(50) DEFAULT NULL,
  district VARCHAR(50) DEFAULT NULL,
  address VARCHAR(500) DEFAULT NULL,
  tenant_id BIGINT DEFAULT NULL,
  delete_flag VARCHAR(1) DEFAULT '0',
  PRIMARY KEY (id),
  CONSTRAINT uk_supplier_only UNIQUE (val_supplier_id),
  CONSTRAINT uk_org_only UNIQUE (val_org_id),
  CONSTRAINT uk_depot_only UNIQUE (val_depot_id)
);
CREATE INDEX idx_tenant_id ON jsh_location_gps (tenant_id);

-- relation-detector-fixture-table: public.jsh_log
CREATE TABLE jsh_log (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT DEFAULT NULL,
  operation VARCHAR(500) DEFAULT NULL,
  client_ip VARCHAR(200) DEFAULT NULL,
  create_time TIMESTAMP DEFAULT NULL,
  status SMALLINT DEFAULT NULL,
  content VARCHAR(5000) DEFAULT NULL,
  tenant_id BIGINT DEFAULT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX fkf2696aa13e226853 ON jsh_log (user_id);
CREATE INDEX create_time ON jsh_log (create_time);
CREATE INDEX tenant_id ON jsh_log (tenant_id);

-- relation-detector-fixture-table: public.jsh_material
CREATE TABLE jsh_material (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  category_id BIGINT DEFAULT NULL,
  name VARCHAR(100) DEFAULT NULL,
  mfrs VARCHAR(50) DEFAULT NULL,
  model VARCHAR(100) DEFAULT NULL,
  standard VARCHAR(100) DEFAULT NULL,
  brand VARCHAR(100) DEFAULT NULL,
  mnemonic VARCHAR(100) DEFAULT NULL,
  color VARCHAR(50) DEFAULT NULL,
  unit VARCHAR(50) DEFAULT NULL,
  remark VARCHAR(500) DEFAULT NULL,
  img_name VARCHAR(1000) DEFAULT NULL,
  unit_id BIGINT DEFAULT NULL,
  expiry_num INTEGER DEFAULT NULL,
  weight NUMERIC(24,6) DEFAULT NULL,
  enabled BOOLEAN DEFAULT NULL,
  other_field1 VARCHAR(500) DEFAULT NULL,
  other_field2 VARCHAR(500) DEFAULT NULL,
  other_field3 VARCHAR(500) DEFAULT NULL,
  enable_serial_number VARCHAR(1) DEFAULT '0',
  enable_batch_number VARCHAR(1) DEFAULT '0',
  position VARCHAR(100) DEFAULT NULL,
  attribute VARCHAR(1000) DEFAULT NULL,
  tenant_id BIGINT DEFAULT NULL,
  delete_flag VARCHAR(1) DEFAULT '0',
  PRIMARY KEY (id)
);
CREATE INDEX fk675951272ab6672c ON jsh_material (category_id);
CREATE INDEX unitid ON jsh_material (unit_id);
CREATE INDEX tenant_id ON jsh_material (tenant_id);

-- relation-detector-fixture-table: public.jsh_material_attribute
CREATE TABLE jsh_material_attribute (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  attribute_name VARCHAR(50) DEFAULT NULL,
  attribute_value VARCHAR(500) DEFAULT NULL,
  tenant_id BIGINT DEFAULT NULL,
  delete_flag VARCHAR(1) DEFAULT '0',
  PRIMARY KEY (id)
);
CREATE INDEX tenant_id ON jsh_material_attribute (tenant_id);

-- relation-detector-fixture-table: public.jsh_material_category
CREATE TABLE jsh_material_category (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(50) DEFAULT NULL,
  category_level SMALLINT DEFAULT NULL,
  parent_id BIGINT DEFAULT NULL,
  sort VARCHAR(10) DEFAULT NULL,
  serial_no VARCHAR(100) DEFAULT NULL,
  remark VARCHAR(1024) DEFAULT NULL,
  create_time TIMESTAMP DEFAULT NULL,
  update_time TIMESTAMP DEFAULT NULL,
  tenant_id BIGINT DEFAULT NULL,
  delete_flag VARCHAR(1) DEFAULT '0',
  PRIMARY KEY (id)
);
CREATE INDEX fk3ee7f725237a77d8 ON jsh_material_category (parent_id);
CREATE INDEX tenant_id ON jsh_material_category (tenant_id);

-- relation-detector-fixture-table: public.jsh_material_current_stock
CREATE TABLE jsh_material_current_stock (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  material_id BIGINT DEFAULT NULL,
  depot_id BIGINT DEFAULT NULL,
  current_number NUMERIC(24,6) DEFAULT NULL,
  current_unit_price NUMERIC(24,6) DEFAULT NULL,
  tenant_id BIGINT DEFAULT NULL,
  delete_flag VARCHAR(1) DEFAULT '0',
  PRIMARY KEY (id)
);
CREATE INDEX material_id ON jsh_material_current_stock (material_id);
CREATE INDEX depot_id ON jsh_material_current_stock (depot_id);
CREATE INDEX tenant_id ON jsh_material_current_stock (tenant_id);

-- relation-detector-fixture-table: public.jsh_material_extend
CREATE TABLE jsh_material_extend (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  material_id BIGINT DEFAULT NULL,
  bar_code VARCHAR(50) DEFAULT NULL,
  commodity_unit VARCHAR(50) DEFAULT NULL,
  sku VARCHAR(50) DEFAULT NULL,
  purchase_decimal NUMERIC(24,6) DEFAULT NULL,
  commodity_decimal NUMERIC(24,6) DEFAULT NULL,
  wholesale_decimal NUMERIC(24,6) DEFAULT NULL,
  low_decimal NUMERIC(24,6) DEFAULT NULL,
  default_flag VARCHAR(1) DEFAULT '1',
  create_time TIMESTAMP DEFAULT NULL,
  create_serial VARCHAR(50) DEFAULT NULL,
  update_serial VARCHAR(50) DEFAULT NULL,
  update_time BIGINT DEFAULT NULL,
  tenant_id BIGINT DEFAULT NULL,
  delete_flag VARCHAR(1) DEFAULT '0',
  PRIMARY KEY (id)
);
CREATE INDEX material_id ON jsh_material_extend (material_id);
CREATE INDEX bar_code ON jsh_material_extend (bar_code);
CREATE INDEX tenant_id ON jsh_material_extend (tenant_id);

-- relation-detector-fixture-table: public.jsh_material_initial_stock
CREATE TABLE jsh_material_initial_stock (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  material_id BIGINT DEFAULT NULL,
  depot_id BIGINT DEFAULT NULL,
  number NUMERIC(24,6) DEFAULT NULL,
  low_safe_stock NUMERIC(24,6) DEFAULT NULL,
  high_safe_stock NUMERIC(24,6) DEFAULT NULL,
  tenant_id BIGINT DEFAULT NULL,
  delete_flag VARCHAR(1) DEFAULT '0',
  PRIMARY KEY (id)
);
CREATE INDEX material_id ON jsh_material_initial_stock (material_id);
CREATE INDEX depot_id ON jsh_material_initial_stock (depot_id);
CREATE INDEX tenant_id ON jsh_material_initial_stock (tenant_id);

-- relation-detector-fixture-table: public.jsh_material_property
CREATE TABLE jsh_material_property (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  native_name VARCHAR(50) DEFAULT NULL,
  enabled BOOLEAN DEFAULT NULL,
  sort VARCHAR(10) DEFAULT NULL,
  another_name VARCHAR(50) DEFAULT NULL,
  tenant_id BIGINT DEFAULT NULL,
  delete_flag VARCHAR(1) DEFAULT '0',
  PRIMARY KEY (id)
);

-- relation-detector-fixture-table: public.jsh_mock_batch_log
CREATE TABLE jsh_mock_batch_log (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  code INTEGER NOT NULL,
  message VARCHAR(255) DEFAULT '成功',
  new_id BIGINT DEFAULT NULL,
  number VARCHAR(50) DEFAULT NULL,
  create_time TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);
CREATE INDEX idx_code_message ON jsh_mock_batch_log (code, message);

-- relation-detector-fixture-table: public.jsh_mock_user_store_pool
CREATE TABLE jsh_mock_user_store_pool (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  tenant_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  org_id BIGINT NOT NULL,
  org_no VARCHAR(50) DEFAULT NULL,
  org_name VARCHAR(100) DEFAULT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX idx_tenant_pool_id ON jsh_mock_user_store_pool (tenant_id, id);

-- relation-detector-fixture-table: public.jsh_msg
CREATE TABLE jsh_msg (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  msg_title VARCHAR(100) DEFAULT NULL,
  msg_content VARCHAR(500) DEFAULT NULL,
  create_time TIMESTAMP DEFAULT NULL,
  type VARCHAR(20) DEFAULT NULL,
  user_id BIGINT DEFAULT NULL,
  status VARCHAR(1) DEFAULT NULL,
  tenant_id BIGINT DEFAULT NULL,
  delete_flag VARCHAR(1) DEFAULT '0',
  PRIMARY KEY (id)
);
CREATE INDEX tenant_id ON jsh_msg (tenant_id);

-- relation-detector-fixture-table: public.jsh_orga_user_rel
CREATE TABLE jsh_orga_user_rel (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  orga_id BIGINT DEFAULT NULL,
  user_id BIGINT NOT NULL,
  user_blng_orga_dspl_seq VARCHAR(20) DEFAULT NULL,
  delete_flag CHAR(1) DEFAULT '0',
  create_time TIMESTAMP DEFAULT NULL,
  creator BIGINT DEFAULT NULL,
  update_time TIMESTAMP DEFAULT NULL,
  updater BIGINT DEFAULT NULL,
  tenant_id BIGINT DEFAULT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX orga_id ON jsh_orga_user_rel (orga_id);
CREATE INDEX user_id ON jsh_orga_user_rel (user_id);
CREATE INDEX creator ON jsh_orga_user_rel (creator);
CREATE INDEX tenant_id ON jsh_orga_user_rel (tenant_id);

-- relation-detector-fixture-table: public.jsh_organization
CREATE TABLE jsh_organization (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  org_no VARCHAR(20) DEFAULT NULL,
  org_abr VARCHAR(20) DEFAULT NULL,
  parent_id BIGINT DEFAULT NULL,
  sort VARCHAR(20) DEFAULT NULL,
  remark VARCHAR(500) DEFAULT NULL,
  create_time TIMESTAMP DEFAULT NULL,
  update_time TIMESTAMP DEFAULT NULL,
  tenant_id BIGINT DEFAULT NULL,
  delete_flag VARCHAR(1) DEFAULT '0',
  PRIMARY KEY (id)
);
CREATE INDEX tenant_id ON jsh_organization (tenant_id);

-- relation-detector-fixture-table: public.jsh_person
CREATE TABLE jsh_person (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  type VARCHAR(20) DEFAULT NULL,
  name VARCHAR(50) DEFAULT NULL,
  enabled BOOLEAN DEFAULT NULL,
  sort VARCHAR(10) DEFAULT NULL,
  tenant_id BIGINT DEFAULT NULL,
  delete_flag VARCHAR(1) DEFAULT '0',
  PRIMARY KEY (id)
);
CREATE INDEX tenant_id ON jsh_person (tenant_id);

-- relation-detector-fixture-table: public.jsh_platform_config
CREATE TABLE jsh_platform_config (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  platform_key VARCHAR(100) DEFAULT NULL,
  platform_key_info VARCHAR(100) DEFAULT NULL,
  platform_value VARCHAR(200) DEFAULT NULL,
  PRIMARY KEY (id)
);

-- relation-detector-fixture-table: public.jsh_role
CREATE TABLE jsh_role (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(50) DEFAULT NULL,
  type VARCHAR(50) DEFAULT NULL,
  price_limit VARCHAR(50) DEFAULT NULL,
  value VARCHAR(200) DEFAULT NULL,
  description VARCHAR(100) DEFAULT NULL,
  enabled BOOLEAN DEFAULT NULL,
  sort VARCHAR(10) DEFAULT NULL,
  tenant_id BIGINT DEFAULT NULL,
  delete_flag VARCHAR(1) DEFAULT '0',
  PRIMARY KEY (id)
);
CREATE INDEX tenant_id ON jsh_role (tenant_id);

-- relation-detector-fixture-table: public.jsh_sequence
CREATE TABLE jsh_sequence (
  seq_name VARCHAR(50) NOT NULL,
  min_value BIGINT NOT NULL,
  max_value BIGINT NOT NULL,
  current_val BIGINT NOT NULL,
  increment_val INTEGER NOT NULL DEFAULT '1',
  remark VARCHAR(500) DEFAULT NULL,
  PRIMARY KEY (seq_name)
);

-- relation-detector-fixture-table: public.jsh_serial_number
CREATE TABLE jsh_serial_number (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  material_id BIGINT DEFAULT NULL,
  depot_id BIGINT DEFAULT NULL,
  serial_number VARCHAR(64) DEFAULT NULL,
  is_sell VARCHAR(1) DEFAULT '0',
  in_price NUMERIC(24,6) DEFAULT NULL,
  remark VARCHAR(1024) DEFAULT NULL,
  create_time TIMESTAMP DEFAULT NULL,
  creator BIGINT DEFAULT NULL,
  update_time TIMESTAMP DEFAULT NULL,
  updater BIGINT DEFAULT NULL,
  in_bill_no VARCHAR(50) DEFAULT NULL,
  out_bill_no VARCHAR(50) DEFAULT NULL,
  tenant_id BIGINT DEFAULT NULL,
  delete_flag VARCHAR(1) DEFAULT '0',
  PRIMARY KEY (id)
);
CREATE INDEX material_id ON jsh_serial_number (material_id);
CREATE INDEX depot_id ON jsh_serial_number (depot_id);
CREATE INDEX tenant_id ON jsh_serial_number (tenant_id);

-- relation-detector-fixture-table: public.jsh_supplier
CREATE TABLE jsh_supplier (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  supplier VARCHAR(255) NOT NULL,
  contacts VARCHAR(100) DEFAULT NULL,
  phone_num VARCHAR(30) DEFAULT NULL,
  email VARCHAR(50) DEFAULT NULL,
  description VARCHAR(500) DEFAULT NULL,
  isystem SMALLINT DEFAULT NULL,
  type VARCHAR(20) DEFAULT NULL,
  enabled BOOLEAN DEFAULT NULL,
  advance_in NUMERIC(24,6) DEFAULT '0.000000',
  begin_need_get NUMERIC(24,6) DEFAULT NULL,
  begin_need_pay NUMERIC(24,6) DEFAULT NULL,
  all_need_get NUMERIC(24,6) DEFAULT NULL,
  all_need_pay NUMERIC(24,6) DEFAULT NULL,
  fax VARCHAR(30) DEFAULT NULL,
  telephone VARCHAR(30) DEFAULT NULL,
  address VARCHAR(100) DEFAULT NULL,
  tax_num VARCHAR(50) DEFAULT NULL,
  bank_name VARCHAR(50) DEFAULT NULL,
  account_number VARCHAR(50) DEFAULT NULL,
  tax_rate NUMERIC(24,6) DEFAULT NULL,
  sort VARCHAR(10) DEFAULT NULL,
  creator BIGINT DEFAULT NULL,
  tenant_id BIGINT DEFAULT NULL,
  delete_flag VARCHAR(1) DEFAULT '0',
  PRIMARY KEY (id)
);
CREATE INDEX type ON jsh_supplier (type);
CREATE INDEX tenant_id ON jsh_supplier (tenant_id);

-- relation-detector-fixture-table: public.jsh_sys_dict_data
CREATE TABLE jsh_sys_dict_data (
  dict_code BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  dict_sort INTEGER DEFAULT '0',
  dict_label VARCHAR(100) DEFAULT '',
  dict_value VARCHAR(100) DEFAULT '',
  dict_type VARCHAR(100) DEFAULT '',
  css_class VARCHAR(100) DEFAULT NULL,
  list_class VARCHAR(100) DEFAULT NULL,
  is_default CHAR(1) DEFAULT 'N',
  status CHAR(1) DEFAULT '0',
  create_by VARCHAR(64) DEFAULT '',
  create_time TIMESTAMP DEFAULT NULL,
  update_by VARCHAR(64) DEFAULT '',
  update_time TIMESTAMP DEFAULT NULL,
  remark VARCHAR(500) DEFAULT NULL,
  delete_flag VARCHAR(1) DEFAULT '0',
  PRIMARY KEY (dict_code)
);

-- relation-detector-fixture-table: public.jsh_sys_dict_type
CREATE TABLE jsh_sys_dict_type (
  dict_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  dict_name VARCHAR(100) DEFAULT '',
  dict_type VARCHAR(100) DEFAULT '',
  status CHAR(1) DEFAULT '0',
  create_by VARCHAR(64) DEFAULT '',
  create_time TIMESTAMP DEFAULT NULL,
  update_by VARCHAR(64) DEFAULT '',
  update_time TIMESTAMP DEFAULT NULL,
  remark VARCHAR(500) DEFAULT NULL,
  delete_flag VARCHAR(1) DEFAULT '0',
  PRIMARY KEY (dict_id),
  CONSTRAINT dict_type UNIQUE (dict_type)
);

-- relation-detector-fixture-table: public.jsh_system_config
CREATE TABLE jsh_system_config (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  company_name VARCHAR(50) DEFAULT NULL,
  company_contacts VARCHAR(20) DEFAULT NULL,
  company_address VARCHAR(50) DEFAULT NULL,
  company_tel VARCHAR(20) DEFAULT NULL,
  company_fax VARCHAR(20) DEFAULT NULL,
  company_post_code VARCHAR(20) DEFAULT NULL,
  sale_agreement VARCHAR(500) DEFAULT NULL,
  depot_flag VARCHAR(1) DEFAULT '0',
  customer_flag VARCHAR(1) DEFAULT '0',
  minus_stock_flag VARCHAR(1) DEFAULT '0',
  purchase_by_sale_flag VARCHAR(1) DEFAULT '0',
  multi_level_approval_flag VARCHAR(1) DEFAULT '0',
  multi_bill_type VARCHAR(200) DEFAULT NULL,
  force_approval_flag VARCHAR(1) DEFAULT '0',
  update_unit_price_flag VARCHAR(1) DEFAULT '1',
  over_link_bill_flag VARCHAR(1) DEFAULT '0',
  in_out_manage_flag VARCHAR(1) DEFAULT '0',
  multi_account_flag VARCHAR(1) DEFAULT '0',
  move_avg_price_flag VARCHAR(1) DEFAULT '0',
  audit_print_flag VARCHAR(1) DEFAULT '0',
  zero_change_amount_flag VARCHAR(1) DEFAULT '0',
  customer_static_price_flag VARCHAR(1) DEFAULT '0',
  material_price_tax_flag VARCHAR(1) DEFAULT '0',
  tenant_id BIGINT DEFAULT NULL,
  delete_flag VARCHAR(1) DEFAULT '0',
  PRIMARY KEY (id)
);

-- relation-detector-fixture-table: public.jsh_temp_category_affinity
CREATE TABLE jsh_temp_category_affinity (
  id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  source_cat_id INTEGER DEFAULT NULL,
  target_cat_id INTEGER DEFAULT NULL,
  link_prob NUMERIC(4,3) DEFAULT NULL,
  min_ratio NUMERIC(4,2) DEFAULT NULL,
  max_ratio NUMERIC(4,2) DEFAULT NULL,
  rule_desc VARCHAR(100) DEFAULT NULL,
  PRIMARY KEY (id)
);

-- relation-detector-fixture-table: public.jsh_temp_category_pdf
CREATE TABLE jsh_temp_category_pdf (
  id BIGINT NOT NULL,
  name VARCHAR(50) DEFAULT NULL,
  weight INTEGER DEFAULT '10',
  cdf_end NUMERIC(10,4) DEFAULT NULL,
  PRIMARY KEY (id)
);

-- relation-detector-fixture-table: public.jsh_temp_day_pdf
CREATE TABLE jsh_temp_day_pdf (
  day_date DATE NOT NULL,
  weight INTEGER DEFAULT '100',
  is_holiday SMALLINT DEFAULT '0',
  remark VARCHAR(100) DEFAULT NULL,
  PRIMARY KEY (day_date)
);

-- relation-detector-fixture-table: public.jsh_temp_hour_pdf
CREATE TABLE jsh_temp_hour_pdf (
  hour_val INTEGER NOT NULL,
  weight INTEGER DEFAULT '10',
  remark VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (hour_val)
);

-- relation-detector-fixture-table: public.jsh_temp_mock_batch_results
CREATE TABLE jsh_temp_mock_batch_results (
  id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  tenant_id BIGINT NOT NULL,
  status VARCHAR(10) NOT NULL,
  order_id BIGINT DEFAULT NULL,
  bill_no VARCHAR(50) DEFAULT NULL,
  mock_time TIMESTAMP DEFAULT NULL,
  operator VARCHAR(50) DEFAULT NULL,
  item_count INTEGER DEFAULT '0',
  total_amount NUMERIC(24,6) DEFAULT '0.000000',
  remark VARCHAR(500) DEFAULT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX idx_audit_month ON jsh_temp_mock_batch_results (mock_time);

-- relation-detector-fixture-table: public.jsh_temp_mock_plan
CREATE TABLE jsh_temp_mock_plan (
  id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL,
  mock_timestamp_str VARCHAR(20) NOT NULL,
  bill_no_str VARCHAR(50) NOT NULL,
  execute_status SMALLINT DEFAULT '0',
  PRIMARY KEY (id)
);
CREATE INDEX idx_mock_time ON jsh_temp_mock_plan (mock_timestamp_str);

-- relation-detector-fixture-table: public.jsh_temp_org_pdf
CREATE TABLE jsh_temp_org_pdf (
  org_id BIGINT NOT NULL,
  weight INTEGER DEFAULT '10',
  cdf_end NUMERIC(10,4) DEFAULT NULL,
  remark VARCHAR(100) DEFAULT NULL,
  PRIMARY KEY (org_id)
);

-- relation-detector-fixture-table: public.jsh_tenant
CREATE TABLE jsh_tenant (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  tenant_id BIGINT DEFAULT NULL,
  login_name VARCHAR(255) DEFAULT NULL,
  user_num_limit INTEGER DEFAULT NULL,
  type VARCHAR(1) DEFAULT '0',
  enabled BOOLEAN DEFAULT true,
  create_time TIMESTAMP DEFAULT NULL,
  expire_time TIMESTAMP DEFAULT NULL,
  remark VARCHAR(500) DEFAULT NULL,
  delete_flag VARCHAR(1) DEFAULT '0',
  PRIMARY KEY (id)
);
CREATE INDEX create_time ON jsh_tenant (create_time);
CREATE INDEX tenant_id ON jsh_tenant (tenant_id);

-- relation-detector-fixture-table: public.jsh_unit
CREATE TABLE jsh_unit (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(50) DEFAULT NULL,
  basic_unit VARCHAR(50) DEFAULT NULL,
  other_unit VARCHAR(50) DEFAULT NULL,
  other_unit_two VARCHAR(50) DEFAULT NULL,
  other_unit_three VARCHAR(50) DEFAULT NULL,
  ratio NUMERIC(24,3) DEFAULT NULL,
  ratio_two NUMERIC(24,3) DEFAULT NULL,
  ratio_three NUMERIC(24,3) DEFAULT NULL,
  enabled BOOLEAN DEFAULT NULL,
  tenant_id BIGINT DEFAULT NULL,
  delete_flag VARCHAR(1) DEFAULT '0',
  PRIMARY KEY (id)
);

-- relation-detector-fixture-table: public.jsh_user
CREATE TABLE jsh_user (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  username VARCHAR(255) NOT NULL,
  login_name VARCHAR(255) NOT NULL,
  password VARCHAR(50) DEFAULT NULL,
  leader_flag VARCHAR(1) DEFAULT '0',
  position VARCHAR(200) DEFAULT NULL,
  department VARCHAR(255) DEFAULT NULL,
  email VARCHAR(100) DEFAULT NULL,
  phonenum VARCHAR(100) DEFAULT NULL,
  ismanager SMALLINT NOT NULL DEFAULT '1',
  isystem SMALLINT NOT NULL DEFAULT '0',
  status SMALLINT DEFAULT '0',
  description VARCHAR(500) DEFAULT NULL,
  remark VARCHAR(500) DEFAULT NULL,
  weixin_open_id VARCHAR(100) DEFAULT NULL,
  tenant_id BIGINT DEFAULT NULL,
  delete_flag VARCHAR(1) DEFAULT '0',
  PRIMARY KEY (id)
);

-- relation-detector-fixture-table: public.jsh_user_business
CREATE TABLE jsh_user_business (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  type VARCHAR(50) DEFAULT NULL,
  key_id VARCHAR(50) DEFAULT NULL,
  value TEXT,
  btn_str VARCHAR(20000) DEFAULT NULL,
  tenant_id BIGINT DEFAULT NULL,
  delete_flag VARCHAR(1) DEFAULT '0',
  PRIMARY KEY (id)
);
CREATE INDEX type ON jsh_user_business (type);
CREATE INDEX key_id ON jsh_user_business (key_id);
CREATE INDEX tenant_id ON jsh_user_business (tenant_id);

-- relation-detector-fixture-table: public.log_bill_sync_detail
CREATE TABLE log_bill_sync_detail (
  logid BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  syncbatchid VARCHAR(50) NOT NULL,
  tenantid BIGINT NOT NULL,
  sourceorderid BIGINT NOT NULL,
  sourceorderitemid BIGINT NOT NULL,
  executetime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  syncstatus VARCHAR(20) NOT NULL,
  errormsg VARCHAR(1000) DEFAULT NULL,
  PRIMARY KEY (logid)
);
CREATE INDEX idx_sync_batch ON log_bill_sync_detail (syncbatchid);
CREATE INDEX idx_source_item ON log_bill_sync_detail (tenantid, sourceorderitemid);

-- relation-detector-fixture-table: public.ontology
CREATE TABLE ontology (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  ontology_name VARCHAR(100) NOT NULL,
  ontology_code VARCHAR(100) NOT NULL,
  business_definition VARCHAR(1024) DEFAULT NULL,
  ontology_type VARCHAR(50) NOT NULL DEFAULT 'entity',
  physical_table VARCHAR(200) DEFAULT NULL,
  business_domain VARCHAR(50) DEFAULT NULL,
  sort_order INTEGER NOT NULL DEFAULT '0',
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  enabled INTEGER NOT NULL DEFAULT '1',
  business_definition_bak VARCHAR(1024) DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT idx_aa733b95416a2be7d0dce878b8 UNIQUE (ontology_code)
);

-- relation-detector-fixture-table: public.ontology_metric
CREATE TABLE ontology_metric (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  metric_code VARCHAR(100) NOT NULL,
  metric_name VARCHAR(100) DEFAULT NULL,
  ontology_code VARCHAR(100) NOT NULL,
  show_style VARCHAR(50) NOT NULL DEFAULT 'table',
  description VARCHAR(500) DEFAULT NULL,
  input_params_json TEXT,
  output_fields_json TEXT,
  default_order_by VARCHAR(200) DEFAULT NULL,
  default_order_dir VARCHAR(10) NOT NULL DEFAULT 'desc',
  default_limit INTEGER NOT NULL DEFAULT '5',
  sort_order INTEGER NOT NULL DEFAULT '0',
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  input_dimensions JSONB DEFAULT NULL,
  output_dimensions JSONB DEFAULT NULL,
  enabled INTEGER NOT NULL DEFAULT '1',
  metric_sql TEXT,
  description_bak VARCHAR(1024) DEFAULT NULL,
  metric_sql1 TEXT,
  PRIMARY KEY (id),
  CONSTRAINT idx_15e15406175086eaaf5769117f UNIQUE (metric_code)
);

-- relation-detector-fixture-table: public.ontology_metric_bak
CREATE TABLE ontology_metric_bak (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  metric_code VARCHAR(100) NOT NULL,
  metric_name VARCHAR(100) DEFAULT NULL,
  ontology_code VARCHAR(100) NOT NULL,
  show_style VARCHAR(50) DEFAULT 'table',
  description VARCHAR(500) DEFAULT NULL,
  description1 TEXT,
  input_params_json TEXT,
  output_fields_json TEXT,
  default_order_by VARCHAR(200) DEFAULT NULL,
  default_order_dir VARCHAR(10) DEFAULT 'desc',
  default_limit INTEGER DEFAULT '5',
  sort_order INTEGER DEFAULT '0',
  enabled SMALLINT DEFAULT '1',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uk_metric_code UNIQUE (metric_code)
);
CREATE INDEX idx_ontology_code ON ontology_metric_bak (ontology_code);

-- relation-detector-fixture-table: public.ontology_metric_bak_ceil_20260525
CREATE TABLE ontology_metric_bak_ceil_20260525 (
  id BIGINT NOT NULL DEFAULT '0',
  metric_code VARCHAR(100) NOT NULL,
  metric_name VARCHAR(100) DEFAULT NULL,
  ontology_code VARCHAR(100) NOT NULL,
  show_style VARCHAR(50) NOT NULL DEFAULT 'table',
  description VARCHAR(500) DEFAULT NULL,
  input_params_json TEXT,
  output_fields_json TEXT,
  default_order_by VARCHAR(200) DEFAULT NULL,
  default_order_dir VARCHAR(10) NOT NULL DEFAULT 'desc',
  default_limit INTEGER NOT NULL DEFAULT '5',
  sort_order INTEGER NOT NULL DEFAULT '0',
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  input_dimensions JSONB DEFAULT NULL,
  output_dimensions JSONB DEFAULT NULL,
  enabled INTEGER NOT NULL DEFAULT '1',
  metric_sql TEXT
);

-- relation-detector-fixture-table: public.ontology_property
CREATE TABLE ontology_property (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  ontology_code VARCHAR(100) NOT NULL,
  property_name VARCHAR(100) NOT NULL,
  property_type VARCHAR(50) NOT NULL,
  description VARCHAR(500) DEFAULT NULL,
  sort_order INTEGER NOT NULL DEFAULT '0',
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  is_primary_key INTEGER NOT NULL DEFAULT '0',
  enabled INTEGER NOT NULL DEFAULT '1',
  PRIMARY KEY (id)
);

-- relation-detector-fixture-table: public.ontology_relation
CREATE TABLE ontology_relation (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  relation_name VARCHAR(100) NOT NULL,
  source_ontology VARCHAR(100) NOT NULL,
  target_ontology VARCHAR(100) NOT NULL,
  cardinality VARCHAR(20) NOT NULL,
  description VARCHAR(500) DEFAULT NULL,
  mapping_field VARCHAR(200) DEFAULT NULL,
  source_primary_key VARCHAR(100) DEFAULT NULL,
  unique_code VARCHAR(200) NOT NULL,
  sort_order INTEGER NOT NULL DEFAULT '0',
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  enabled INTEGER NOT NULL DEFAULT '1',
  description_bak VARCHAR(1024) DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT idx_e490fb346e1a9921337c87a381 UNIQUE (unique_code)
);

-- relation-detector-fixture-table: public.ontology_rule
CREATE TABLE ontology_rule (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  ontology_code VARCHAR(100) NOT NULL,
  name VARCHAR(100) NOT NULL,
  rule_code VARCHAR(100) DEFAULT NULL,
  rule_type VARCHAR(50) DEFAULT NULL,
  scene_type VARCHAR(50) DEFAULT NULL,
  description VARCHAR(1000) DEFAULT NULL,
  sort_order INTEGER DEFAULT '0',
  enabled SMALLINT DEFAULT '1',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

-- relation-detector-fixture-table: public.ontology_rule_1
CREATE TABLE ontology_rule_1 (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  ontology_code VARCHAR(100) NOT NULL,
  code VARCHAR(100) DEFAULT NULL,
  name VARCHAR(100) NOT NULL,
  description VARCHAR(500) DEFAULT NULL,
  sort_order INTEGER DEFAULT '0',
  enabled SMALLINT DEFAULT '1',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

-- relation-detector-fixture-table: public.ontology_rule_item
CREATE TABLE ontology_rule_item (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  rule_code VARCHAR(100) NOT NULL,
  item_code VARCHAR(100) NOT NULL,
  item_name VARCHAR(200) NOT NULL,
  item_type VARCHAR(50) NOT NULL,
  item_content TEXT,
  executable_logic VARCHAR(1000) DEFAULT NULL,
  priority INTEGER DEFAULT '0',
  sort_order INTEGER DEFAULT '0',
  enabled SMALLINT DEFAULT '1',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uk_item_code UNIQUE (item_code)
);

-- relation-detector-fixture-table: public.ontology_rule_item_1
CREATE TABLE ontology_rule_item_1 (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  rule_code VARCHAR(100) NOT NULL,
  rule_name VARCHAR(200) NOT NULL,
  rule_content TEXT NOT NULL,
  priority INTEGER DEFAULT '0',
  sort_order INTEGER DEFAULT '0',
  enabled SMALLINT DEFAULT '1',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

-- relation-detector-fixture-table: public.spring_ai_store
CREATE TABLE spring_ai_store (
  id VARCHAR(500) NOT NULL,
  namespace TEXT,
  key_name VARCHAR(500) DEFAULT NULL,
  value_json TEXT,
  created_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id)
);

-- relation-detector-fixture-table: public.sys_batch_exec_detail_log
CREATE TABLE sys_batch_exec_detail_log (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  batch_session_time TIMESTAMP NOT NULL,
  inbound_number VARCHAR(50) DEFAULT NULL,
  source_order_id BIGINT DEFAULT NULL,
  creator_id BIGINT DEFAULT NULL,
  warehouse_id BIGINT DEFAULT NULL,
  time_user NUMERIC(10,4) DEFAULT NULL,
  time_number NUMERIC(10,4) DEFAULT NULL,
  time_order NUMERIC(10,4) DEFAULT NULL,
  time_depot NUMERIC(10,4) DEFAULT NULL,
  time_item NUMERIC(10,4) DEFAULT NULL,
  time_stock NUMERIC(10,4) DEFAULT NULL,
  time_head NUMERIC(10,4) DEFAULT NULL,
  result_status VARCHAR(10) DEFAULT NULL,
  error_message VARCHAR(500) DEFAULT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX idx_batch_session ON sys_batch_exec_detail_log (batch_session_time);
