-- ============================================================
-- ERP系统补充表: 发货物流、销售提成、促销活动、
--   三单匹配、固定资产、BOM生产工单、客服工单
-- 关系说明:
--   shipments -> sales_orders (1:1), 通过tracking_no追踪物流
--   sales_commissions -> sales_orders + employees (N:1:1), 按销售额计算提成
--   promotions -> sales_order_items (N:M), 通过promotion_items关联
--   invoices -> purchase_orders + purchase_receipts (三单匹配)
--   fixed_assets + depreciation_log (固定资产+折旧)
--   boms -> products (自引用), 生产工单用料展开
--   work_orders -> boms + products (生产工单)
-- ============================================================

-- ============================================================
-- Custom ENUM types
-- ============================================================

-- ============================================================
-- 1. 发货物流模块
-- shipments: 发货单 -> 关联sales_orders
-- shipping_tracks: 物流轨迹 -> 关联shipments
-- ============================================================

CREATE TABLE shipments (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_no VARCHAR2(30) NOT NULL UNIQUE,
    order_id NUMBER(19) CHECK (order_id >= 0) NOT NULL,
    warehouse_id NUMBER(19) CHECK (warehouse_id >= 0) NOT NULL,
    carrier VARCHAR2(100) NOT NULL,
    tracking_no VARCHAR2(50) NULL,
    shipping_method VARCHAR2(40) DEFAULT 'express',
    shipping_fee NUMBER(12,2) DEFAULT 0.00,
    package_count NUMBER(10) DEFAULT 1,
    weight_kg NUMBER(8,3) DEFAULT 0.000,
    status VARCHAR2(40) DEFAULT 'pending',
    picker_id NUMBER(19) NULL,
    packer_id NUMBER(19) NULL,
    shipped_at TIMESTAMP(0) NULL,
    delivered_at TIMESTAMP(0) NULL,
    estimated_delivery_date DATE NULL,
    actual_delivery_date DATE NULL,
    from_address VARCHAR2(300) NULL,
    to_address VARCHAR2(300) NOT NULL,
    receiver_name VARCHAR2(50) NULL,
    receiver_phone VARCHAR2(20) NULL,
    remark VARCHAR2(500) NULL,
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ship_order FOREIGN KEY (order_id) REFERENCES sales_orders(id),
    CONSTRAINT fk_ship_wh FOREIGN KEY (warehouse_id) REFERENCES warehouses(id)
);

CREATE INDEX idx_shipments_order ON shipments (order_id);
CREATE INDEX idx_shipments_tracking ON shipments (tracking_no);
CREATE INDEX idx_shipments_status ON shipments (status);
CREATE INDEX idx_shipments_carrier ON shipments (carrier);
CREATE INDEX idx_shipments_shipped_at ON shipments (shipped_at);

CREATE OR REPLACE TRIGGER trg_shipments_updated_at
    BEFORE UPDATE ON shipments
    FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

CREATE TABLE shipping_tracks (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_id NUMBER(19) CHECK (shipment_id >= 0) NOT NULL,
    track_time TIMESTAMP(0) NOT NULL,
    location VARCHAR2(200) NOT NULL,
    status_desc VARCHAR2(200) NOT NULL,
    operator VARCHAR2(50) NULL,
    remark VARCHAR2(200) NULL,
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_st_shipment FOREIGN KEY (shipment_id) REFERENCES shipments(id) ON DELETE CASCADE
);

CREATE INDEX idx_shipping_tracks_shipment ON shipping_tracks (shipment_id);
CREATE INDEX idx_shipping_tracks_track_time ON shipping_tracks (track_time);

-- ============================================================
-- 2. 销售提成模块
-- 提成规则: 不同产品/分类不同提成比例
-- 销售额阶梯提成，超过目标有额外奖励
-- ============================================================

CREATE TABLE commission_rules (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    product_category_id NUMBER(19) NULL,
    min_amount NUMBER(18,2) DEFAULT 0.00,
    max_amount NUMBER(18,2) DEFAULT 99999999.99,
    commission_rate NUMBER(5,4) NOT NULL,
    bonus NUMBER(12,2) DEFAULT 0.00,
    effective_date DATE NOT NULL,
    expiry_date DATE NULL,
    status VARCHAR2(40) DEFAULT 'active',
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_cr_category FOREIGN KEY (product_category_id) REFERENCES product_categories(id) ON DELETE SET NULL
);

CREATE INDEX idx_commission_rules_category ON commission_rules (product_category_id);
CREATE INDEX idx_commission_rules_effective ON commission_rules (effective_date, expiry_date);

CREATE TABLE sales_commissions (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id NUMBER(19) CHECK (employee_id >= 0) NOT NULL,
    order_id NUMBER(19) CHECK (order_id >= 0) NOT NULL,
    order_item_id NUMBER(19) NULL,
    period VARCHAR2(7) NOT NULL,
    base_amount NUMBER(18,2) NOT NULL,
    commission_rate NUMBER(5,4) NOT NULL,
    commission_amount NUMBER(12,2) NOT NULL,
    bonus NUMBER(12,2) DEFAULT 0.00,
    total_commission NUMBER(12,2) GENERATED ALWAYS AS (commission_amount + bonus) VIRTUAL,
    status VARCHAR2(40) DEFAULT 'pending',
    calculated_at TIMESTAMP(0) NULL,
    paid_at TIMESTAMP(0) NULL,
    settlement_id NUMBER(19) NULL,
    CONSTRAINT uk_sales_commissions_order_item UNIQUE (order_id, order_item_id),
    CONSTRAINT fk_sc_emp FOREIGN KEY (employee_id) REFERENCES employees(id),
    CONSTRAINT fk_sc_order FOREIGN KEY (order_id) REFERENCES sales_orders(id)
);

CREATE INDEX idx_sales_commissions_employee ON sales_commissions (employee_id);
CREATE INDEX idx_sales_commissions_period ON sales_commissions (period);
CREATE INDEX idx_sales_commissions_status ON sales_commissions (status);

-- ============================================================
-- 3. 促销活动模块
-- ============================================================

CREATE TABLE promotions (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(200) NOT NULL,
    code VARCHAR2(30) NOT NULL UNIQUE,
    promotion_type VARCHAR2(40) NOT NULL,
    discount_value NUMBER(12,2) NOT NULL,
    min_purchase_amount NUMBER(18,2) DEFAULT 0.00,
    max_discount_amount NUMBER(12,2) DEFAULT 0.00,
    usage_limit NUMBER(10) DEFAULT 0,
    used_count NUMBER(10) DEFAULT 0,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    status VARCHAR2(40) DEFAULT 'draft',
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_promotions_date_range ON promotions (start_date, end_date);
CREATE INDEX idx_promotions_status ON promotions (status);
CREATE INDEX idx_promotions_code ON promotions (code);

CREATE OR REPLACE TRIGGER trg_promotions_updated_at
    BEFORE UPDATE ON promotions
    FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

CREATE TABLE promotion_products (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    promotion_id NUMBER(19) CHECK (promotion_id >= 0) NOT NULL,
    product_id NUMBER(19) NULL,
    category_id NUMBER(19) NULL,
    CONSTRAINT uk_promo_product UNIQUE (promotion_id, product_id, category_id),
    CONSTRAINT fk_pp_promo FOREIGN KEY (promotion_id) REFERENCES promotions(id) ON DELETE CASCADE,
    CONSTRAINT fk_pp_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
    CONSTRAINT fk_pp_category FOREIGN KEY (category_id) REFERENCES product_categories(id) ON DELETE CASCADE
);

-- 促销使用记录
CREATE TABLE promotion_usages (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    promotion_id NUMBER(19) CHECK (promotion_id >= 0) NOT NULL,
    order_id NUMBER(19) CHECK (order_id >= 0) NOT NULL,
    customer_id NUMBER(19) CHECK (customer_id >= 0) NOT NULL,
    discount_applied NUMBER(12,2) NOT NULL,
    used_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_promo_order UNIQUE (promotion_id, order_id),
    CONSTRAINT fk_pu_promo FOREIGN KEY (promotion_id) REFERENCES promotions(id),
    CONSTRAINT fk_pu_order FOREIGN KEY (order_id) REFERENCES sales_orders(id) ON DELETE CASCADE,
    CONSTRAINT fk_pu_customer FOREIGN KEY (customer_id) REFERENCES customers(id)
);

CREATE INDEX idx_promotion_usages_customer ON promotion_usages (customer_id);

-- ============================================================
-- 4. 发票与三单匹配模块
-- 三单匹配: 采购单(PO) vs 入库单(Receipt) vs 发票(Invoice)
-- 匹配条件: 数量、单价、金额一致才可付款
-- ============================================================

CREATE TABLE invoices (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_no VARCHAR2(50) NOT NULL UNIQUE,
    invoice_type VARCHAR2(40) NOT NULL,
    supplier_id NUMBER(19) NULL,
    customer_id NUMBER(19) NULL,
    invoice_date DATE NOT NULL,
    due_date DATE NULL,
    total_amount NUMBER(18,2) NOT NULL,
    tax_amount NUMBER(18,2) DEFAULT 0.00,
    tax_rate NUMBER(5,4) DEFAULT 0.13,
    status VARCHAR2(40) DEFAULT 'draft',
    verified_by NUMBER(19) NULL,
    verified_at TIMESTAMP(0) NULL,
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_inv_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE SET NULL,
    CONSTRAINT fk_inv_customer FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE SET NULL
);

CREATE INDEX idx_invoices_supplier ON invoices (supplier_id);
CREATE INDEX idx_invoices_customer ON invoices (customer_id);
CREATE INDEX idx_invoices_date ON invoices (invoice_date);
CREATE INDEX idx_invoices_status ON invoices (status);

CREATE OR REPLACE TRIGGER trg_invoices_updated_at
    BEFORE UPDATE ON invoices
    FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- 三单匹配明细
CREATE TABLE three_way_matching (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id NUMBER(19) CHECK (invoice_id >= 0) NOT NULL,
    purchase_order_id NUMBER(19) CHECK (purchase_order_id >= 0) NOT NULL,
    purchase_receipt_id NUMBER(19) CHECK (purchase_receipt_id >= 0) NOT NULL,
    product_id NUMBER(19) CHECK (product_id >= 0) NOT NULL,
    po_quantity NUMBER(10) NOT NULL,
    receipt_quantity NUMBER(10) NOT NULL,
    invoice_quantity NUMBER(10) NOT NULL,
    po_price NUMBER(12,2) NOT NULL,
    receipt_price NUMBER(12,2) NOT NULL,
    invoice_price NUMBER(12,2) NOT NULL,
    quantity_match NUMBER(1) GENERATED ALWAYS AS (CASE WHEN po_quantity = receipt_quantity AND receipt_quantity = invoice_quantity THEN 1 ELSE 0 END) VIRTUAL,
    price_match NUMBER(1) GENERATED ALWAYS AS (CASE WHEN po_price = receipt_price AND receipt_price = invoice_price THEN 1 ELSE 0 END) VIRTUAL,
    match_status VARCHAR2(40) DEFAULT 'pending',
    match_result VARCHAR2(500) NULL,
    matched_by NUMBER(19) NULL,
    matched_at TIMESTAMP(0) NULL,
    CONSTRAINT fk_twm_invoice FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE CASCADE,
    CONSTRAINT fk_twm_po FOREIGN KEY (purchase_order_id) REFERENCES purchase_orders(id),
    CONSTRAINT fk_twm_receipt FOREIGN KEY (purchase_receipt_id) REFERENCES purchase_receipts(id),
    CONSTRAINT fk_twm_product FOREIGN KEY (product_id) REFERENCES products(id)
);

CREATE INDEX idx_three_way_matching_invoice ON three_way_matching (invoice_id);
CREATE INDEX idx_three_way_matching_po ON three_way_matching (purchase_order_id);
CREATE INDEX idx_three_way_matching_receipt ON three_way_matching (purchase_receipt_id);

-- ============================================================
-- 5. 固定资产模块
-- 折旧方法: 直线法(straight_line)
-- 折旧公式: 月折旧额 = (原值 - 残值) / 使用月数
-- 净值 = 原值 - 累计折旧
-- ============================================================

CREATE TABLE fixed_assets (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_no VARCHAR2(30) NOT NULL UNIQUE,
    name VARCHAR2(200) NOT NULL,
    category VARCHAR2(40) NOT NULL,
    purchase_date DATE NOT NULL,
    purchase_amount NUMBER(18,2) NOT NULL,
    salvage_value NUMBER(18,2) DEFAULT 0.00,
    useful_life_months NUMBER(10) NOT NULL,
    monthly_depreciation NUMBER(12,2) GENERATED ALWAYS AS (
        ROUND((purchase_amount - salvage_value) / useful_life_months, 2)
    ) VIRTUAL,
    accumulated_depreciation NUMBER(18,2) DEFAULT 0.00,
    net_book_value NUMBER(18,2) GENERATED ALWAYS AS (
        purchase_amount - accumulated_depreciation
    ) VIRTUAL,
    department_id NUMBER(19) CHECK (department_id >= 0) NOT NULL,
    custodian_id NUMBER(19) NULL,
    location VARCHAR2(200) NULL,
    status VARCHAR2(40) DEFAULT 'in_use',
    last_depreciation_date DATE NULL,
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_fa_dept FOREIGN KEY (department_id) REFERENCES departments(id),
    CONSTRAINT fk_fa_custodian FOREIGN KEY (custodian_id) REFERENCES employees(id) ON DELETE SET NULL
);

CREATE INDEX idx_fixed_assets_dept ON fixed_assets (department_id);
CREATE INDEX idx_fixed_assets_category ON fixed_assets (category);
CREATE INDEX idx_fixed_assets_status ON fixed_assets (status);

CREATE OR REPLACE TRIGGER trg_fixed_assets_updated_at
    BEFORE UPDATE ON fixed_assets
    FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

CREATE TABLE depreciation_log (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id NUMBER(19) CHECK (asset_id >= 0) NOT NULL,
    depreciation_date DATE NOT NULL,
    depreciation_amount NUMBER(12,2) NOT NULL,
    before_accumulated NUMBER(18,2) NOT NULL,
    after_accumulated NUMBER(18,2) NOT NULL,
    before_net_value NUMBER(18,2) NOT NULL,
    after_net_value NUMBER(18,2) NOT NULL,
    voucher_id NUMBER(19) NULL,
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_asset_date UNIQUE (asset_id, depreciation_date),
    CONSTRAINT fk_dl_asset FOREIGN KEY (asset_id) REFERENCES fixed_assets(id) ON DELETE CASCADE
);

CREATE INDEX idx_depreciation_log_date ON depreciation_log (depreciation_date);

-- ============================================================
-- 6. BOM与生产工单模块
-- BOM: 物料清单，定义产品组成关系
-- 自引用: parent_product_id -> products.id (成品), child_product_id -> products.id (原料/半成品)
-- ============================================================

CREATE TABLE boms (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_product_id NUMBER(19) CHECK (parent_product_id >= 0) NOT NULL,
    child_product_id NUMBER(19) CHECK (child_product_id >= 0) NOT NULL,
    quantity NUMBER(10,3) NOT NULL,
    unit VARCHAR2(20) NOT NULL,
    scrap_rate NUMBER(5,4) DEFAULT 0.00,
    sort_order NUMBER(10) DEFAULT 0,
    effective_date DATE NOT NULL,
    expiry_date DATE NULL,
    status VARCHAR2(40) DEFAULT 'active',
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_parent_child UNIQUE (parent_product_id, child_product_id, effective_date),
    CONSTRAINT fk_bom_parent FOREIGN KEY (parent_product_id) REFERENCES products(id) ON DELETE CASCADE,
    CONSTRAINT fk_bom_child FOREIGN KEY (child_product_id) REFERENCES products(id) ON DELETE CASCADE
);

CREATE INDEX idx_boms_child ON boms (child_product_id);
CREATE INDEX idx_boms_status ON boms (status);

CREATE TABLE work_orders (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no VARCHAR2(30) NOT NULL UNIQUE,
    product_id NUMBER(19) CHECK (product_id >= 0) NOT NULL,
    bom_id NUMBER(19) NULL,
    planned_quantity NUMBER(10) NOT NULL,
    completed_quantity NUMBER(10) DEFAULT 0,
    rejected_quantity NUMBER(10) DEFAULT 0,
    warehouse_id NUMBER(19) CHECK (warehouse_id >= 0) NOT NULL,
    start_date DATE NULL,
    due_date DATE NULL,
    completed_date DATE NULL,
    status VARCHAR2(40) DEFAULT 'draft',
    priority VARCHAR2(40) DEFAULT 'normal',
    released_by NUMBER(19) NULL,
    remark VARCHAR2(500) NULL,
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_wo_product FOREIGN KEY (product_id) REFERENCES products(id),
    CONSTRAINT fk_wo_bom FOREIGN KEY (bom_id) REFERENCES boms(id) ON DELETE SET NULL,
    CONSTRAINT fk_wo_wh FOREIGN KEY (warehouse_id) REFERENCES warehouses(id)
);

CREATE INDEX idx_work_orders_product ON work_orders (product_id);
CREATE INDEX idx_work_orders_status ON work_orders (status);
CREATE INDEX idx_work_orders_due_date ON work_orders (due_date);
CREATE INDEX idx_work_orders_priority ON work_orders (priority);

CREATE OR REPLACE TRIGGER trg_work_orders_updated_at
    BEFORE UPDATE ON work_orders
    FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- 工单用料明细
CREATE TABLE work_order_materials (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_order_id NUMBER(19) CHECK (work_order_id >= 0) NOT NULL,
    product_id NUMBER(19) CHECK (product_id >= 0) NOT NULL,
    batch_id NUMBER(19) NULL,
    required_qty NUMBER(10,3) NOT NULL,
    issued_qty NUMBER(10,3) DEFAULT 0,
    returned_qty NUMBER(10,3) DEFAULT 0,
    actual_consumed NUMBER(10,3) DEFAULT 0,
    unit VARCHAR2(20) NOT NULL,
    status VARCHAR2(40) DEFAULT 'pending',
    CONSTRAINT fk_wom_wo FOREIGN KEY (work_order_id) REFERENCES work_orders(id) ON DELETE CASCADE,
    CONSTRAINT fk_wom_product FOREIGN KEY (product_id) REFERENCES products(id)
);

CREATE INDEX idx_work_order_materials_wo ON work_order_materials (work_order_id);
CREATE INDEX idx_work_order_materials_product ON work_order_materials (product_id);

-- ============================================================
-- 7. 客服工单模块
-- ============================================================

CREATE TABLE service_tickets (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_no VARCHAR2(30) NOT NULL UNIQUE,
    customer_id NUMBER(19) CHECK (customer_id >= 0) NOT NULL,
    order_id NUMBER(19) NULL,
    product_id NUMBER(19) NULL,
    ticket_type VARCHAR2(40) NOT NULL,
    priority VARCHAR2(40) DEFAULT 'normal',
    subject VARCHAR2(200) NOT NULL,
    description CLOB NULL,
    status VARCHAR2(40) DEFAULT 'open',
    assigned_to NUMBER(19) NULL,
    resolution VARCHAR2(500) NULL,
    resolved_at TIMESTAMP(0) NULL,
    satisfaction_score NUMBER(5) NULL,
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_st_customer FOREIGN KEY (customer_id) REFERENCES customers(id),
    CONSTRAINT fk_st_order FOREIGN KEY (order_id) REFERENCES sales_orders(id) ON DELETE SET NULL,
    CONSTRAINT fk_st_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL,
    CONSTRAINT fk_st_assigned FOREIGN KEY (assigned_to) REFERENCES employees(id) ON DELETE SET NULL
);

CREATE INDEX idx_service_tickets_customer ON service_tickets (customer_id);
CREATE INDEX idx_service_tickets_order ON service_tickets (order_id);
CREATE INDEX idx_service_tickets_status ON service_tickets (status);
CREATE INDEX idx_service_tickets_priority ON service_tickets (priority);
CREATE INDEX idx_service_tickets_assigned ON service_tickets (assigned_to);

CREATE OR REPLACE TRIGGER trg_service_tickets_updated_at
    BEFORE UPDATE ON service_tickets
    FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/