-- ============================================================
-- ERP deep scenario tables - Oracle 16/17/18 compatible
-- Covers MRP, shop-floor execution, costing, AR/AP, WMS,
-- repair service, master-data governance, and sensitive access audit.
-- ============================================================

CREATE TABLE production_plans (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_no VARCHAR2(30) NOT NULL UNIQUE,
    product_id NUMBER(19) NOT NULL,
    warehouse_id NUMBER(19) NOT NULL,
    plan_month VARCHAR2(7) NOT NULL,
    forecast_qty NUMBER(10) NOT NULL,
    confirmed_sales_qty NUMBER(10) DEFAULT 0,
    safety_stock_qty NUMBER(10) DEFAULT 0,
    planned_production_qty NUMBER(10) NOT NULL,
    status VARCHAR2(20) DEFAULT 'draft',
    planner_id NUMBER(19) NOT NULL,
    approved_by NUMBER(19) NULL,
    approved_at TIMESTAMP(0) NULL,
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_prod_plan_product FOREIGN KEY (product_id) REFERENCES products(id),
    CONSTRAINT fk_prod_plan_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouses(id),
    CONSTRAINT fk_prod_plan_planner FOREIGN KEY (planner_id) REFERENCES employees(id),
    CONSTRAINT fk_prod_plan_approved FOREIGN KEY (approved_by) REFERENCES employees(id)
);

CREATE INDEX idx_prod_plan_month ON production_plans (plan_month);
CREATE INDEX idx_prod_plan_status ON production_plans (status);

CREATE TABLE mrp_runs (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_no VARCHAR2(30) NOT NULL UNIQUE,
    plan_id NUMBER(19) NOT NULL,
    run_date DATE NOT NULL,
    demand_source VARCHAR2(30) NOT NULL,
    status VARCHAR2(20) DEFAULT 'running',
    created_by NUMBER(19) NOT NULL,
    completed_at TIMESTAMP(0) NULL,
    CONSTRAINT fk_mrp_run_plan FOREIGN KEY (plan_id) REFERENCES production_plans(id),
    CONSTRAINT fk_mrp_run_created_by FOREIGN KEY (created_by) REFERENCES employees(id)
);

CREATE INDEX idx_mrp_run_date ON mrp_runs (run_date);

CREATE TABLE mrp_run_items (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id NUMBER(19) NOT NULL,
    parent_product_id NUMBER(19) NOT NULL,
    component_product_id NUMBER(19) NOT NULL,
    gross_requirement NUMBER(18,4) NOT NULL,
    on_hand_qty NUMBER(18,4) DEFAULT 0.0000,
    reserved_qty NUMBER(18,4) DEFAULT 0.0000,
    planned_receipt_qty NUMBER(18,4) DEFAULT 0.0000,
    net_requirement NUMBER(18,4) NOT NULL,
    suggested_order_qty NUMBER(18,4) NOT NULL,
    suggested_supplier_id NUMBER(19) NULL,
    suggested_due_date DATE NULL,
    CONSTRAINT fk_mrp_item_run FOREIGN KEY (run_id) REFERENCES mrp_runs(id) ON DELETE CASCADE,
    CONSTRAINT fk_mrp_item_parent FOREIGN KEY (parent_product_id) REFERENCES products(id),
    CONSTRAINT fk_mrp_item_component FOREIGN KEY (component_product_id) REFERENCES products(id),
    CONSTRAINT fk_mrp_item_supplier FOREIGN KEY (suggested_supplier_id) REFERENCES suppliers(id)
);

CREATE INDEX idx_mrp_item_component ON mrp_run_items (component_product_id);

CREATE TABLE work_order_operations (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_order_id NUMBER(19) NOT NULL,
    operation_id NUMBER(19) NOT NULL,
    operation_seq NUMBER(10) NOT NULL,
    planned_start TIMESTAMP(0) NULL,
    planned_end TIMESTAMP(0) NULL,
    actual_start TIMESTAMP(0) NULL,
    actual_end TIMESTAMP(0) NULL,
    status VARCHAR2(20) DEFAULT 'pending',
    assigned_employee_id NUMBER(19) NULL,
    qualified_qty NUMBER(10) DEFAULT 0,
    scrapped_qty NUMBER(10) DEFAULT 0,
    rework_qty NUMBER(10) DEFAULT 0,
    CONSTRAINT fk_wo_op_work_order FOREIGN KEY (work_order_id) REFERENCES work_orders(id) ON DELETE CASCADE,
    CONSTRAINT fk_wo_op_operation FOREIGN KEY (operation_id) REFERENCES production_operations(id),
    CONSTRAINT fk_wo_op_employee FOREIGN KEY (assigned_employee_id) REFERENCES employees(id),
    CONSTRAINT uk_work_order_operation UNIQUE (work_order_id, operation_seq)
);

CREATE TABLE operation_reports (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_order_operation_id NUMBER(19) NOT NULL,
    report_no VARCHAR2(30) NOT NULL UNIQUE,
    employee_id NUMBER(19) NOT NULL,
    report_time TIMESTAMP(0) NOT NULL,
    input_qty NUMBER(10) NOT NULL,
    qualified_qty NUMBER(10) NOT NULL,
    scrapped_qty NUMBER(10) DEFAULT 0,
    rework_qty NUMBER(10) DEFAULT 0,
    labor_minutes NUMBER(10,2) DEFAULT 0.00,
    machine_minutes NUMBER(10,2) DEFAULT 0.00,
    CONSTRAINT fk_operation_report_op FOREIGN KEY (work_order_operation_id) REFERENCES work_order_operations(id),
    CONSTRAINT fk_operation_report_employee FOREIGN KEY (employee_id) REFERENCES employees(id)
);

CREATE INDEX idx_operation_report_time ON operation_reports (report_time);

CREATE TABLE material_issues (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    issue_no VARCHAR2(30) NOT NULL UNIQUE,
    work_order_id NUMBER(19) NOT NULL,
    warehouse_id NUMBER(19) NOT NULL,
    issue_date DATE NOT NULL,
    issued_by NUMBER(19) NOT NULL,
    status VARCHAR2(20) DEFAULT 'draft',
    CONSTRAINT fk_material_issue_work_order FOREIGN KEY (work_order_id) REFERENCES work_orders(id),
    CONSTRAINT fk_material_issue_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouses(id),
    CONSTRAINT fk_material_issue_employee FOREIGN KEY (issued_by) REFERENCES employees(id)
);

CREATE TABLE material_issue_items (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    issue_id NUMBER(19) NOT NULL,
    product_id NUMBER(19) NOT NULL,
    batch_id NUMBER(19) NULL,
    required_qty NUMBER(18,4) NOT NULL,
    issued_qty NUMBER(18,4) NOT NULL,
    unit_cost NUMBER(18,4) NOT NULL,
    CONSTRAINT fk_material_issue_item_issue FOREIGN KEY (issue_id) REFERENCES material_issues(id) ON DELETE CASCADE,
    CONSTRAINT fk_material_issue_item_product FOREIGN KEY (product_id) REFERENCES products(id),
    CONSTRAINT fk_material_issue_item_batch FOREIGN KEY (batch_id) REFERENCES product_batches(id)
);

CREATE TABLE finished_goods_receipts (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_no VARCHAR2(30) NOT NULL UNIQUE,
    work_order_id NUMBER(19) NOT NULL,
    product_id NUMBER(19) NOT NULL,
    batch_id NUMBER(19) NULL,
    warehouse_id NUMBER(19) NOT NULL,
    receipt_date DATE NOT NULL,
    received_qty NUMBER(10) NOT NULL,
    unit_cost NUMBER(18,4) DEFAULT 0.0000,
    received_by NUMBER(19) NOT NULL,
    status VARCHAR2(20) DEFAULT 'draft',
    CONSTRAINT fk_fg_receipt_work_order FOREIGN KEY (work_order_id) REFERENCES work_orders(id),
    CONSTRAINT fk_fg_receipt_product FOREIGN KEY (product_id) REFERENCES products(id),
    CONSTRAINT fk_fg_receipt_batch FOREIGN KEY (batch_id) REFERENCES product_batches(id),
    CONSTRAINT fk_fg_receipt_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouses(id),
    CONSTRAINT fk_fg_receipt_employee FOREIGN KEY (received_by) REFERENCES employees(id)
);

CREATE TABLE standard_costs (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id NUMBER(19) NOT NULL,
    cost_version VARCHAR2(20) NOT NULL,
    material_cost NUMBER(18,4) DEFAULT 0.0000,
    labor_cost NUMBER(18,4) DEFAULT 0.0000,
    overhead_cost NUMBER(18,4) DEFAULT 0.0000,
    effective_from DATE NOT NULL,
    effective_to DATE NULL,
    status VARCHAR2(20) DEFAULT 'draft',
    approved_by NUMBER(19) NULL,
    CONSTRAINT fk_std_cost_product FOREIGN KEY (product_id) REFERENCES products(id),
    CONSTRAINT fk_std_cost_approved FOREIGN KEY (approved_by) REFERENCES employees(id),
    CONSTRAINT uk_product_cost_version UNIQUE (product_id, cost_version)
);

CREATE TABLE inventory_cost_layers (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id NUMBER(19) NOT NULL,
    batch_id NUMBER(19) NULL,
    warehouse_id NUMBER(19) NOT NULL,
    source_type VARCHAR2(40) NOT NULL,
    source_id NUMBER(19) NOT NULL,
    receipt_date DATE NOT NULL,
    original_qty NUMBER(18,4) NOT NULL,
    remaining_qty NUMBER(18,4) NOT NULL,
    unit_cost NUMBER(18,4) NOT NULL,
    currency VARCHAR2(3) DEFAULT 'CNY',
    CONSTRAINT fk_cost_layer_product FOREIGN KEY (product_id) REFERENCES products(id),
    CONSTRAINT fk_cost_layer_batch FOREIGN KEY (batch_id) REFERENCES product_batches(id),
    CONSTRAINT fk_cost_layer_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouses(id)
);

CREATE INDEX idx_cost_layer_source ON inventory_cost_layers (source_type, source_id);
CREATE INDEX idx_cost_layer_product_date ON inventory_cost_layers (product_id, receipt_date);

CREATE TABLE inventory_valuation_snapshots (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_date DATE NOT NULL,
    product_id NUMBER(19) NOT NULL,
    warehouse_id NUMBER(19) NOT NULL,
    quantity NUMBER(18,4) NOT NULL,
    unit_cost NUMBER(18,4) NOT NULL,
    inventory_value NUMBER(18,2) NOT NULL,
    valuation_method VARCHAR2(30) NOT NULL,
    CONSTRAINT fk_inv_value_product FOREIGN KEY (product_id) REFERENCES products(id),
    CONSTRAINT fk_inv_value_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouses(id),
    CONSTRAINT uk_inv_value_snapshot UNIQUE (snapshot_date, product_id, warehouse_id, valuation_method)
);

CREATE TABLE work_order_costs (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_order_id NUMBER(19) NOT NULL,
    material_cost NUMBER(18,2) DEFAULT 0.00,
    labor_cost NUMBER(18,2) DEFAULT 0.00,
    overhead_cost NUMBER(18,2) DEFAULT 0.00,
    finished_qty NUMBER(10) DEFAULT 0,
    unit_cost NUMBER(18,4) DEFAULT 0.0000,
    variance_amount NUMBER(18,2) DEFAULT 0.00,
    calculated_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_work_order_cost_work_order FOREIGN KEY (work_order_id) REFERENCES work_orders(id),
    CONSTRAINT uk_work_order_cost UNIQUE (work_order_id)
);

CREATE TABLE cogs_entries (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sales_order_id NUMBER(19) NOT NULL,
    sales_order_item_id NUMBER(19) NOT NULL,
    product_id NUMBER(19) NOT NULL,
    batch_id NUMBER(19) NULL,
    quantity NUMBER(18,4) NOT NULL,
    unit_cost NUMBER(18,4) NOT NULL,
    cogs_amount NUMBER(18,2) NOT NULL,
    voucher_id NUMBER(19) NULL,
    posted_at TIMESTAMP(0) NULL,
    CONSTRAINT fk_cogs_order FOREIGN KEY (sales_order_id) REFERENCES sales_orders(id),
    CONSTRAINT fk_cogs_order_item FOREIGN KEY (sales_order_item_id) REFERENCES sales_order_items(id),
    CONSTRAINT fk_cogs_product FOREIGN KEY (product_id) REFERENCES products(id),
    CONSTRAINT fk_cogs_batch FOREIGN KEY (batch_id) REFERENCES product_batches(id),
    CONSTRAINT fk_cogs_voucher FOREIGN KEY (voucher_id) REFERENCES vouchers(id)
);

CREATE TABLE account_subjects (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id NUMBER(19) NULL,
    subject_code VARCHAR2(30) NOT NULL UNIQUE,
    subject_name VARCHAR2(100) NOT NULL,
    subject_type VARCHAR2(20) NOT NULL,
    balance_direction VARCHAR2(10) NOT NULL,
    is_leaf NUMBER(1) DEFAULT 1,
    status VARCHAR2(20) DEFAULT 'active',
    CONSTRAINT fk_subject_parent FOREIGN KEY (parent_id) REFERENCES account_subjects(id)
);

CREATE TABLE opening_balances (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ledger_book_id NUMBER(19) NOT NULL,
    subject_id NUMBER(19) NOT NULL,
    period_code VARCHAR2(7) NOT NULL,
    debit_amount NUMBER(18,2) DEFAULT 0.00,
    credit_amount NUMBER(18,2) DEFAULT 0.00,
    CONSTRAINT fk_opening_balance_book FOREIGN KEY (ledger_book_id) REFERENCES ledger_books(id),
    CONSTRAINT fk_opening_balance_subject FOREIGN KEY (subject_id) REFERENCES account_subjects(id),
    CONSTRAINT uk_opening_balance UNIQUE (ledger_book_id, subject_id, period_code)
);

CREATE TABLE account_balances (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ledger_book_id NUMBER(19) NOT NULL,
    subject_id NUMBER(19) NOT NULL,
    period_code VARCHAR2(7) NOT NULL,
    begin_debit NUMBER(18,2) DEFAULT 0.00,
    begin_credit NUMBER(18,2) DEFAULT 0.00,
    current_debit NUMBER(18,2) DEFAULT 0.00,
    current_credit NUMBER(18,2) DEFAULT 0.00,
    ending_debit NUMBER(18,2) DEFAULT 0.00,
    ending_credit NUMBER(18,2) DEFAULT 0.00,
    CONSTRAINT fk_account_balance_book FOREIGN KEY (ledger_book_id) REFERENCES ledger_books(id),
    CONSTRAINT fk_account_balance_subject FOREIGN KEY (subject_id) REFERENCES account_subjects(id),
    CONSTRAINT uk_account_balance UNIQUE (ledger_book_id, subject_id, period_code)
);

CREATE TABLE budget_versions (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ledger_book_id NUMBER(19) NOT NULL,
    version_code VARCHAR2(30) NOT NULL,
    version_name VARCHAR2(100) NOT NULL,
    fiscal_year NUMBER(10) NOT NULL,
    status VARCHAR2(20) DEFAULT 'draft',
    approved_by NUMBER(19) NULL,
    CONSTRAINT fk_budget_version_book FOREIGN KEY (ledger_book_id) REFERENCES ledger_books(id),
    CONSTRAINT fk_budget_version_approved FOREIGN KEY (approved_by) REFERENCES employees(id),
    CONSTRAINT uk_budget_version UNIQUE (ledger_book_id, version_code)
);

CREATE TABLE budget_items (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version_id NUMBER(19) NOT NULL,
    department_id NUMBER(19) NOT NULL,
    subject_id NUMBER(19) NOT NULL,
    period_code VARCHAR2(7) NOT NULL,
    budget_amount NUMBER(18,2) NOT NULL,
    used_amount NUMBER(18,2) DEFAULT 0.00,
    CONSTRAINT fk_budget_item_version FOREIGN KEY (version_id) REFERENCES budget_versions(id) ON DELETE CASCADE,
    CONSTRAINT fk_budget_item_department FOREIGN KEY (department_id) REFERENCES departments(id),
    CONSTRAINT fk_budget_item_subject FOREIGN KEY (subject_id) REFERENCES account_subjects(id),
    CONSTRAINT uk_budget_item UNIQUE (version_id, department_id, subject_id, period_code)
);

CREATE TABLE ar_invoices (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ar_no VARCHAR2(30) NOT NULL UNIQUE,
    sales_order_id NUMBER(19) NOT NULL,
    customer_id NUMBER(19) NOT NULL,
    invoice_date DATE NOT NULL,
    due_date DATE NOT NULL,
    invoice_amount NUMBER(18,2) NOT NULL,
    paid_amount NUMBER(18,2) DEFAULT 0.00,
    writeoff_amount NUMBER(18,2) DEFAULT 0.00,
    status VARCHAR2(20) DEFAULT 'open',
    CONSTRAINT fk_ar_invoice_order FOREIGN KEY (sales_order_id) REFERENCES sales_orders(id),
    CONSTRAINT fk_ar_invoice_customer FOREIGN KEY (customer_id) REFERENCES customers(id)
);

CREATE INDEX idx_ar_invoice_customer_due ON ar_invoices (customer_id, due_date);

CREATE TABLE ap_invoices (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ap_no VARCHAR2(30) NOT NULL UNIQUE,
    purchase_order_id NUMBER(19) NOT NULL,
    supplier_id NUMBER(19) NOT NULL,
    invoice_date DATE NOT NULL,
    due_date DATE NOT NULL,
    invoice_amount NUMBER(18,2) NOT NULL,
    paid_amount NUMBER(18,2) DEFAULT 0.00,
    status VARCHAR2(20) DEFAULT 'open',
    CONSTRAINT fk_ap_invoice_order FOREIGN KEY (purchase_order_id) REFERENCES purchase_orders(id),
    CONSTRAINT fk_ap_invoice_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers(id)
);

CREATE INDEX idx_ap_invoice_supplier_due ON ap_invoices (supplier_id, due_date);

CREATE TABLE payment_requests (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_no VARCHAR2(30) NOT NULL UNIQUE,
    supplier_id NUMBER(19) NOT NULL,
    requested_by NUMBER(19) NOT NULL,
    request_date DATE NOT NULL,
    planned_pay_date DATE NOT NULL,
    total_amount NUMBER(18,2) DEFAULT 0.00,
    status VARCHAR2(20) DEFAULT 'draft',
    CONSTRAINT fk_payment_request_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers(id),
    CONSTRAINT fk_payment_request_employee FOREIGN KEY (requested_by) REFERENCES employees(id)
);

CREATE TABLE payment_request_items (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id NUMBER(19) NOT NULL,
    ap_invoice_id NUMBER(19) NOT NULL,
    requested_amount NUMBER(18,2) NOT NULL,
    CONSTRAINT fk_payment_request_item_request FOREIGN KEY (request_id) REFERENCES payment_requests(id) ON DELETE CASCADE,
    CONSTRAINT fk_payment_request_item_ap FOREIGN KEY (ap_invoice_id) REFERENCES ap_invoices(id)
);

CREATE TABLE warehouse_zones (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_id NUMBER(19) NOT NULL,
    zone_code VARCHAR2(30) NOT NULL,
    zone_name VARCHAR2(100) NOT NULL,
    zone_type VARCHAR2(20) NOT NULL,
    CONSTRAINT fk_zone_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouses(id),
    CONSTRAINT uk_zone UNIQUE (warehouse_id, zone_code)
);

CREATE TABLE warehouse_locations (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    zone_id NUMBER(19) NOT NULL,
    location_code VARCHAR2(50) NOT NULL,
    location_type VARCHAR2(20) DEFAULT 'bin',
    max_weight_kg NUMBER(12,3) DEFAULT 0.000,
    max_volume_m3 NUMBER(12,6) DEFAULT 0.000000,
    status VARCHAR2(20) DEFAULT 'active',
    CONSTRAINT fk_location_zone FOREIGN KEY (zone_id) REFERENCES warehouse_zones(id),
    CONSTRAINT uk_location UNIQUE (zone_id, location_code)
);

CREATE TABLE inventory_location_balances (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_id NUMBER(19) NOT NULL,
    product_id NUMBER(19) NOT NULL,
    batch_id NUMBER(19) NULL,
    quantity NUMBER(18,4) NOT NULL,
    locked_quantity NUMBER(18,4) DEFAULT 0.0000,
    CONSTRAINT fk_loc_balance_location FOREIGN KEY (location_id) REFERENCES warehouse_locations(id),
    CONSTRAINT fk_loc_balance_product FOREIGN KEY (product_id) REFERENCES products(id),
    CONSTRAINT fk_loc_balance_batch FOREIGN KEY (batch_id) REFERENCES product_batches(id),
    CONSTRAINT uk_location_product_batch UNIQUE (location_id, product_id, batch_id)
);

CREATE TABLE putaway_tasks (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_no VARCHAR2(30) NOT NULL UNIQUE,
    receipt_id NUMBER(19) NOT NULL,
    product_id NUMBER(19) NOT NULL,
    batch_id NUMBER(19) NULL,
    from_location_id NUMBER(19) NULL,
    to_location_id NUMBER(19) NOT NULL,
    quantity NUMBER(18,4) NOT NULL,
    assigned_to NUMBER(19) NULL,
    status VARCHAR2(20) DEFAULT 'pending',
    CONSTRAINT fk_putaway_receipt FOREIGN KEY (receipt_id) REFERENCES purchase_receipts(id),
    CONSTRAINT fk_putaway_product FOREIGN KEY (product_id) REFERENCES products(id),
    CONSTRAINT fk_putaway_batch FOREIGN KEY (batch_id) REFERENCES product_batches(id),
    CONSTRAINT fk_putaway_to_location FOREIGN KEY (to_location_id) REFERENCES warehouse_locations(id),
    CONSTRAINT fk_putaway_employee FOREIGN KEY (assigned_to) REFERENCES employees(id)
);

CREATE TABLE picking_tasks (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_no VARCHAR2(30) NOT NULL UNIQUE,
    sales_order_id NUMBER(19) NOT NULL,
    warehouse_id NUMBER(19) NOT NULL,
    wave_no VARCHAR2(30) NULL,
    assigned_to NUMBER(19) NULL,
    status VARCHAR2(20) DEFAULT 'pending',
    CONSTRAINT fk_picking_order FOREIGN KEY (sales_order_id) REFERENCES sales_orders(id),
    CONSTRAINT fk_picking_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouses(id),
    CONSTRAINT fk_picking_employee FOREIGN KEY (assigned_to) REFERENCES employees(id)
);

CREATE TABLE picking_task_items (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    picking_task_id NUMBER(19) NOT NULL,
    sales_order_item_id NUMBER(19) NOT NULL,
    product_id NUMBER(19) NOT NULL,
    batch_id NUMBER(19) NULL,
    location_id NUMBER(19) NOT NULL,
    required_qty NUMBER(18,4) NOT NULL,
    picked_qty NUMBER(18,4) DEFAULT 0.0000,
    CONSTRAINT fk_picking_item_task FOREIGN KEY (picking_task_id) REFERENCES picking_tasks(id) ON DELETE CASCADE,
    CONSTRAINT fk_picking_item_order_item FOREIGN KEY (sales_order_item_id) REFERENCES sales_order_items(id),
    CONSTRAINT fk_picking_item_product FOREIGN KEY (product_id) REFERENCES products(id),
    CONSTRAINT fk_picking_item_batch FOREIGN KEY (batch_id) REFERENCES product_batches(id),
    CONSTRAINT fk_picking_item_location FOREIGN KEY (location_id) REFERENCES warehouse_locations(id)
);

CREATE TABLE repair_orders (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    repair_no VARCHAR2(30) NOT NULL UNIQUE,
    service_ticket_id NUMBER(19) NOT NULL,
    customer_id NUMBER(19) NOT NULL,
    product_id NUMBER(19) NOT NULL,
    serial_number_id NUMBER(19) NULL,
    received_date DATE NOT NULL,
    fault_desc VARCHAR2(500) NOT NULL,
    status VARCHAR2(20) DEFAULT 'received',
    technician_id NUMBER(19) NULL,
    estimated_cost NUMBER(18,2) DEFAULT 0.00,
    actual_cost NUMBER(18,2) DEFAULT 0.00,
    CONSTRAINT fk_repair_ticket FOREIGN KEY (service_ticket_id) REFERENCES service_tickets(id),
    CONSTRAINT fk_repair_customer FOREIGN KEY (customer_id) REFERENCES customers(id),
    CONSTRAINT fk_repair_product FOREIGN KEY (product_id) REFERENCES products(id),
    CONSTRAINT fk_repair_serial FOREIGN KEY (serial_number_id) REFERENCES serial_numbers(id),
    CONSTRAINT fk_repair_technician FOREIGN KEY (technician_id) REFERENCES employees(id)
);

CREATE TABLE repair_order_parts (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    repair_order_id NUMBER(19) NOT NULL,
    product_id NUMBER(19) NOT NULL,
    batch_id NUMBER(19) NULL,
    quantity NUMBER(18,4) NOT NULL,
    unit_cost NUMBER(18,4) NOT NULL,
    issued_from_warehouse_id NUMBER(19) NOT NULL,
    CONSTRAINT fk_repair_part_order FOREIGN KEY (repair_order_id) REFERENCES repair_orders(id) ON DELETE CASCADE,
    CONSTRAINT fk_repair_part_product FOREIGN KEY (product_id) REFERENCES products(id),
    CONSTRAINT fk_repair_part_batch FOREIGN KEY (batch_id) REFERENCES product_batches(id),
    CONSTRAINT fk_repair_part_warehouse FOREIGN KEY (issued_from_warehouse_id) REFERENCES warehouses(id)
);

CREATE TABLE numbering_rules (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_type VARCHAR2(50) NOT NULL UNIQUE,
    prefix VARCHAR2(20) NOT NULL,
    date_pattern VARCHAR2(20) DEFAULT 'YYYYMM',
    sequence_length NUMBER(10) DEFAULT 4,
    current_sequence NUMBER(10) DEFAULT 0,
    updated_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE master_data_change_requests (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_no VARCHAR2(30) NOT NULL UNIQUE,
    master_type VARCHAR2(20) NOT NULL,
    master_id NUMBER(19) NOT NULL,
    change_reason VARCHAR2(500) NOT NULL,
    requested_by NUMBER(19) NOT NULL,
    requested_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    approved_by NUMBER(19) NULL,
    approved_at TIMESTAMP(0) NULL,
    status VARCHAR2(20) DEFAULT 'submitted',
    CONSTRAINT fk_mdc_requested_by FOREIGN KEY (requested_by) REFERENCES employees(id),
    CONSTRAINT fk_mdc_approved_by FOREIGN KEY (approved_by) REFERENCES employees(id)
);

CREATE INDEX idx_mdc_master ON master_data_change_requests (master_type, master_id);

CREATE TABLE master_data_change_items (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id NUMBER(19) NOT NULL,
    field_name VARCHAR2(100) NOT NULL,
    old_value VARCHAR2(1000) NULL,
    new_value VARCHAR2(1000) NULL,
    CONSTRAINT fk_mdc_item_request FOREIGN KEY (request_id) REFERENCES master_data_change_requests(id) ON DELETE CASCADE
);

CREATE TABLE data_permission_scopes (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id NUMBER(19) NOT NULL,
    scope_type VARCHAR2(20) NOT NULL,
    scope_id NUMBER(19) NOT NULL,
    can_read NUMBER(1) DEFAULT 1,
    can_write NUMBER(1) DEFAULT 0,
    CONSTRAINT fk_data_scope_role FOREIGN KEY (role_id) REFERENCES roles(id),
    CONSTRAINT uk_data_scope UNIQUE (role_id, scope_type, scope_id)
);

CREATE TABLE sensitive_access_logs (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id NUMBER(19) NOT NULL,
    object_type VARCHAR2(50) NOT NULL,
    object_id NUMBER(19) NOT NULL,
    field_name VARCHAR2(100) NOT NULL,
    access_reason VARCHAR2(500) NULL,
    accessed_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sensitive_access_employee FOREIGN KEY (employee_id) REFERENCES employees(id)
);

CREATE INDEX idx_sensitive_access_object ON sensitive_access_logs (object_type, object_id);

-- ============================================================
-- Semantic-layer example support: region, fiscal calendar,
-- category dimension, payments, and sales fact.
-- Oracle 16/17/18 compatible.
-- ============================================================

CREATE TABLE region_dim (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_code VARCHAR2(30) NOT NULL UNIQUE,
    region_name VARCHAR2(100) NOT NULL,
    province VARCHAR2(50) NOT NULL,
    city VARCHAR2(50) NULL,
    district VARCHAR2(50) NULL,
    sales_region VARCHAR2(100) NOT NULL,
    region_level VARCHAR2(20) DEFAULT 'city',
    is_active NUMBER(1) DEFAULT 1,
    CONSTRAINT uk_region_location UNIQUE (province, city, district)
);

CREATE INDEX idx_region_sales_region ON region_dim (sales_region);

CREATE TABLE fiscal_calendar (
    calendar_date DATE PRIMARY KEY,
    fiscal_year NUMBER(10) NOT NULL,
    fiscal_quarter NUMBER(5) NOT NULL,
    fiscal_month NUMBER(5) NOT NULL,
    fiscal_month_name VARCHAR2(20) NOT NULL,
    period_code VARCHAR2(7) NOT NULL,
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    is_current_fiscal_year NUMBER(1) DEFAULT 0,
    accounting_period_id NUMBER(19) NULL,
    CONSTRAINT fk_fiscal_calendar_period FOREIGN KEY (accounting_period_id) REFERENCES accounting_periods(id)
);

CREATE INDEX idx_fiscal_calendar_year_month ON fiscal_calendar (fiscal_year, fiscal_month);
CREATE INDEX idx_fiscal_calendar_current ON fiscal_calendar (is_current_fiscal_year);

CREATE TABLE category_dim (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_category_id NUMBER(19) NOT NULL,
    category_code VARCHAR2(50) NOT NULL,
    level1_name VARCHAR2(100) NOT NULL,
    level2_name VARCHAR2(100) NULL,
    leaf_name VARCHAR2(100) NOT NULL,
    is_womenwear NUMBER(1) DEFAULT 0,
    effective_from DATE NOT NULL DEFAULT DATE '2026-01-01',
    effective_to DATE NULL,
    status VARCHAR2(20) DEFAULT 'active',
    CONSTRAINT fk_category_dim_source FOREIGN KEY (source_category_id) REFERENCES product_categories(id),
    CONSTRAINT uk_category_dim_source UNIQUE (source_category_id)
);

CREATE INDEX idx_category_dim_level1 ON category_dim (level1_name);
CREATE INDEX idx_category_dim_womenwear ON category_dim (is_womenwear);

CREATE TABLE payments (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_no VARCHAR2(40) NOT NULL UNIQUE,
    customer_id NUMBER(19) NOT NULL,
    order_id NUMBER(19) NULL,
    receipt_id NUMBER(19) NULL,
    journal_id NUMBER(19) NULL,
    payment_date DATE NOT NULL,
    amount NUMBER(18,2) NOT NULL,
    currency VARCHAR2(3) DEFAULT 'CNY',
    order_status VARCHAR2(30) NOT NULL,
    payment_status VARCHAR2(20) DEFAULT 'pending',
    failure_reason VARCHAR2(300) NULL,
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_payment_customer FOREIGN KEY (customer_id) REFERENCES customers(id),
    CONSTRAINT fk_payment_order FOREIGN KEY (order_id) REFERENCES sales_orders(id),
    CONSTRAINT fk_payment_receipt FOREIGN KEY (receipt_id) REFERENCES payment_receipts(id),
    CONSTRAINT fk_payment_journal FOREIGN KEY (journal_id) REFERENCES cashier_journals(id)
);

CREATE INDEX idx_payment_customer_date ON payments (customer_id, payment_date);
CREATE INDEX idx_payment_status_date ON payments (payment_status, payment_date);

CREATE TABLE sales_fact (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id NUMBER(19) NOT NULL,
    order_item_id NUMBER(19) NOT NULL,
    customer_id NUMBER(19) NOT NULL,
    product_id NUMBER(19) NOT NULL,
    category_dim_id NUMBER(19) NOT NULL,
    warehouse_id NUMBER(19) NOT NULL,
    region_dim_id NUMBER(19) NOT NULL,
    fiscal_date DATE NOT NULL,
    payment_id NUMBER(19) NULL,
    quantity_sold NUMBER(18,4) NOT NULL,
    sales_amount NUMBER(18,2) NOT NULL,
    paid_amount NUMBER(18,2) DEFAULT 0.00,
    refund_amount NUMBER(18,2) DEFAULT 0.00,
    net_sales_amount NUMBER(18,2) NOT NULL,
    gross_margin_amount NUMBER(18,2) DEFAULT 0.00,
    order_status VARCHAR2(30) NOT NULL,
    sales_channel VARCHAR2(30) DEFAULT 'direct',
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sales_fact_order FOREIGN KEY (order_id) REFERENCES sales_orders(id),
    CONSTRAINT fk_sales_fact_item FOREIGN KEY (order_item_id) REFERENCES sales_order_items(id),
    CONSTRAINT fk_sales_fact_customer FOREIGN KEY (customer_id) REFERENCES customers(id),
    CONSTRAINT fk_sales_fact_product FOREIGN KEY (product_id) REFERENCES products(id),
    CONSTRAINT fk_sales_fact_category FOREIGN KEY (category_dim_id) REFERENCES category_dim(id),
    CONSTRAINT fk_sales_fact_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouses(id),
    CONSTRAINT fk_sales_fact_region FOREIGN KEY (region_dim_id) REFERENCES region_dim(id),
    CONSTRAINT fk_sales_fact_fiscal FOREIGN KEY (fiscal_date) REFERENCES fiscal_calendar(calendar_date),
    CONSTRAINT fk_sales_fact_payment FOREIGN KEY (payment_id) REFERENCES payments(id),
    CONSTRAINT uk_sales_fact_item UNIQUE (order_item_id)
);

CREATE INDEX idx_sales_fact_customer_date ON sales_fact (customer_id, fiscal_date);
CREATE INDEX idx_sales_fact_region_category ON sales_fact (region_dim_id, category_dim_id, fiscal_date);
